(()=>{const original=globalThis.KoMath;
(function(root){const base=root.KoMath;let excluded=[];const specs=[{name:'격자에서 밀어서 옮기기',type:'move'},{name:'거울선으로 뒤집기',type:'flip'},{name:'중심 주위로 90도 돌리기',type:'turn'}].map(s=>({...s,activities:[{title:'옮긴 모양을 그려요'},{title:'처음 모양을 찾아요'},{title:'친구의 그림을 검토해요'}]}));
function generate(id,p,seed,n=8){const offset=base.profiles(id).length;if(id!=='4-1-4'||p<offset)return base.generate(id,p,seed,n);const s=specs[p-offset],art=KoArt.session(seed,excluded);let state=seed>>>0;const r=(a,b)=>{state=(Math.imul(state,1664525)+1013904223)>>>0;return a+Math.floor(state/4294967296*(b-a+1))};return s.activities.map((act,k)=>({title:act.title,skill:s.type,questions:Array.from({length:n},()=>{const dx=r(1,2),dy=1,shape=[[1,1],[2,1],[2,r(2,3)],[1,2]],transform=([x,y])=>s.type==='move'?[x+dx,y+dy]:s.type==='flip'?[6-x,y]:[6-y,x],dest=shape.map(transform),correct=r(0,1)===1,wrong=dest.map(([x,y])=>[x,y+1]),asset=art.take(x=>['음식','동물과 자연','놀이와 운동'].includes(x.category));
const instruction=s.type==='move'?'오른쪽으로 '+dx+'칸, 아래로 1칸 밀어서 옮깁니다.':s.type==='flip'?'점선을 거울선으로 하여 좌우로 뒤집습니다.':'중심점 주위로 시계 방향으로 90도 돌립니다.';
let svg='<svg class="transform-grid" viewBox="0 0 210 210">';for(let i=0;i<=6;i++)svg+='<path d="M15 '+(15+i*30)+'H195M'+(15+i*30)+' 15V195" stroke="#d7e4e5" stroke-width="1"/>';const poly=(points,color,extra='')=>'<polygon '+extra+' points="'+points.map(([x,y])=>(15+x*30)+','+(15+y*30)).join(' ')+'" fill="none" stroke="'+color+'" stroke-width="2.5"/>';
if(s.type==='flip')svg+='<path d="M105 10V200" stroke="#647c99" stroke-dasharray="5 3"/>';if(s.type==='turn')svg+='<circle cx="105" cy="105" r="3" fill="#647c99"/><text x="111" y="119" font-size="20">중심</text>';
let prompt,answer,reason;if(k===0){prompt=instruction+' 옮긴 모양을 그리세요.';svg+=poly(shape,'#247e79')+poly(dest,'#c62828','class="geometry-answer"');answer='빨간 모양을 확인하세요.';reason='모든 꼭짓점에 같은 이동 규칙을 적용합니다.'}if(k===1){prompt=instruction+' 그림은 옮긴 뒤의 모양입니다. 처음 모양을 그리세요.';svg+=poly(dest,'#247e79')+poly(shape,'#c62828','class="geometry-answer"');answer='빨간 모양이 처음 모양입니다.';reason='이동 과정을 거꾸로 되짚어 봅니다.'}if(k===2){prompt=instruction+' 초록 모양을 옮긴 결과가 보라 모양과 같나요? 틀리면 고쳐 그리세요.';svg+=poly(shape,'#247e79')+poly(correct?dest:wrong,'#8266a6')+poly(dest,'#c62828','class="geometry-answer"');answer=correct?'○':'×, 빨간 모양으로 고칩니다.';reason='모양의 크기는 바뀌지 않으며 모든 꼭짓점의 위치를 확인합니다.'}svg+='</svg>';
return {methodId:s.type+'-'+k,artId:asset.id,prompt,visual:'<span class="picture-badge">'+KoArt.icon(asset)+'</span>'+svg,task:'',answer,reason,check:{kind:'transform',shape,dest,type:s.type,dx,dy}};})}));}
root.KoMath={...base,profiles:id=>base.profiles(id).concat(id==='4-1-4'?specs:[]),generate,excludeArt:ids=>{excluded=ids;base.excludeArt(ids)}};
})(globalThis);

globalThis.ItGeometrySource=globalThis.KoMath;globalThis.KoMath=original;})();
