/* The original ko/engine.js is loaded first. Keep its generator and catalog intact. */
(()=>{
const source=KoMath;
const definitions=[
 ['it-1-contare',1,1,'Contare fino a 9','1-1-1','count:9'],
 ['it-1-confrontare',1,2,'Confrontare i numeri fino a 9','1-1-1','compare:9'],
 ['it-2-decine-unita',2,1,'Decine e unità','1-2-1','place:2'],
 ['it-2-addizioni',2,2,'Addizioni entro 100','2-1-3','add:99'],
 ['it-3-sottrazioni',3,1,'Sottrazioni entro 1 000','3-1-1','sub:999'],
 ['it-3-moltiplicazioni',3,2,'Moltiplicare per una cifra','3-1-4','mul:99'],
 ['it-4-angoli-retti',4,1,'Riconoscere gli angoli retti','4-1-2','angle-right'],
 ['it-4-simmetria',4,2,'Assi di simmetria del quadrato','4-1-2','symmetry-line'],
 ['it-5-frazioni-figure',5,1,'Ripasso: frazioni e figure','3-1-6','fraction-model'],
 ['it-5-confronto-frazioni',5,2,'Frazioni con lo stesso denominatore','3-2-5','fraction-compare'],
 ['it-4-tipi-angoli',4,3,'Angoli acuti, retti e ottusi','4-1-2','angle-type'],
 ['it-4-goniometro',4,4,'Leggere il goniometro','4-1-2','angle-measure'],
 ['it-5-perimetro-rettangolo',5,3,'Perimetro del rettangolo','5-1-6','perimeter'],
 ['it-5-area-rettangolo',5,4,'Area del rettangolo','5-1-6','area-rectangle']
];
definitions.push(['it-2-righello',2,3,'Leggere il righello','2-1-4','ruler:cm'],['it-3-centimetri-millimetri',3,3,'Centimetri e millimetri','3-1-5','convert:mm'],['it-3-metri-centimetri',3,4,'Metri e centimetri','2-2-3','convert:m'],['it-4-chilogrammi-grammi',4,5,'Chilogrammi e grammi','3-2-4','convert:kg'],['it-4-litri-millilitri',4,6,'Litri e millilitri','3-2-4','convert:L']);
definitions.push(['it-4-decimali-figure',4,7,'Decimi e numeri decimali','3-1-6','decimal-model'],['it-4-centesimi-decimali',4,8,'Dai centesimi ai numeri decimali','6-1-3','decimal-fraction'],['it-5-semplificare-frazioni',5,5,'Semplificare le frazioni','5-1-4','reduce'],['it-5-confrontare-denominatori',5,6,'Confrontare frazioni diverse','5-1-4','fraction-compare-unlike']);
const tr=s=>String(s).replaceAll("예각삼각형","triangolo acutangolo").replaceAll("직각삼각형","triangolo rettangolo").replaceAll("둔각삼각형","triangolo ottusangolo").replaceAll("직사각형","rettangolo").replaceAll("정사각형","quadrato").replaceAll("마름모","rombo").replaceAll("평행사변형","parallelogramma").replaceAll('반지름',"raggio").replaceAll('지름',"diametro").replaceAll('꼭짓점',"vertice").replaceAll('직육면체','parallelepipedo rettangolo').replaceAll('원기둥','cilindro').replace(/(?<![가-힣])구(?![가-힣])/g,'sfera').replaceAll('위에서 본 모양 · 숫자는 그 자리의 개수 · 아래쪽이 앞','Vista dall’alto: ogni numero indica i cubetti nella colonna. Il lato inferiore è il davanti.').replaceAll('불가능하다','impossibile').replaceAll('확실하다','certo').replaceAll('반반이다','probabilità del 50%').replaceAll('길이는 문제의 조건을 보세요','Misure indicate nel testo').replaceAll('삼각형','triangolo').replaceAll('사각형','quadrilatero').replaceAll('원','cerchio').replaceAll('선분','segmento').replaceAll('반직선','semiretta').replaceAll('직선','retta').replace(/(\d+)시\s*(\d+)분/g,(_,h,m)=>h+':'+m.padStart(2,'0')).replaceAll('친구의 답:','Risposta proposta:').replaceAll('맞으면 ○, 틀리면 ×. 틀린 답은 고치세요.','Vero: ○. Falso: ×. Correggi la risposta sbagliata.').replaceAll('바른 답:','Risposta corretta:').replaceAll('예각','acuto').replaceAll('직각','retto').replaceAll('둔각','ottuso').replaceAll('아니요','No').replaceAll('예','Sì').replaceAll('문제 그림','Figura dell’esercizio');
definitions.push(...[["it-2-leggere-tabelle",2,4,"Leggere le tabelle","2-2-5","table"],["it-3-pittogrammi",3,5,"Leggere i pittogrammi","3-2-6","graph:picture"],["it-4-grafici-barre",4,9,"Leggere i grafici a barre","4-1-5","graph:bar"],["it-5-media-aritmetica",5,7,"Calcolare la media aritmetica","5-2-6","average"]]);
definitions.push(...[["it-2-ore-mezzore",2,5,"Orologio: ore e mezzore","1-2-3","clock:30"],["it-2-settimane-giorni",2,6,"Settimane e giorni","2-2-4","calendar"],["it-3-orologio-minuti",3,6,"Orologio: intervalli di 5 minuti","2-2-4","clock:5"],["it-3-tempo-trascorso",3,7,"Calcolare l’orario finale","2-2-4","elapsed"],["it-4-minuti-secondi",4,10,"Convertire minuti e secondi","3-1-5","time-seconds"]]);
definitions.push(...[["it-1-figure-piane",1,3,"Riconoscere le figure piane","1-2-3","flat-basic"],["it-2-contare-lati",2,7,"Contare i lati delle figure","2-1-2","flat-count"],["it-3-linee-segmenti",3,8,"Rette, semirette e segmenti","3-1-2","lines"],["it-3-lati-poligoni",3,9,"Contare i lati dei poligoni","4-2-6","polygon"]]);
definitions.push(...[["it-4-somma-frazioni-stesso-denominatore",4,11,"Frazioni: somma con uguale denominatore","4-2-1","fraction-add-same"],["it-4-sottrazione-frazioni-stesso-denominatore",4,12,"Frazioni: sottrazione con uguale denominatore","4-2-1","fraction-sub-same"],["it-5-addizioni-frazioni",5,8,"Addizioni di frazioni","5-1-5","fraction-add"],["it-5-sottrazioni-frazioni",5,9,"Sottrazioni di frazioni","5-1-5","fraction-sub"]]);
definitions.push(...[["it-4-addizioni-decimali",4,13,"Addizioni con i numeri decimali","4-2-3","decimal-add"],["it-4-sottrazioni-decimali",4,14,"Sottrazioni con i numeri decimali","4-2-3","decimal-sub"],["it-5-decimali-per-interi",5,10,"Moltiplicare decimali per interi","5-2-4","decimal-mul-whole"],["it-5-decimali-divisi-interi",5,11,"Dividere decimali per interi","6-1-3","decimal-div-whole"]]);
definitions.push(...[["it-3-centinaia-decine-unita",3,10,"Centinaia, decine e unità","2-1-1","place:3"],["it-4-migliaia-cifre",4,15,"Riconoscere le cifre fino alle migliaia","2-2-1","place:4"],["it-5-divisori",5,12,"Trovare tutti i divisori","5-1-2","factor"],["it-5-multipli",5,13,"I primi tre multipli positivi","5-1-2","multiple"]]);
definitions.push(...[["it-5-arrotondare",5,14,"Arrotondare alle decine e centinaia","5-2-1","round-nearest"],["it-5-ordine-operazioni",5,15,"L’ordine delle operazioni","5-1-1","mixed"],["it-5-operazioni-parentesi",5,16,"Operazioni con le parentesi","5-1-1","mixed-bracket"],["it-5-denominatore-comune",5,17,"Il minimo denominatore comune","5-1-4","common-denominator"]]);
definitions.push(...[["it-5-area-triangolo",5,18,"Area del triangolo","5-1-6","area-triangle"],["it-5-area-parallelogramma",5,19,"Area del parallelogramma","5-1-6","area-parallelogram"],["it-5-area-trapezio",5,20,"Area del trapezio","5-1-6","area-trapezoid"],["it-5-area-rombo",5,21,"Area del rombo","5-1-6","area-rhombus"]]);
definitions.push(...[["it-5-percentuali",5,22,"Calcolare una percentuale","6-1-4","percent"],["it-5-probabilita-base",5,23,"Eventi certi, impossibili e al 50%","5-2-6","chance"],["it-5-media-dato-mancante",5,24,"La media e il dato mancante","5-2-6","average-missing"]]);
definitions.push(...[["it-2-contare-cubetti",2,8,"Contare i cubetti","2-1-2","cube-count"],["it-5-colonne-cubetti",5,25,"Contare cubetti da una pianta","6-2-3","cube-count"],["it-5-viste-cubetti",5,26,"Cubetti: vista frontale e laterale","6-2-3","cube-view"],["it-5-togliere-colonne",5,27,"Togliere una colonna di cubetti","6-2-3","cube-missing"]]);
definitions.push(["it-2-solidi",2,9,"Riconoscere i solidi","2-2-6","solid-basic"]);
definitions.push(...[["it-1-contare-forme",1,4,"Contare le forme uguali","1-1-2","sort"],["it-1-confrontare-lunghezze",1,5,"Confrontare le lunghezze","1-1-5","length-compare"]]);
const compareText=s=>String(s).replaceAll('막대가 길수록 길이가 큽니다.',"Confronta le lunghezze.").replace(/(?<![가-힣])(가|나)(?![가-힣])/g,(_,x)=>x==='가'?'A':'B');
definitions.push(...[["it-1-sequenze-forme",1,6,"Completare sequenze di forme","1-2-5","pattern"],["it-2-sequenze-numeri",2,10,"Numeri mancanti entro 100","1-2-1","sequence:100"]]);
definitions.push(...[["it-1-scomporre-numeri",1,7,"Scomporre i numeri entro 10","1-2-2","bond:10"],["it-2-moltiplicazioni-schieramenti",2,11,"Moltiplicazioni con schieramenti","2-1-6","array"]]);
definitions.push(...[["it-5-moltiplicare-decimali",5,28,"Moltiplicare due numeri decimali","5-2-4","decimal-mul"],["it-5-divisore-decimale",5,29,"Dividere per un numero decimale","6-2-2","decimal-div"]]);
definitions.push(...[["it-4-traslazioni-griglia",4,16,"Traslazioni sulla griglia","4-1-4","geometry-move"],["it-4-riflessioni-griglia",4,17,"Riflessioni sulla griglia","4-1-4","geometry-flip"],["it-5-rotazioni-griglia",5,30,"Rotazioni di 90 gradi sulla griglia","4-1-4","geometry-turn"]]);
const geometryText=s=>String(s).replaceAll('빨간 모양을 확인하세요.',"Controlla la figura rossa.").replaceAll('빨간 모양이 처음 모양입니다.',"La figura rossa è quella iniziale.").replaceAll('×, 빨간 모양으로 고칩니다.',"×, correggi seguendo la figura rossa.").replaceAll('중심',"Centro").replace(/src="art\//g,'src="/ko/art/').replace(/alt="[^"]*"/g,'alt=""');
definitions.push(...[["it-5-grafici-linee",5,31,"Grafici a linee: leggere e disegnare","4-2-5","data-line"],["it-5-diagrammi-nastro",5,32,"Percentuali e diagrammi a nastro","6-1-5","data-percent"]]);
const bankText=s=>String(s).replaceAll('전체',"totale").replaceAll('같습니다.',"Sono uguali.").replace(/(\d+)개 많습니다\./g,"$1 in più").replace(/(\d+)개 적습니다\./g,"$1 in meno").replaceAll('● 한 개는 10개를 나타냅니다.',"● = 10 elementi").replaceAll('늘어난 구간 없음',"Nessun aumento").replaceAll('에 경계',": confini").replaceAll('개','').replace(/(?<![가-힣])(월|화|수|목|가|나|다|라)(?![가-힣])/g,(_,x)=>({월:"Lun",화:"Mar",수:"Mer",목:"Gio",가:'A',나:'B',다:'C',라:'D'})[x]);
definitions.push(...[["it-4-costruire-grafici-barre",4,18,"Disegnare e confrontare grafici a barre","4-1-5","data-bar"],["it-3-pittogrammi-tabelle",3,11,"Pittogrammi: completare le tabelle","3-2-6","data-picture"]]);
definitions.push(...[["it-4-raggio-cerchio",4,19,"Riconoscere il raggio del cerchio","3-2-2","circle-parts"],["it-4-diametro-cerchio",4,20,"Calcolare il diametro del cerchio","3-2-2","circle-size"]]);
definitions.push(...[["it-4-classificare-triangoli",4,21,"Classificare i triangoli per angoli","4-2-2","triangle-type"],["it-4-classificare-quadrilateri",4,22,"Classificare i quadrilateri","4-2-4","quad-type"]]);
definitions.push(...[["it-3-metri-centimetri-confronti",3,12,"Metri e centimetri: convertire e confrontare","2-2-3","metric-m-cm",0],["it-4-peso-conversioni-confronti",4,23,"Chilogrammi e grammi: equivalenze","3-2-4","metric-kg-g",1],["it-4-capacita-conversioni-confronti",4,24,"Litri e millilitri: equivalenze","3-2-4","metric-L-mL",0]]);
definitions.push(...[["it-3-centimetri-millimetri-equivalenze",3,13,"Centimetri e millimetri: equivalenze","3-1-5","metric-cm-mm",0],["it-3-chilometri-metri-equivalenze",3,14,"Chilometri e metri: equivalenze","3-1-5","metric-km-m",1]]);
definitions.push(...[["it-2-disegnare-orologio",2,12,"Disegnare l’orologio: ore e mezzore","1-2-3","time-clock-30",0],["it-3-disegnare-minuti",3,15,"Disegnare l’orologio ogni 5 minuti","2-2-4","time-clock-5",0],["it-3-partenza-arrivo-durata",3,16,"Partenza, arrivo e tempo trascorso","3-1-5","time-duration",2]]);
definitions.push(["it-5-metri-quadrati-centimetri",5,33,"Metri quadrati e centimetri quadrati","5-1-6","metric-m²-cm²",0]);
definitions.push(["it-5-frazioni-per-naturali",5,34,"Frazioni per un numero naturale","5-2-2","fraction-mul-whole"]);
const documentLang='it';
const clockCopy={"draw":"Disegna le lancette per indicare le ","read":"Leggi l’ora e scrivi anche che ora sarà dopo 30 minuti.","long":"La lancetta dei minuti indica ","short":" e quella delle ore indica ","between":" ed è tra ","end":". Scrivi l’ora e disegna le lancette.","reason":"La lancetta corta indica le ore, quella lunga i minuti. Ogni intervallo grande vale 5 minuti.","now":"Ora attuale","later":"Dopo 30 minuti","time":"Ora","work":"Calcolo o linea del tempo","answer":"Risposta","duration":["Tempo trascorso","Ora di partenza","Ora di arrivo"],"clock":["Disegna le lancette","Leggi e aggiungi tempo","Ricostruisci l’ora"],"start":"Partenza: ","arrival":"Arrivo: ","elapsed":"Tempo trascorso: ","askDuration":"Quanto tempo è trascorso?","askStart":"A che ora è iniziato?","askEnd":"A che ora è finito?","reasons":["Sottrai l’ora iniziale da quella finale.","Sottrai la durata dall’ora finale.","Aggiungi la durata all’ora iniziale."]};
const timeText=s=>String(s).replaceAll('class="learning-clock"','class="learning-clock" style="width:85px;height:85px"').replaceAll('식 또는 시간선',clockCopy.work).replaceAll('30분 뒤',clockCopy.later).replaceAll('지금',clockCopy.now).replaceAll('시각',clockCopy.time).replaceAll('답:',clockCopy.answer+':').replace(/(\d+)분/g,'$1 min');
const dataText=s=>String(s).replaceAll('사과','Mele').replaceAll('배','Pere').replaceAll('귤','Mandarini').replace(/● 한 개는 (\d+)명/g,'● = $1 persone').replaceAll('선택한 사람 수 (명)','Numero di persone').replace(/>(가|나|다)</g,(_,x)=>'>'+({가:'A',나:'B',다:'C'}[x])+'<');
const decimalText=s=>String(s).split(/(<[^>]*>)/g).map((t,i)=>i%2?t:t.replace(/(\d)\.(\d)/g,'$1,$2')).join('');
globalThis.ItSourceMath=source;globalThis.ItDefinitions=definitions;
globalThis.KoCatalog={units:definitions.map(([id,grade,number,name])=>({id,grade,number,name,semester:1,gradeLabel:'Classe '+grade})),themes:Array.from({length:10},()=>['Un passo alla volta','Osserva, calcola e spiega','#278477','#edf8e9','rabbit'])};
globalThis.KoMath={...source,profiles(id){const d=definitions.find(x=>x[0]===id);return d?[{name:d[3]}]:[];},generate(id,p,seed,n){
 const d=definitions.find(x=>x[0]===id);if(!d||p!==0)throw Error('Unsupported Italian topic');
 return ((d[5].startsWith('metric-')||(d[5].startsWith('time-clock')||d[5]==='time-duration'))?ItMeasurementSource.generate(d[4],source.profiles(d[4]).length+d[6],seed,n):d[5].startsWith('data-')?ItDataSource.generate(d[4],source.profiles(d[4]).length,seed,n):d[5].startsWith('geometry-')?ItGeometrySource.generate(d[4],source.profiles(d[4]).length+['geometry-move','geometry-flip','geometry-turn'].indexOf(d[5]),seed,n):source.generate(d[4],0,seed,n,[0,1,2].map(mode=>({skill:d[5],mode})))).map((s,i)=>({...s,title:(d[5].startsWith('time-clock')||d[5]==='time-duration')?["Disegna o calcola","Leggi e completa","Trova il dato mancante"][i]:d[5].startsWith('metric-')?["Converti la misura","Completa l’equivalenza","Confronta le misure"][i]:d[5].startsWith('data-')?["Leggi i dati","Rappresenta i dati","Ragiona sui dati"][i]:d[5].startsWith('geometry-')?["Disegna la figura trasformata","Trova la figura iniziale","Controlla il disegno"][i]:['Osserva e risolvi','Completa o scegli','Controlla la risposta'][i],questions:s.questions.map(q=>{
  const skill=d[5].split(':')[0];let prompt,reason;
  if(d[5].startsWith('time-clock')){if(i===0){const m=q.answer.match(/(\d+)시 (\d+)분/);prompt=clockCopy.draw+m[1]+':'+m[2].padStart(2,'0')+'.';}else if(i===1)prompt=clockCopy.read;else{const m=q.prompt.match(/긴바늘이 (\d+)를 가리키고 짧은바늘은 (\d+)(?:와 (\d+) 사이)?/);prompt=clockCopy.long+m[1]+(m[3]?(documentLang==='it'?' e quella delle ore è tra ':' y la de las horas está entre ')+m[2]+(documentLang==='it'?' e ':' y ')+m[3]:clockCopy.short+m[2])+clockCopy.end;}reason="Ore: lancetta corta. Minuti: lancetta lunga.";}
  else if(q.check?.kind==='duration'){const c=q.check,fmt=t=>Math.floor(t/60)+':'+String(t%60).padStart(2,'0');prompt=i===0?clockCopy.start+fmt(c.start)+'. '+clockCopy.arrival+fmt(c.end)+'. '+clockCopy.askDuration:i===1?clockCopy.arrival+fmt(c.end)+'. '+clockCopy.elapsed+c.duration+' min. '+clockCopy.askStart:clockCopy.start+fmt(c.start)+'. '+clockCopy.elapsed+c.duration+' min. '+clockCopy.askEnd;reason=clockCopy.reasons[i];}
  else if(q.check?.kind==='measurement'){const m=q.check,[_,large,small]=d[5].split('-');prompt=["Esprimi la misura usando soltanto l’unità più piccola.","Completa i numeri mancanti per usare entrambe le unità.","Porta le misure alla stessa unità e confrontale con >, = oppure <."][i];reason=i===0?'1 '+large+' = '+m.factor+' '+small+'; '+m.a+' × '+m.factor+' + '+m.b+' = '+m.total+' '+small:i===1?m.total+' '+small+' = '+m.a+' × '+m.factor+' '+small+' + '+m.b+' '+small:"Confronta "+m.total+' '+small+' / '+q.task.match(/(\d+)[a-zA-Z²³]+$/)[1]+' '+small+'.';}
  else if(d[5]==='data-bar'){prompt=["Indica tutte le categorie più numerose e il totale degli elementi.","Completa il grafico disegnando le barre corrispondenti alla tabella.","Confronta A+B con C+D: indica di quanto il primo totale è maggiore o minore, oppure se sono uguali."][i];reason=["Trova il valore massimo e somma tutti i valori.","Controlla etichette e scala prima di disegnare le barre.","Somma le due coppie e confronta i risultati."][i];}
  else if(d[5]==='data-picture'){prompt=i===0?"Quanti elementi rappresenta A? Quanti sono gli elementi in totale?":i===1?"Completa la tabella con i valori reali del pittogramma.":"Correggi questa frase: “A e B rappresentano "+(q.check.values[0]+q.check.values[1])+" elementi in tutto”.";reason=["Ogni simbolo rappresenta 10 elementi: moltiplica il numero dei simboli per 10.","Leggi la legenda prima di completare ogni colonna.","Non confondere il numero dei simboli con il numero degli elementi."][i];}
  else if(q.check?.kind==='data-target'){prompt=(d[5]==='data-line'?["Indica il valore massimo e tutti i giorni in cui si verifica.","Disegna i punti della tabella e uniscili in ordine per completare il grafico.","Trova tutti gli intervalli con il maggiore aumento e indica di quanto aumenta. Se non aumenta mai, scrivi “nessun aumento”."]:["Se il totale è 200 elementi, quanti appartengono alla categoria A?","Segna i confini nel diagramma a nastro e scrivi le categorie secondo le percentuali della tabella.","La somma delle percentuali A e B è maggiore della somma di C e D? Confrontale con i numeri."])[i];reason=d[5]==='data-line'?["Cerca tutti i giorni con lo stesso valore massimo.","Controlla le etichette e la scala degli assi.","Confronta le differenze tra giorni consecutivi, non solo i valori."][i]:i===0?q.reason:i===1?"Segna le percentuali cumulative nell’ordine A, B, C, D.":"Somma le percentuali delle due coppie e confrontale.";}
  else if(q.check?.kind==='transform'){const inst=q.check.type==='move'?"Sposta la figura di "+q.check.dx+" caselle a destra e di una casella in basso.":q.check.type==='flip'?"Rifletti la figura rispetto alla linea tratteggiata.":"Ruota la figura di 90° in senso orario intorno al punto indicato.";prompt=inst+[" Disegna la figura trasformata."," La figura mostra il risultato: disegna la figura iniziale."," La figura viola è il risultato corretto della trasformazione della figura verde? Correggila se necessario."][i];reason=["Applica la stessa trasformazione a ogni vertice.","Ripercorri la trasformazione al contrario.","Controlla la posizione di ogni vertice: forma e dimensioni restano uguali."][i];}
  else if(q.check?.kind==='calc'){const c=q.check;prompt=['Calcola il risultato.','Scrivi il numero mancante.','Controlla il risultato di '+q.reason.split(' = ')[0]+'.'][i];reason=q.reason.replaceAll('이므로',', quindi');}
  else if(q.check?.kind==='fraction'){prompt=i===1?'Completa il numeratore mancante.':i===2?'Calcola e controlla il risultato proposto.':d[4]==='4-2-1'?'Calcola il risultato.':'Calcola e scrivi una frazione ridotta o un numero intero.';reason=q.reason;}
  else if(skill==='perimeter'){const c=q.check;prompt='Qual è il perimetro del rettangolo in cm?';reason='('+c.a+' + '+c.b+') × 2 = '+c.result+' cm';}
  else if(skill==='area-rectangle'){const c=q.check;prompt='Qual è l’area del rettangolo in cm²?';reason=c.a+' × '+c.b+' = '+c.result+' cm²';}
  else if(skill==='angle-type'){prompt='L’angolo è acuto, retto oppure ottuso?';reason='Acuto: meno di 90°. Retto: 90°. Ottuso: più di 90° e meno di 180°.';}
  else if(skill==='angle-measure'){prompt='Leggi il goniometro. Quanto misura l’angolo?';const degrees=q.reason.match(/(\d+)°를/)[1];reason='Parti dallo zero a destra: l’altro lato indica '+degrees+'°.';}
  else if(skill==='ruler'){prompt='Quanto è lunga la barretta in cm?';reason='Sottrai la misura iniziale da quella finale: '+q.reason+'.';}
  else if(skill==='convert'){const m=q.prompt.match(/^(\d+)(\w+) (\d+)(\w+)는 몇 (\w+)인가요/);prompt='Esprimi '+m[1]+' '+m[2]+' e '+m[3]+' '+m[4]+' in '+m[5]+'.';reason=q.reason.replaceAll('입니다.','.');}
  else if(skill==='decimal-model'){prompt='Scrivi la parte colorata come numero decimale.';reason=q.reason;}
  else if(skill==='decimal-fraction'){const n=q.prompt.match(/^(\d+)\/100/)[1];prompt='Scrivi '+n+'/100 come numero decimale.';reason=n+' centesimi: usa due cifre dopo la virgola.';}
  else if(skill==='reduce'){prompt='Riduci la frazione ai minimi termini.';const n=q.reason.match(/(\d+)로/)[1];reason='Dividi numeratore e denominatore per il loro massimo comune divisore, '+n+'.';}
  else if(skill==='fraction-compare-unlike'){prompt='Confronta le frazioni con denominatori diversi.';reason='Porta le frazioni allo stesso denominatore e confronta i numeratori.';}
  else if(skill==='table'){const fruit=q.prompt.match(/^(사과|배|귤)/)[1];prompt='Quanti elementi ci sono nella colonna '+dataText(fruit)+'?';reason='Leggi il numero sotto il nome del frutto nella tabella.';}
  else if(skill==='graph'){if(i===2){prompt='Somma i valori delle categorie A e B.';reason=q.reason;}else{const label=({가:'A',나:'B',다:'C'})[q.prompt[0]];prompt='Quante persone hanno scelto la categoria '+label+'?';reason='Leggi la scala o la legenda e trova il valore della categoria.';}}
  else if(skill==='average'){const sum=q.reason.match(/합 (\d+)/)[1];prompt='Calcola la media dei tre numeri.';reason='Dividi la somma '+sum+' per il numero dei dati, 3.';}
  else if(skill==='clock'){prompt='Scrivi l’ora indicata dall’orologio.';reason='La lancetta corta indica le ore; quella lunga indica i minuti.';}
  else if(skill==='calendar'){const weeks=q.prompt.match(/^(\d+)/)[1];prompt='Quanti giorni ci sono in '+weeks+' '+(weeks==='1'?'settimana':'settimane')+'?';reason='Una settimana ha 7 giorni: moltiplica il numero di settimane per 7.';}
  else if(skill==='elapsed'){const m=q.prompt.match(/^(\d+)시 (\d+)분부터 (\d+)분/);prompt='Ora iniziale: '+m[1]+':'+m[2].padStart(2,'0')+'. Che ora sarà dopo '+m[3]+' minuti?';reason='Aggiungi i minuti trascorsi. Ogni 60 minuti passa un’ora.';}
  else if(skill==='time-seconds'){const m=q.prompt.match(/^(\d+)분 (\d+)초/);prompt='Esprimi '+m[1]+' min e '+m[2]+' s in secondi.';reason=q.reason.replaceAll('입니다.','')+' s; 1 min = 60 s.';}
  else if(skill==='flat-basic'){prompt='Scrivi il nome della figura.';reason='Osserva i lati rettilinei e le linee curve.';}
  else if(skill==='flat-count'){prompt='Quanti lati rettilinei ha la figura?';reason='Il triangolo ha 3 lati, il quadrilatero 4; il cerchio non ha lati rettilinei.';}
  else if(skill==='lines'){prompt='La figura è una retta, una semiretta o un segmento?';reason='Il segmento ha due estremi; la semiretta ha un’origine; la retta prosegue in entrambe le direzioni.';}
  else if(skill==='polygon'){prompt='Quanti lati ha il poligono?';reason='Segui il contorno e conta ogni lato una sola volta.';}
  else if(skill==='factor'){const n=q.prompt.match(/^(\d+)/)[0];prompt='Scrivi tutti i divisori positivi di '+n+'.';reason='Cerca i numeri naturali che dividono '+n+' senza resto.';}
  else if(skill==='multiple'){const n=q.prompt.match(/^(\d+)/)[0];prompt='Scrivi i primi tre multipli positivi di '+n+' in ordine crescente.';reason='Moltiplica '+n+' per 1, 2 e 3.';}
  else if(skill==='round-nearest'){const n=q.prompt.match(/^(\d+)/)[0],place=q.prompt.includes('십')?'decina':'centinaio';prompt='Arrotonda '+n+' al '+(place==='decina'?'multiplo di 10':'multiplo di 100')+' più vicino.';reason='Osserva la cifra subito a destra della posizione da conservare: da 5 in su arrotonda per eccesso, altrimenti per difetto.';}
  else if(skill==='mixed'||skill==='mixed-bracket'){prompt='Calcola rispettando l’ordine delle operazioni.';reason=skill==='mixed-bracket'?'Calcola prima la somma tra parentesi, poi moltiplica.':'Esegui prima la moltiplicazione, poi l’addizione.';}
  else if(skill==='common-denominator'){const n=q.reason.match(/는 (\d+)/)[1];prompt='Riscrivi le frazioni con il minimo denominatore comune.';reason='Il minimo comune multiplo dei denominatori è '+n+'.';}
  else if(['area-triangle','area-parallelogram','area-trapezoid','area-rhombus'].includes(skill)){const c=q.check;const details=skill==='area-trapezoid'?'trapezio con basi '+c.a+' cm e '+c.c+' cm e altezza '+c.b+' cm':skill==='area-rhombus'?'rombo con diagonali '+c.a+' cm e '+c.b+' cm':(skill==='area-triangle'?'triangolo':'parallelogramma')+' con base '+c.a+' cm e altezza '+c.b+' cm';prompt='Calcola l’area in cm² del '+details+'.';if(i===1)prompt+=' Scegli il risultato.';if(i===2)prompt+=' Controlla la risposta proposta.';reason=(skill==='area-trapezoid'?'('+c.a+' + '+c.c+') × '+c.b+' ÷ 2':c.a+' × '+c.b+(skill==='area-parallelogram'?'':' ÷ 2'))+' = '+c.result+' cm²';}
  else if(skill==='percent'){const m=q.prompt.match(/전체 (\d+)개 중 (\d+)개/);prompt='Quale percentuale rappresentano '+m[2]+' elementi su un totale di '+m[1]+'?';reason='Dividi la parte per il totale e moltiplica per 100.';}
  else if(skill==='chance'){prompt=q.prompt.includes('빨간 공만')?'Una scatola contiene solo palline rosse. Quanto è probabile estrarre una pallina blu?':q.prompt.includes('파란 공만')?'Una scatola contiene solo palline blu. Quanto è probabile estrarre una pallina blu?':'Una scatola contiene una pallina rossa e una blu. Estrai una pallina a caso, senza guardare: quanto è probabile che sia rossa?';reason='Confronta il colore e il numero delle palline nella scatola.';}
  else if(skill==='average-missing'){const n=q.prompt.match(/평균이 (\d+)/)[1],sum=q.reason.match(/합 (\d+)/)[1];prompt='La media dei tre numeri è '+n+'. Trova il numero mancante.';reason='La somma dei tre numeri è '+sum+'. Sottrai i due numeri conosciuti.';}
  else if(['cube-count','cube-view','cube-missing'].includes(skill)){prompt=skill==='cube-view'?'Quanti quadrati si vedono nella vista '+(q.prompt.startsWith('앞')?'frontale':'da destra')+'?':skill==='cube-missing'?'Togli tutti i cubetti della colonna in alto a sinistra nella pianta. Quanti cubetti restano?':'Quanti cubetti ci sono in tutto?';reason=d[4]==='2-1-2'?'Conta una volta ciascun cubetto disegnato.':skill==='cube-view'?'Per ogni fila nella direzione di osservazione considera solo la colonna più alta; poi somma le altezze.':q.reason;}
  else if(skill==='solid-basic'){prompt="Qual è il nome del solido rappresentato?";reason="Osserva le superfici piane e curve. Confronta il disegno con un oggetto reale.";}
  else if(skill==='sort'){prompt="Quanti simboli uguali a "+q.prompt[0]+" ci sono?";reason="Raggruppa i simboli della stessa forma e contali.";}
  else if(skill==='length-compare'){prompt="Quale barretta è più lunga, A o B?";reason="Le barrette partono dallo stesso punto. Confronta dove arrivano.";}
  else if(skill==='pattern'){prompt="Quale simbolo continua la sequenza?";reason="Si ripete questo gruppo: "+q.reason.replace('가 반복됩니다.','')+'.';}
  else if(skill==='sequence'){prompt="Scrivi il numero mancante.";reason="Ogni numero aumenta di "+q.reason.match(/^\d+/)[0]+'.';}
  else if(skill==='bond'){const m=q.prompt.match(/^(\d+)을 (\d+)과/);prompt="Scomponi "+m[1]+" in "+m[2]+" e un’altra parte. Qual è la parte mancante?";reason=q.reason;}
  else if(skill==='circle-parts'){prompt="Come si chiama il segmento che unisce il centro a un punto della circonferenza?";reason="Il raggio unisce il centro a un punto della circonferenza.";}
  else if(skill==='circle-size'){prompt="Quanto misura il diametro in cm?";reason="Il diametro è il doppio del raggio.";}
  else if(skill==='triangle-type'){prompt="Classifica per angoli un triangolo con angoli di "+q.prompt.match(/세 각이 (.*?)인/)[1]+'.';reason="Controlla se un angolo è retto o ottuso; se tutti sono acuti, il triangolo è acutangolo.";}
  else if(skill==='quad-type'){const idx=q.prompt.startsWith('네 각이 직각이고 가로')?0:q.prompt.startsWith('네 각이 직각이고 네 변')?1:q.prompt.startsWith('네 변이 같고')?2:3;prompt=["Ha quattro angoli retti e lati di 6 cm e 3 cm.","Ha quattro angoli retti e quattro lati di 4 cm.","Ha quattro lati uguali e un angolo di 60°.","Ha due coppie di lati opposti paralleli, lati consecutivi di 4 cm e 6 cm e un angolo di 60°."][idx]+" Qual è il nome più specifico del quadrilatero?";reason="Usa insieme le lunghezze dei lati e gli angoli. Scegli il nome più specifico, anche quando appartiene a una famiglia più ampia.";}
  else if(skill==='count'){prompt='Quanti pallini ci sono?';reason='Conta ogni pallino una sola volta.';}
  else if(skill==='compare'){prompt='Confronta i numeri. Quale segno è corretto?';reason='Confronta le quantità e usa >, < oppure =.';}
  else if(skill==='place'){const m=q.prompt.match(/^(\d+)에서 (일|십|백|천)의/),place=({일:'unità',십:'decine',백:'centinaia',천:'migliaia'})[m[2]];prompt='Qual è la cifra delle '+place+' nel numero '+m[1]+'?';reason='Da destra trovi unità, decine, centinaia e migliaia.';}
  else if(skill==='angle-right'){prompt='La figura mostra un angolo retto?';reason='Confronta l’angolo con quello di un foglio rettangolare.';}
  else if(skill==='symmetry-line'){prompt='Quanti assi di simmetria ha un quadrato?';reason='Due assi passano per i punti medi dei lati e due sono le diagonali.';}
  else if(skill==='fraction-model'){prompt='Quale frazione rappresenta la parte colorata?';reason='Il denominatore conta tutte le parti uguali; il numeratore conta quelle colorate.';}
  else{prompt='Confronta le due frazioni.';reason='Con denominatori uguali, confronta i numeratori.';}
  if(!q.check&&!skill.startsWith('time-clock')&&i===1)prompt+=' Scegli la risposta.';
  if(!q.check&&!skill.startsWith('time-clock')&&i===2)prompt+=' Controlla la risposta proposta.';
  const display=(skill.startsWith('time-clock')||skill==='time-duration')?s=>timeText(tr(geometryText(s))):skill.startsWith('metric-')?s=>tr(geometryText(s)):skill.startsWith('data-')?s=>tr(bankText(geometryText(s))):skill.startsWith('geometry-')?s=>tr(geometryText(s)):skill==='length-compare'?s=>tr(compareText(s)):skill.startsWith('decimal-')?s=>decimalText(tr(s)):['table','graph'].includes(skill)?s=>dataText(tr(s)):tr;
  if(skill==='metric-m²-cm²'&&i<2){let boxIndex=0;q={...q,task:q.task.replace(/□/g,()=>{boxIndex++;return i===0||boxIndex===2?'<span class="write-answer-box" style="min-width:70px" aria-label="□"></span>':'□';})};}
  return {...q,prompt:skill.startsWith('decimal-')?decimalText(prompt):prompt,reason:skill.startsWith('decimal-')?decimalText(reason):reason,visual:display(q.visual),task:display(q.task),answer:display(q.answer)};
 })}));
}};
})();
