(function(root){
const grades={
1:{name:'Woodland friends',motto:'Small steps, bright discoveries.',color:'#a04d25',light:'#fff1df',mascot:'fox',units:[['add','Addition within 20','1.OA.C.6'],['sub','Subtraction within 20','1.OA.C.6'],['place','Tens and ones','1.NBT.B.2'],['shape','Shape detectives','1.G.A.1'],['clock','Hours and half hours','1.MD.B.3'],['data','Picture data','1.MD.C.4']]},
2:{name:'River explorers',motto:'Be curious. Try a new way.',color:'#166b85',light:'#e8f7fc',mascot:'otter',units:[['add','Addition within 100','2.NBT.B.5'],['sub','Subtraction within 100','2.NBT.B.5'],['place','Hundreds, tens and ones','2.NBT.A.1'],['money','Count the coins','2.MD.C.8'],['clock','Time to five minutes','2.MD.C.7'],['length','Measure and compare','2.MD.A.4']]},
3:{name:'Space explorers',motto:'Think it through. Make a discovery.',color:'#534599',light:'#f0edfc',mascot:'rocket',units:[['mul','Multiplication facts','3.OA.C.7'],['div','Division facts','3.OA.C.7'],['fraction','Fractions of a whole','3.NF.A.1'],['area','Area adventures','3.MD.C.7'],['perimeter','Around the edges','3.MD.D.8'],['data','Scaled bar graphs','3.MD.B.3']]},
4:{name:'Nature research lab',motto:'Observe. Connect. Explain.',color:'#386b45',light:'#edf5e9',mascot:'owl',units:[['mul','Multi-digit multiplication','4.NBT.B.5'],['div','Division with remainders','4.NBT.B.6'],['equivalent','Equivalent fractions','4.NF.A.1'],['fractionAdd','Add like fractions','4.NF.B.3'],['angle','Angles and turns','4.MD.C.7'],['place','Place-value patterns','4.NBT.A.2']]},
5:{name:'Design & discovery',motto:'Plan your approach. Check your thinking.',color:'#285a78',light:'#eaf1f7',mascot:'robot',units:[['decimal','Decimal operations','5.NBT.B.7'],['fractionAdd','Add unlike fractions','5.NF.A.1'],['fractionMul','Multiply fractions','5.NF.B.4'],['unitDiv','Divide with unit fractions','5.NF.B.7'],['volume','Volume lab','5.MD.C.5'],['coordinate','Coordinate missions','5.G.A.1–2']]}
};
const box='<span class="write-box"></span>';
const svg=(body,w=190,h=90)=>'<div class="art">'+`<svg viewBox="0 0 ${w} ${h}" aria-hidden="true">${body}</svg></div>`;
const gcd=(a,b)=>b?gcd(b,a%b):a;
const frac=(n,d)=>{const g=gcd(n,d);return d/g===1?String(n/g):(n/g)+'/'+(d/g)};
const fhtml=(n,d)=>`<span class="fraction"><span>${n}</span><span>${d}</span></span>`;
const rectangle=(a,b)=>svg(`<rect x="35" y="18" width="120" height="52" fill="#e6eef3" stroke="#48697a"/><text x="95" y="13" text-anchor="middle">${a} units</text><text x="95" y="87" text-anchor="middle">${b} units high</text>`);
function generate(grade,id,seed){let state=seed>>>0;const r=n=>{state=(Math.imul(state,1664525)+1013904223)>>>0;return Math.floor(state/4294967296*n)};
const make=mode=>{
let prompt='',visual='',task='',answer='',check=null;const set=(p,v,t,a,c=null)=>{prompt=p;visual=v;task=t;answer=String(a);check=c};
if(['add','sub','mul','div','decimal'].includes(id)){
let a,b,op,result;if(id==='add'){const max=grade===1?20:100;a=r(max+1);b=r(max-a+1);op='+';result=a+b;}if(id==='sub'){const max=grade===1?20:100;a=1+r(max);b=r(a+1);op='−';result=a-b;}
if(id==='mul'){a=grade===3?1+r(10):10+r(90);b=grade===3?1+r(10):2+r(8);op='×';result=a*b;}
if(id==='div'){b=2+r(8);const q=1+r(grade===3?10:99),rem=grade===3?0:r(b);a=b*q+rem;op='÷';result=rem?q+' R '+rem:q;}
if(id==='decimal'){const ai=10+r(990),bi=1+r(400);a=ai/100;b=bi/100;op=mode===1?'−':'+';if(op==='−'&&a<b)[a,b]=[b,a];result=Number((op==='+'?a+b:a-b).toFixed(2));}
const expression=`${a} ${op} ${b}`;check={a,b,op,result};
if(mode===0)set(id==='div'&&grade===4?'Divide. Include a remainder if needed.':'Calculate.', '',`<div class="equation">${expression} = ${box}</div>`,result,check);
else if(mode===1&&id!=='div')set('Find the missing result. Explain how you checked it.','',`<div class="equation">${box} = ${expression}</div><div class="reason-line">My check: __________________</div>`,result,check);
else if(mode===1)set('Use multiplication to check the division.','',`<div class="equation">${expression} = ${box}</div><div class="reason-line">My check: __________________</div>`,result,check);
else {const story=op==='+'?`The team collected ${a} ${id==='decimal'?'meters of ribbon':'tokens'} and then ${b} more. What is the total?`:op==='−'?`The team has ${a} ${id==='decimal'?'meters of ribbon':'tokens'} and uses ${b}. How much is left?`:op==='×'?`There are ${a} packs with ${b} cards in each pack. How many cards?`:`Share ${a} tokens equally among ${b} teams. How many per team${grade===4?', and how many left over':''}?`;set(story,'',box,result,check);}
}
else if(id==='place'){const digits=grade===1?2:grade===2?3:6;const n=10**(digits-1)+r(9*10**(digits-1));const pos=r(digits);const value=Math.floor(n/10**pos)%10;const names=['ones','tens','hundreds','thousands','ten-thousands','hundred-thousands'];if(mode===0)set(`What digit is in the ${names[pos]} place?`,'',`<div class="equation">${n.toLocaleString('en-US')}</div>`+box,value);else if(mode===1)set(`What is the value of the digit in the ${names[pos]} place?`,'',`<div class="equation">${n.toLocaleString('en-US')}</div>`+box,value*10**pos);else set('Write the number in expanded form.','',`<div class="equation">${n.toLocaleString('en-US')}</div><div class="drawing-space"></div>`,String(n).split('').map((x,i)=>+x*10**(digits-i-1)).filter(Boolean).join(' + '));}
else if(id==='clock'){const hour=1+r(12),minute=grade===1?r(2)*30:r(12)*5;const angle=(hour%12+minute/60)*Math.PI/6,ma=minute*Math.PI/30;visual=svg(`<circle cx="95" cy="48" r="39" fill="white" stroke="#527284"/>`+Array.from({length:12},(_,i)=>{const t=(i+1)*Math.PI/6;return `<text x="${95+31*Math.sin(t)}" y="${52-31*Math.cos(t)}" text-anchor="middle" font-size="9">${i+1}</text>`}).join('')+`<path d="M95 48L${95+21*Math.sin(angle)} ${48-21*Math.cos(angle)}M95 48L${95+28*Math.sin(ma)} ${48-28*Math.cos(ma)}" stroke="#285a78" stroke-width="2.5"/>`,190,94);set(mode===2?'The club starts at this time. Write the time.':'Read the clock.',visual,box+' : '+box,hour+':'+String(minute).padStart(2,'0'));}
else if(id==='shape'){const names=['triangle','rectangle','square'];const name=names[r(3)],sides=name==='triangle'?3:4;visual=svg(name==='triangle'?'<path d="M95 10L150 78H40Z" fill="#f6d3ac" stroke="#765442"/>':`<rect x="50" y="12" width="${name==='square'?65:100}" height="65" fill="#f6d3ac" stroke="#765442"/>`);set(mode===0?'Name the shape.':mode===1?'How many straight sides?':'How many corners?',visual,box,mode===0?name:sides);}
else if(id==='money'){const values=[1,5,10,25],counts=values.map(()=>r(4));if(counts.every(x=>x===0))counts[0]=1;const sum=counts.reduce((s,c,i)=>s+c*values[i],0);visual='<div class="coin-list">'+counts.map((c,i)=>`${c} × <span>${values[i]}¢</span>`).join(' &nbsp; ')+'</div>';set(mode===2?'These coins are in your pocket. How many cents?':'Count the value of the coins.',visual,box+' cents',sum);}
else if(id==='length'){const a=2+r(18),b=1+r(a-1);set(mode===0?'How much longer is A than B?':mode===1?'Find the difference in length.':'Two ribbons have the lengths shown. How many centimeters longer is A?',svg(`<text x="5" y="20">A</text><rect x="25" y="5" width="140" height="17" fill="#91c9da"/><text x="90" y="18" text-anchor="middle">${a} cm</text><text x="5" y="60">B</text><rect x="25" y="44" width="${140*b/a}" height="17" fill="#ebbf86"/><text x="95" y="83" text-anchor="middle">B = ${b} cm</text>`),box+' cm',a-b);}
else if(id==='data'){const scale=grade===1?1:2,vals=[1+r(5),1+r(5),1+r(5)],labels=['A','B','C'];visual=svg(vals.map((v,i)=>`<text x="4" y="${20+i*24}">${labels[i]}</text><rect x="25" y="${6+i*24}" width="${v*26}" height="16" fill="#8ebbb8"/>`+Array.from({length:v},(_,j)=>`<path d="M${25+j*26} ${6+i*24}v16" stroke="white"/>`).join('')).join(''),180,82)+`<small>Each block = ${scale} votes.</small>`;set(mode===0?'How many votes for A?':mode===1?'How many votes altogether?':'How many more votes for the biggest group than the smallest?',visual,box,mode===0?vals[0]*scale:mode===1?vals.reduce((a,b)=>a+b)*scale:(Math.max(...vals)-Math.min(...vals))*scale);}
else if(['fraction','equivalent','fractionAdd','fractionMul','unitDiv'].includes(id)){
const d=grade===3?[2,3,4,6,8][r(5)]:2+r(7),n=1+r(d-1),e=2+r(7),m=1+r(e-1);
if(id==='fraction'){visual=svg(Array.from({length:d},(_,i)=>`<rect x="${10+i*160/d}" y="20" width="${160/d}" height="42" fill="${i<n?'#ada2dc':'white'}" stroke="#645787"/>`).join(''));set(mode===0?'What fraction is shaded?':mode===1?'What fraction is not shaded?':'How many equal parts make one whole?',visual,box,mode===2?d:frac(mode===0?n:d-n,d));}
if(id==='equivalent'){const k=2+r(4);set('Complete the equivalent fraction.','',`<div class="equation">${fhtml(n,d)} = ${fhtml('□',d*k)}</div>`,n*k);}
if(id==='fractionAdd'){const den=grade===4?d:(e===d?(e===8?2:e+1):e);const other=1+r(den-1);if(mode===1)set('Find the missing numerator.','',`<div class="equation">${fhtml('□',d)} + ${fhtml(other,den)} = ${fhtml(n*den+other*d,d*den)}</div>`,n);else set(mode===2?`One ribbon is ${n}/${d} meter long. Another is ${other}/${den} meter long. What is their total length?`:'Add. Simplify if possible.','',`<div class="equation">${fhtml(n,d)} + ${fhtml(other,den)} = ${box}</div>`,frac(n*den+other*d,d*den));}
if(id==='fractionMul')set(mode===2?'Find the product. Simplify if possible.':'Multiply the fractions.','',`<div class="equation">${fhtml(n,d)} × ${fhtml(m,e)} = ${box}</div>`,frac(n*m,d*e));
if(id==='unitDiv'){const whole=1+r(8);const reverse=mode===1;set(mode===2?`How many pieces of length 1/${d} meter fit into ${whole} meters?`:'Divide.','',`<div class="equation">${reverse?fhtml(1,d)+' ÷ '+whole:whole+' ÷ '+fhtml(1,d)} = ${box}</div>`,reverse?frac(1,d*whole):whole*d);}
}
else if(id==='area'||id==='perimeter'){const a=2+r(8),b=2+r(8);set(id==='area'?'Find the rectangle’s area.':'Find the distance around the rectangle.',rectangle(a,b),box+(id==='area'?' square units':' units'),id==='area'?a*b:2*(a+b));}
else if(id==='angle'){const a=10+r(8)*10,b=10+r(8)*10;set(mode===1?`A ${a+b}° angle is split into ${a}° and an unknown angle. Find the unknown.`:`Two adjacent angles measure ${a}° and ${b}°. Find their combined angle.`,'',box+' degrees',mode===1?b:a+b);}
else if(id==='volume'){const a=2+r(8),b=2+r(8),c=2+r(8);visual=svg(`<path d="M35 32L70 10H145V60L110 82H35Z M35 32H110L145 10 M110 32V82" fill="#deeaf0" stroke="#48697a"/><text x="45" y="57">${a} × ${b} × ${c}</text>`);set(mode===2?'A box has the dimensions shown in centimeters. Find its volume.':'Find the volume in cubic centimeters.',visual,box+' cm³',a*b*c);}
else if(id==='coordinate'){const x=1+r(5),y=1+r(5);visual=svg(Array.from({length:6},(_,i)=>`<path d="M35 ${75-i*12}H95M${35+i*12} 15V75" stroke="#ccd8de"/><text x="${35+i*12}" y="87" text-anchor="middle" font-size="8">${i}</text><text x="25" y="${78-i*12}" font-size="8">${i}</text>`).join('')+`<circle cx="${35+x*12}" cy="${75-y*12}" r="3" fill="#285a78"/><text x="105" y="79">x</text><text x="22" y="9">y</text>`);set(mode===0?'Write the ordered pair of the point.':mode===1?'What is the x-coordinate?':'What is the y-coordinate?',visual,box,mode===0?`(${x}, ${y})`:mode===1?x:y);}
else throw Error('Unknown unit '+id);
return {prompt,visual,task,answer,check};
};return [0,1,2].map(mode=>({questions:Array.from({length:mode===1?3:2},()=>make(mode))}));
}
root.GradeMath={grades,generate};if(typeof module!=='undefined')module.exports=root.GradeMath;
})(globalThis);

if(typeof module!=="undefined")require("./grade-extension.js");
