/* Reuse existing generators; levels are skills, not national grade claims. */
(function(root){
const original=DrillCatalog.units.flatMap(u=>u.drills.map(p=>({...p,originUnit:u.id}))), W=Worksheets;
const stages=[
['add-10','Add and subtract within 10'],['add-20','Add and subtract within 20'],['add-2','Two-digit addition and subtraction'],['add-3','Three-digit addition and subtraction'],
['tables','Multiplication facts'],['mul-1','Multiply by a one-digit number'],['mul-2','Multiply by a two-digit number'],['div-facts','Division facts'],['div-1','Divide by a one-digit number'],['div-2','Divide by a two-digit number'],
['fraction-forms','Improper fractions and mixed numbers'],['factors','Factors and multiples'],['equivalent','Simplify and find common denominators'],['fraction-same','Add and subtract: like denominators'],['fraction-unlike','Add and subtract: unlike denominators'],['fraction-mul','Multiply fractions'],['fraction-div-whole','Divide fractions by whole numbers'],['fraction-div','Divide by a fraction'],['decimal-add','Add and subtract decimals'],['decimal-mul','Multiply decimals'],['decimal-div-whole','Divide decimals by whole numbers'],['decimal-div','Divide by a decimal'],['mixed','Mixed operations']
].map(([id,name],i)=>({id,name,number:i+1,grade:Math.min(6,Math.floor(i/4)+1),semester:i%2+1,drills:[]}));
const byId=new Map(stages.map(s=>[s.id,s]));
function classify(p){const c=W.types.find(t=>t.id===p.source)?.config||{};if(p.mode==='skill'){if(['improper','mixed','one-fraction'].includes(p.skill))return 'fraction-forms';if(['factor','multiple','common-factor','common-multiple','gcd','lcm'].includes(p.skill))return 'factors';if(['reduce','common','compare-fraction'].includes(p.skill))return 'equivalent';if(p.skill.startsWith('mixed-'))return 'mixed';if(p.skill==='bond9'||p.skill==='bond')return 'add-10';if(p.skill==='repeat'||p.skill==='groups')return 'tables';if(p.skill==='decimal-scale')return 'decimal-mul';return null;}
if(p.mode==='story')return null;
if(p.tables||p.source==='multiply-one')return 'tables';if(p.source==='divide')return 'div-facts';
if(p.custom==='early')return p.max<=10?'add-10':p.max<=20?'add-20':'add-2';
if(c.kind==='natural'){if(['add','sub'].includes(c.code)){if(c.da===1&&c.db===1)return c.code==='add'?'add-20':'add-10';return Math.max(c.da,c.db)<=2?'add-2':'add-3';}return c.code==='mul'?(c.db===1?'mul-1':'mul-2'):(c.db===1?'div-1':'div-2');}
if(c.kind?.startsWith('fraction')){if(c.code==='mul')return 'fraction-mul';if(c.code==='div')return c.fb==='whole'?'fraction-div-whole':'fraction-div';return p.same||c.same?'fraction-same':'fraction-unlike';}
if(c.kind?.startsWith('decimal')){if(['add','sub'].includes(c.code))return 'decimal-add';if(c.code==='mul')return 'decimal-mul';return (c.dp??c.db)===0?'decimal-div-whole':'decimal-div';}return null;}
const names={whole:'Whole number',proper:'Proper fraction',improper:'Improper fraction',mixed:'Mixed number'},ops={add:'plus',sub:'minus',mul:'times',div:'divided by'};
const skillNames={bond:'Make 10',bond9:'Number bonds within 9',repeat:'Repeated addition',groups:'Equal groups to multiplication',factor:'Find factors',multiple:'Find multiples','common-factor':'Common factors','common-multiple':'Common multiples',gcd:'Greatest common factor',lcm:'Least common multiple',reduce:'Simplest form',common:'Find a common denominator','compare-fraction':'Compare using common denominators',improper:'Improper fraction to mixed number',mixed:'Mixed number to improper fraction','one-fraction':'Write 1 as a fraction','decimal-scale':'Multiply by 10, 100, or 1,000','mixed-add':'Addition and subtraction','mixed-mul':'Multiplication and division','mixed-four':'Order of operations','mixed-bracket':'Parentheses and operations'};
function title(p){const c=W.types.find(t=>t.id===p.source)?.config||{};if(p.mode==='story')return 'Choose the operation: word problems';if(p.skill)return skillNames[p.skill];let t='';if(p.tables)t=p.tables.length===8?'All multiplication facts':p.tables.join(', ')+' times tables';else if(p.custom==='early')t=(p.code==='add'?'Addition':'Subtraction')+(p.max===99?' · two digits and one digit':' within '+p.max);else if(c.kind==='natural')t=c.da+'-digit '+ops[c.code]+' '+c.db+'-digit';else if(c.kind==='fraction-pair')t=names[c.fa]+' '+ops[c.code]+' '+names[c.fb]+(p.same?' · like denominators':'');else if(c.kind==='fraction')t='Fractions '+ops[c.code]+(c.same?' · like denominators':' · unlike denominators');else if(c.kind?.startsWith('decimal')){const [a,b]=p.decimalPlaces||[c.dp??c.da,c.dp??c.db];t=(a?a+' decimal place'+(a===1?'':'s'):'Whole number')+' '+ops[c.code]+' '+(b?b+' decimal place'+(b===1?'':'s'):'whole number');}else t=p.source==='divide'?'Division facts':p.source==='multiply-one'?'Multiplication facts':p.source==='subtract-small'?'Subtraction within 10':'Addition within 20';if(p.condition)t+=' · '+(p.condition==='carry'?'with regrouping':'no regrouping');if(p.remainder!==undefined)t+=' · '+(p.remainder?'with remainders':'no remainders');if(p.mode==='blank')return t+' · missing number';if(p.mode==='digit')return t+' · missing digits';return t+(p.layout==='vertical'?' · vertical':' · horizontal');}
const registry=new Map(),seen=new Set();function add(stage,p,group){const clean={source:p.source,mode:p.mode,layout:p.layout,custom:p.custom,max:p.max,carry:p.carry,code:p.code,same:p.same,condition:p.condition,remainder:p.remainder,tables:p.tables,decimalPlaces:p.decimalPlaces,skill:p.skill,sourceExtra:p.sourceExtra?{same:p.sourceExtra.same,custom:p.sourceExtra.custom,max:p.sourceExtra.max,carry:p.sourceExtra.carry,code:p.sourceExtra.code,condition:p.sourceExtra.condition,tables:p.sourceExtra.tables}:undefined};const key=stage.id+'|'+group+'|'+JSON.stringify(clean);if(seen.has(key))return;seen.add(key);const id=p.id+'--'+stage.id+'-'+stage.drills.length,copy={...p,id,group,title:title(p)};stage.drills.push(copy);registry.set(id,copy);W.types.push({...W.types.find(t=>t.id===p.source),id,title:copy.title});}
for(const p of original){if(p.mode==='story')continue;const id=classify(p);if(!id)continue;add(byId.get(id),p,['blank','digit'].includes(p.mode)?'빈칸 응용':'기본 연산');}
const reviews={'add-20':['add-10'],'add-2':['add-20'],'add-3':['add-2'],'mul-1':['tables'],'mul-2':['mul-1'],'div-facts':['tables'],'div-1':['div-facts'],'div-2':['div-1'],'fraction-same':['fraction-forms'],'fraction-unlike':['fraction-same','equivalent'],'equivalent':['factors'],'fraction-mul':['equivalent'],'fraction-div-whole':['fraction-mul'],'fraction-div':['fraction-div-whole'],'decimal-add':['add-3'],'decimal-mul':['mul-2'],'decimal-div-whole':['div-2'],'decimal-div':['decimal-div-whole'],'mixed':['mul-2','div-2']};
const basics=new Map(stages.map(s=>[s.id,s.drills.filter(p=>p.group==='기본 연산')]));for(const s of stages)for(const previous of reviews[s.id]||[])for(const p of basics.get(previous))add(s,p,'기초 보충');
for(const s of stages){const pool=basics.get(s.id).filter(p=>p.mode==='basic'&&p.layout==='horizontal');if(!pool.length)continue;const p=pool[0];add(s,{...p,mode:'story',layout:'horizontal',pool:pool.map(p=>({source:p.source,extra:p}))},'문장 연습');}
for(const s of stages)s.drills.sort((a,b)=>['기본 연산','기초 보충','빈칸 응용','문장 연습'].indexOf(a.group)-['기본 연산','기초 보충','빈칸 응용','문장 연습'].indexOf(b.group));
DrillCatalog.units=stages;DrillCatalog.profiles=registry;root.PracticeLevels={stages,title};
})(globalThis);
