/* Free Quill editor enhancements; existing Firestore collection format is retained. */
(function(){
const $=id=>document.getElementById(id);let selectedImage=null,draftTimer,loadingDraft=false,lastFocus=null;
const originalInit=initBoard,originalOpen=openWrite,originalEdit=editPost,originalClose=closeWrite;
const draftKey=()=>`gd-board-draft:${BOARD.collection}:${currentUser?.uid||'guest'}:${editingPostId||'new'}`;
function notice(text){$('draftStatus').textContent=text;}
function saveDraft(){if(!$('wTitle').value.trim()&&!quillEditor.getText().trim()&&!quillEditor.root.querySelector('img'))return;if(loadingDraft||!currentUser||$('writeModal').classList.contains('hidden'))return;try{localStorage.setItem(draftKey(),JSON.stringify({title:$('wTitle').value,html:quillEditor.root.innerHTML,category:$('wCategory')?.value,time:Date.now()}));notice('이 브라우저에 임시저장됨 · '+new Date().toLocaleTimeString('ko-KR'));}catch{notice('임시저장 공간이 부족합니다. 글을 등록하거나 복사해 주세요.');}}
window.clearBoardDraft=()=>{clearTimeout(draftTimer);try{localStorage.removeItem(draftKey());}catch{}};
function scheduleDraft(){if(loadingDraft)return;clearTimeout(draftTimer);draftTimer=setTimeout(saveDraft,800);$('wordCount').textContent=quillEditor.getText().trim().length.toLocaleString()+'자';}
function restoreDraft(){try{const raw=localStorage.getItem(draftKey());$('restoreDraft').hidden=!raw;if(!raw)return;const d=JSON.parse(raw);loadingDraft=true;$('wTitle').value=d.title||'';quillEditor.clipboard.dangerouslyPasteHTML(sanitizeHtml(d.html||''));if($('wCategory'))$('wCategory').value=d.category||BOARD.categories?.[0];loadingDraft=false;notice('임시저장한 글을 불러왔습니다.');}catch{loadingDraft=false;notice('저장한 글을 불러오지 못했습니다.');}}
const originalAuth=renderAuth;renderAuth=function(){originalAuth();if($('writeModal')&&!$('writeModal').classList.contains('hidden')){$('writeLoggedIn').classList.toggle('hidden',!canWrite());$('writeLoggedOut').classList.toggle('hidden',canWrite());}};
initBoard=function(config){originalInit(config);setupUI();};
initEditor=function(){
$('wToolbar').innerHTML=`<span class="ql-formats"><select class="ql-header" aria-label="문단 종류"><option selected>본문</option><option value="2">큰 제목</option><option value="3">작은 제목</option></select><select class="ql-size" aria-label="글자 크기"><option value="small">작게</option><option selected>보통</option><option value="large">크게</option><option value="huge">아주 크게</option></select></span><span class="ql-formats"><button class="ql-bold" aria-label="굵게"></button><button class="ql-italic" aria-label="기울임"></button><button class="ql-underline" aria-label="밑줄"></button><button class="ql-strike" aria-label="취소선"></button></span><span class="ql-formats"><select class="ql-color" aria-label="글자색"></select><select class="ql-background" aria-label="강조색"></select></span><span class="ql-formats"><button class="ql-list" value="ordered" aria-label="번호 목록"></button><button class="ql-list" value="bullet" aria-label="글머리 목록"></button><select class="ql-align" aria-label="정렬"></select><button class="ql-blockquote" aria-label="인용"></button><button class="ql-clean" aria-label="서식 지우기"></button></span>`;
quillEditor=new Quill('#wEditor',{theme:'snow',modules:{toolbar:'#wToolbar',table:true,history:{userOnly:true}},placeholder:'질문이나 이야기를 자유롭게 남겨주세요. 사진은 본문 중간에 넣을 수 있어요.'});
quillEditor.on('text-change',scheduleDraft);
quillEditor.root.addEventListener('click',e=>{selectedImage=e.target.tagName==='IMG'?e.target:null;$('imageSize').disabled=!selectedImage;});
quillEditor.root.addEventListener('paste',e=>{const files=[...(e.clipboardData?.files||[])];if(files.length){e.preventDefault();e.stopImmediatePropagation();addImages(files);}},true);
quillEditor.root.addEventListener('drop',e=>{if(e.dataTransfer.files.length){e.preventDefault();e.stopImmediatePropagation();addImages([...e.dataTransfer.files]);}},true);
};
async function addImages(files){
if(window.boardUploading)return; if(files.length>10){alert('한 번에 사진 10장까지 올릴 수 있습니다.');return;}
if(files.some(f=>!['image/jpeg','image/png','image/webp','image/gif'].includes(f.type)||f.size>5*1024*1024)){alert('JPG·PNG·WEBP·GIF 사진만 장당 5MB까지 올릴 수 있습니다.');return;}
window.boardUploading=true;const range=quillEditor.getSelection(true);let at=range?.index??quillEditor.getLength()-1;
try{for(let i=0;i<files.length;i++){notice(`사진 올리는 중 ${i+1}/${files.length}`);const url=await uploadImage(files[i]);if(!/^https:\/\//.test(url))throw Error('Invalid image URL');quillEditor.insertEmbed(at,'image',url,'user');at++;quillEditor.insertText(at,'\n','user');at++;}quillEditor.setSelection(at);saveDraft();}catch{notice('사진 업로드에 실패했습니다. 이미 올라간 사진은 유지됩니다.');}finally{window.boardUploading=false;}
}
function setupUI(){
const category=$('wCategory');if(category&&BOARD.categories)category.innerHTML=BOARD.categories.map(c=>`<option>${escapeHtml(c)}</option>`).join('');
$('wTitle').maxLength=199;$('wTitle').setAttribute('aria-label','글 제목');$('wTitle').placeholder='제목을 입력해 주세요';$('wTitle').addEventListener('input',scheduleDraft);category?.addEventListener('change',scheduleDraft);
$('writeModal').setAttribute('role','dialog');$('writeModal').setAttribute('aria-modal','true');$('writeModal').setAttribute('aria-label','게시판 글쓰기');
$('writeLoggedIn').insertAdjacentHTML('afterbegin','<div class="compose-label">GOOGOODAN COMMUNITY <button type="button" id="composeClose" aria-label="작성창 닫기">×</button></div>');
$('wToolbar').insertAdjacentHTML('beforebegin',`<div class="compose-tools"><button type="button" id="addPhotos"><b>▧</b> 사진</button><button type="button" id="addTable"><b>▦</b> 표</button><button type="button" id="addLink"><b>↗</b> 링크</button><button type="button" id="undoEdit"><b>↶</b> 실행 취소</button><button type="button" id="redoEdit"><b>↷</b> 다시 실행</button><label>사진 크기 <select id="imageSize" disabled><option value="100%">전체</option><option value="75%">75%</option><option value="50%">50%</option><option value="25%">25%</option></select></label></div><div class="table-tools"><span>표 안을 선택한 뒤</span><button type="button" data-table="insertRowBelow">행 추가</button><button type="button" data-table="insertColumnRight">열 추가</button><button type="button" data-table="deleteRow">행 삭제</button><button type="button" data-table="deleteColumn">열 삭제</button><button type="button" data-table="deleteTable">표 삭제</button></div>`);
$('wEditor').insertAdjacentHTML('afterend','<div class="compose-status"><span id="draftStatus" role="status">임시저장은 이 브라우저에만 보관됩니다.</span><span id="wordCount">0자</span></div><div id="postPreview" class="hidden post-rich"></div>');
document.querySelector('#writeLoggedIn .modal-actions').insertAdjacentHTML('afterbegin','<button type="button" id="restoreDraft">임시글 불러오기</button><button type="button" id="saveDraft">임시저장</button><button type="button" id="previewPost">미리보기</button>');
$('composeClose').onclick=()=>closeWrite();$('saveDraft').onclick=saveDraft;$('restoreDraft').onclick=restoreDraft;
$('previewPost').onclick=()=>{const box=$('postPreview');box.classList.toggle('hidden');if(!box.classList.contains('hidden')){box.innerHTML='<h2>'+escapeHtml($('wTitle').value)+'</h2>'+renderContent({contentHtml:quillEditor.root.innerHTML});box.scrollIntoView({behavior:'smooth',block:'nearest'});}$('previewPost').textContent=box.classList.contains('hidden')?'미리보기':'미리보기 닫기';};
$('addPhotos').onclick=()=>{const input=document.createElement('input');input.type='file';input.multiple=true;input.accept='image/jpeg,image/png,image/webp,image/gif';input.onchange=()=>addImages([...input.files]);input.click();};
$('addTable').onclick=()=>{quillEditor.focus();quillEditor.getModule('table').insertTable(3,3);};
document.querySelectorAll('[data-table]').forEach(b=>b.onclick=()=>{quillEditor.focus();quillEditor.getModule('table')[b.dataset.table]();});
$('addLink').onclick=()=>{const value=prompt('연결할 주소를 입력하세요. (https://...)');if(!value)return;let url;try{url=new URL(value);if(!['https:','http:'].includes(url.protocol))throw Error();}catch{alert('http 또는 https 주소를 입력해 주세요.');return;}const r=quillEditor.getSelection(true);if(r.length)quillEditor.format('link',url.href);else quillEditor.insertText(r.index,url.href,{link:url.href},'user');};
$('undoEdit').onclick=()=>quillEditor.history.undo();$('redoEdit').onclick=()=>quillEditor.history.redo();
$('imageSize').onchange=e=>{if(!selectedImage)return;const blot=Quill.find(selectedImage);if(blot){quillEditor.formatText(quillEditor.getIndex(blot),1,'width',e.target.value,'user');saveDraft();}};
const tools=document.querySelector('.board-toolbar');tools.insertAdjacentHTML('afterend','<div class="board-find"><label>분류<select id="categoryFilter"><option value="">전체</option></select></label><label class="board-search">제목 검색<input id="boardSearch" type="search" placeholder="어떤 이야기를 찾으세요?"></label><p>불러온 글에서 검색합니다. 더 보기를 누르면 검색 범위가 넓어집니다.</p></div>');
$('categoryFilter').insertAdjacentHTML('beforeend',(BOARD.categories||[]).map(c=>`<option>${escapeHtml(c)}</option>`).join(''));$('categoryFilter').onchange=renderList;$('boardSearch').oninput=renderList;
window.addEventListener('beforeunload',()=>saveDraft());
$('writeModal').addEventListener('keydown',e=>{if(e.key==='Escape'){e.preventDefault();closeWrite();}if(e.key==='Tab'){const els=[...$('writeModal').querySelectorAll('button,input,select,[tabindex="0"],[contenteditable="true"]')].filter(x=>!x.disabled&&x.getClientRects().length);const first=els[0],last=els.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus();}}});
renderList();
}
function opened(){lastFocus=document.activeElement;document.body.classList.add('composing');selectedImage=null;$('imageSize').disabled=true;$('postPreview').classList.add('hidden');$('previewPost').textContent='미리보기';notice('이 브라우저에 자동으로 임시저장됩니다.');try{$('restoreDraft').hidden=!localStorage.getItem(draftKey());}catch{}setTimeout(()=>(currentUser?$('wTitle'):document.querySelector('#writeLoggedOut .btn-login')).focus(),0);}
openWrite=function(){loadingDraft=true;originalOpen();loadingDraft=false;if(!$('writeModal').classList.contains('hidden'))opened();};
editPost=function(id){loadingDraft=true;originalEdit(id);const p=posts.find(x=>x.id===id);if(editingPostId===id&&p){quillEditor.clipboard.dangerouslyPasteHTML(sanitizeHtml(p.contentHtml||escapeHtml(p.content||'').replace(/\n/g,'<br>')+(p.imageUrl?'<p><img src="'+escapeHtml(p.imageUrl)+'"></p>':'')));opened();}loadingDraft=false;};
closeWrite=function(saved=false){if(window.boardUploading){alert('사진 업로드가 끝난 뒤 닫아 주세요.');return;}clearTimeout(draftTimer);if(!saved)saveDraft();loadingDraft=true;originalClose();loadingDraft=false;document.body.classList.remove('composing');lastFocus?.focus();};
renderList=function(){
const list=$('postList'),term=($('boardSearch')?.value||'').trim().toLocaleLowerCase(),cat=$('categoryFilter')?.value||'';const visible=posts.filter(p=>(!cat||p.category===cat)&&(!term||String(p.title||'').toLocaleLowerCase().includes(term)));
$('postCount').textContent=`불러온 글 ${posts.length}개`+(term||cat?` · 검색 ${visible.length}개`:'');$('moreBtn').classList.toggle('hidden',noMore);
list.innerHTML='';if(!visible.length){list.innerHTML='<div class="board-empty"><span>✎</span><h3>'+(posts.length?'찾는 글이 없습니다':'첫 이야기를 기다리고 있어요')+'</h3><p>'+(posts.length?'다른 검색어를 입력하거나 더 보기를 눌러주세요.':'궁금한 점, 필요한 자료, 사용 후기를 남겨주세요.')+'</p></div>';return;}
for(const p of visible){const item=document.createElement('article');item.className='post-item';const catBadge=p.category?'<span class="badge-cat">'+escapeHtml(p.category)+'</span>':'';item.innerHTML='<button type="button" class="post-row">'+catBadge+'<span class="post-title">'+escapeHtml(p.title)+'</span><span class="post-meta"><span>'+escapeHtml(p.authorName||'사용자')+'</span><span>'+fmtDate(p.createdAt)+'</span><span>댓글 '+Number(p.commentCount||0)+'</span></span><span class="post-arrow">⌄</span></button><div class="post-detail hidden" id="detail-'+escapeHtml(p.id)+'"></div>';item.querySelector('.post-row').onclick=()=>toggleDetail(p.id);list.appendChild(item);}
};
})();
