'use strict';
const $=id=>document.getElementById(id),cfg=window.GD_COMMUNITY||{},cats=['질문','자료 요청','사용 후기','봉사 소식','자유'];
let editor,selectedImage,editing=null,activePost=null,next=null,filter='',timer,busy=false,loading=false,widget=null;
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let editingCredential='';
async function credential(password){if(/^[A-Za-z0-9_-]{24,100}$/.test(password))return password;return 'pw:'+Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(password)))).map(x=>x.toString(16).padStart(2,'0')).join('');}
function remembered(id){try{return localStorage.getItem('gd-owner:'+id)||'';}catch{return '';}}
function remember(id,key){try{localStorage.setItem('gd-owner:'+id,key);}catch{}}
async function askCredential(id){const saved=remembered(id);if(saved)return saved;const p=prompt('작성할 때 정한 비밀번호를 입력하세요. 기존 글은 수정 코드를 입력하세요.');return p?credential(p):'';}

const configured=()=>/^https:\/\//.test(cfg.apiBase||'')&&!!cfg.turnstileSiteKey;
function status(msg){$('connectionStatus').textContent=msg;}
async function api(path,method='GET',body){if(!configured())throw Error('무료 서버 계정 연결을 준비 중입니다. 아직 글은 전송되지 않습니다.');const r=await fetch(cfg.apiBase.replace(/\/$/,'')+path,{method,headers:body instanceof FormData?{}:{'Content-Type':'application/json'},body:body?(body instanceof FormData?body:JSON.stringify(body)):undefined,signal:AbortSignal.timeout(30000)});const data=await r.json();if(!r.ok)throw Error(data.error||'처리하지 못했습니다.');return data;}
function human(){return new Promise((resolve,reject)=>{if(!configured()||!window.turnstile){reject(Error('스팸 방지 기능이 아직 연결되지 않았습니다.'));return;}$('challenge').showModal();let done=false;const finish=(error,value)=>{if(done)return;done=true;if(widget!==null){turnstile.remove(widget);widget=null;}$('challenge').close();error?reject(Error(error)):resolve(value);};$('cancelChallenge').onclick=()=>finish('전송을 취소했습니다.');$('challenge').oncancel=e=>{e.preventDefault();finish('전송을 취소했습니다.');};widget=turnstile.render('#turnstileBox',{sitekey:cfg.turnstileSiteKey,action:'board-write',callback:token=>finish(null,token),'error-callback':()=>finish('스팸 방지 연결을 다시 시도해 주세요.'),'expired-callback':()=>finish('검사 시간이 지났습니다. 다시 시도해 주세요.')});});}
async function write(path,method,body){return api(path,method,{...body,token:await human(),website:$('website').value});}
function renderRich(delta){const mount=document.createElement('div');const q=new Quill(mount,{readOnly:true,modules:{toolbar:false}});q.setContents(delta);const html=DOMPurify.sanitize(q.root.innerHTML,{ALLOWED_TAGS:['p','br','strong','em','u','s','span','ol','ul','li','a','img','h1','h2','h3','blockquote','table','tbody','tr','td','th'],ALLOWED_ATTR:['style','class','href','src','width','height','data-row','data-list']});const div=document.createElement('div');div.innerHTML=html;div.querySelectorAll('a').forEach(a=>{a.target='_blank';a.rel='noopener noreferrer nofollow ugc';});return div.innerHTML;}
function draftKey(){return 'gd-guest-draft:'+(editing||'new');}
function categoryLabel(c){return c==='봉사 소식'?'자원봉사 소식':c;}
function saveDraft(){if(loading)return;if(!$('title').value&&!editor.getText().trim()&&!editor.root.querySelector('img'))return;try{localStorage.setItem(draftKey(),JSON.stringify({title:$('title').value,nickname:$('nickname').value,category:$('category').value,content:editor.getContents(),time:Date.now()}));$('draftStatus').textContent='이 브라우저에 내용을 임시저장했습니다. 비밀번호는 저장하지 않습니다.';}catch{$('draftStatus').textContent='저장 공간이 부족합니다. 내용을 복사해 주세요.';}}
function closeComposer(){if(busy){alert('전송이 끝난 뒤 닫아 주세요.');return;}clearTimeout(timer);saveDraft();$('composer').close();}
function openComposer(post=null,key=''){editing=post?.id||null;loading=true;editor.setContents(post?.content||[]);$('title').value=post?.title||'';$('nickname').value=post?.nickname||'';$('category').value=post?.category||cats[0];editingCredential=key;$('editCode').value='';$('editCode').required=!post;$('editCode').closest('.edit-key').hidden=!!post;$('nickname').disabled=!!post;$('composeTitle').textContent=post?'이야기 수정':'새 이야기 쓰기';$('submitPost').textContent=post?'수정 완료':'등록';$('preview').hidden=true;$('draftStatus').textContent='임시저장은 이 브라우저에만 보관됩니다.';loading=false;$('composer').showModal();$('title').focus();}
async function loadPosts(more=false){try{const data=await api('/posts?category='+encodeURIComponent(filter)+'&q='+encodeURIComponent($('search').value)+(more&&next?'&before='+next:''));if(!more)$('posts').innerHTML='';for(const p of data.posts){const b=document.createElement('button');b.className='post-card';b.innerHTML='<span class="badge">'+esc(categoryLabel(p.category))+'</span><strong>'+esc(p.title)+'</strong><small>'+esc(p.nickname)+' · '+new Date(p.created_at).toLocaleDateString('ko-KR')+' · 댓글 '+p.comment_count+'</small><span>↗</span>';b.onclick=()=>openPost(p.id);$('posts').append(b);}next=data.next;$('more').hidden=!next;if(!$('posts').children.length)$('posts').innerHTML='<div class="empty"><b>✎</b><h2>이야기를 기다리고 있어요</h2><p>궁금한 점과 필요한 자료를 남겨주세요.</p></div>';status('');}catch(e){status(e.message);}}
async function openPost(id){try{const data=await api('/posts/'+id);activePost=data.post;const p=data.post;$('article').innerHTML='<span class="badge">'+esc(categoryLabel(p.category))+'</span><h2>'+esc(p.title)+'</h2><p class="small">'+esc(p.nickname)+' · '+new Date(p.created_at).toLocaleString('ko-KR')+'</p><div class="rich">'+renderRich(p.content)+'</div>';$('postActions').innerHTML='<button id="editPost">수정</button><button id="deletePost">삭제</button>';$('editPost').onclick=async()=>{const key=await askCredential(id);if(key)openComposer(activePost,key);};$('deletePost').onclick=async()=>{const key=await askCredential(id);if(!key||!confirm('이 글과 댓글을 삭제할까요?'))return;try{await write('/posts/'+id,'DELETE',{editCode:key});$('reader').close();loadPosts();}catch(e){alert(e.message);}};
$('comments').innerHTML='';for(const c of data.comments){const div=document.createElement('div');div.className='comment';div.innerHTML='<strong>'+esc(c.nickname)+'</strong><small>'+new Date(c.created_at).toLocaleDateString('ko-KR')+'</small><p>'+esc(c.content)+'</p><button>삭제</button>';div.querySelector('button').onclick=async()=>{const key=await askCredential(c.id);if(!key)return;try{await write('/comments/'+c.id,'DELETE',{editCode:key});openPost(id);}catch(e){alert(e.message);}};$('comments').append(div);}if(!$('reader').open)$('reader').showModal();}catch(e){status(e.message);}}
async function uploadPhotos(files){if(busy)return;if(files.length>10||files.some(f=>f.size>5242880||!['image/jpeg','image/png','image/gif','image/webp'].includes(f.type))){alert('사진은 한 번에 10장, 장당 5MB 이내의 JPG·PNG·GIF·WEBP만 가능합니다.');return;}busy=true;try{let at=editor.getSelection(true)?.index??editor.getLength()-1;for(let i=0;i<files.length;i++){$('draftStatus').textContent=`사진 ${i+1}/${files.length} 올리는 중`;const form=new FormData();form.append('file',files[i]);form.append('token',await human());const data=await api('/upload','POST',form);editor.insertEmbed(at++,'image',data.url,'user');editor.insertText(at++,'\n','user');}saveDraft();}catch(e){$('draftStatus').textContent=e.message;}finally{busy=false;}}
function init(){
$('category').innerHTML=cats.map(c=>'<option value="'+c+'">'+categoryLabel(c)+'</option>').join('');for(const c of ['전체',...cats]){const b=document.createElement('button');b.textContent=categoryLabel(c);b.setAttribute('aria-pressed',c==='전체');b.onclick=()=>{filter=c==='전체'?'':c;document.querySelectorAll('#categories button').forEach(x=>x.setAttribute('aria-pressed',x===b));loadPosts();};$('categories').append(b);}
editor=new Quill('#editor',{theme:'snow',modules:{toolbar:'#toolbar',table:true,history:{userOnly:true}},placeholder:'사진과 이야기를 자유롭게 담아주세요.'});
editor.on('text-change',()=>{clearTimeout(timer);if(!loading)timer=setTimeout(saveDraft,1000);});for(const id of ['title','nickname','category'])$(id).addEventListener('input',()=>{clearTimeout(timer);timer=setTimeout(saveDraft,1000);});
$('newPost').onclick=()=>openComposer();document.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>b.dataset.close==='composer'?closeComposer():$(b.dataset.close).close());$('composer').oncancel=e=>{e.preventDefault();closeComposer();};
$('draft').onclick=saveDraft;$('restore').onclick=()=>{try{const raw=localStorage.getItem(draftKey());if(!raw){$('draftStatus').textContent='저장된 임시글이 없습니다.';return;}const d=JSON.parse(raw);loading=true;editor.setContents(d.content);for(const k of ['title','nickname','category'])$(k).value=d[k];loading=false;$('draftStatus').textContent='임시글을 불러왔습니다.';}catch{loading=false;$('draftStatus').textContent='임시글을 불러오지 못했습니다.';}};
$('previewButton').onclick=()=>{$('preview').hidden=!$('preview').hidden;if(!$('preview').hidden)$('preview').innerHTML='<h2>'+esc($('title').value)+'</h2>'+renderRich(editor.getContents());};
$('photo').onclick=()=>{const input=document.createElement('input');input.type='file';input.accept='image/jpeg,image/png,image/webp,image/gif';input.multiple=true;input.onchange=()=>uploadPhotos([...input.files]);input.click();};
editor.root.addEventListener('paste',e=>{if(e.clipboardData.files.length){e.preventDefault();e.stopImmediatePropagation();uploadPhotos([...e.clipboardData.files]);}},true);editor.root.addEventListener('drop',e=>{if(e.dataTransfer.files.length){e.preventDefault();e.stopImmediatePropagation();uploadPhotos([...e.dataTransfer.files]);}},true);
$('table').onclick=()=>{editor.focus();editor.getModule('table').insertTable(3,3);};document.querySelectorAll('[data-table]').forEach(b=>b.onclick=()=>{editor.focus();editor.getModule('table')[b.dataset.table]();});$('undo').onclick=()=>editor.history.undo();$('redo').onclick=()=>editor.history.redo();$('link').onclick=()=>{const value=prompt('https:// 주소를 입력해 주세요.');if(!value)return;try{const u=new URL(value);if(!['http:','https:'].includes(u.protocol))throw Error();const r=editor.getSelection(true);r.length?editor.format('link',u.href):editor.insertText(r.index,u.href,{link:u.href},'user');}catch{alert('올바른 웹 주소를 입력해 주세요.');}};
editor.root.addEventListener('click',e=>{selectedImage=e.target.tagName==='IMG'?e.target:null;$('imageWidth').disabled=!selectedImage;});$('imageWidth').onchange=()=>{const blot=selectedImage&&Quill.find(selectedImage);if(blot)editor.formatText(editor.getIndex(blot),1,'width',$('imageWidth').value,'user');};
$('postForm').onsubmit=async e=>{e.preventDefault();if(busy)return;busy=true;$('submitPost').disabled=true;try{const authKey=editing?editingCredential:await credential($('editCode').value);const saved=await write('/posts'+(editing?'/'+editing:''),editing?'PATCH':'POST',{title:$('title').value,nickname:$('nickname').value,category:$('category').value,content:editor.getContents(),editCode:authKey});remember(editing||saved.id,authKey);$('editCode').value='';clearTimeout(timer);try{localStorage.removeItem(draftKey());}catch{}$('composer').close();if($('reader').open)$('reader').close();loadPosts();}catch(err){$('draftStatus').textContent=err.message;}finally{busy=false;$('submitPost').disabled=false;}};
$('commentForm').onsubmit=async e=>{e.preventDefault();if(busy)return;busy=true;try{const key=await credential($('commentPassword').value);const saved=await write('/posts/'+activePost.id+'/comments','POST',{nickname:$('commentNick').value,text:$('commentText').value,editCode:key});remember(saved.id,key);$('commentText').value='';$('commentPassword').value='';$('commentStatus').textContent='댓글이 등록되었습니다.';openPost(activePost.id);}catch(err){$('commentStatus').textContent=err.message;}finally{busy=false;}};
$('searchForm').onsubmit=e=>{e.preventDefault();loadPosts();};$('more').onclick=()=>loadPosts(true);window.addEventListener('beforeunload',()=>{if($('composer').open)saveDraft();});
if(configured()){const s=document.createElement('script');s.src='https://challenges.cloudflare.com/turnstile/v0/api.js?render=explicit';s.async=true;document.head.append(s);loadPosts();}else{status('무료 서버 연결 준비 중입니다. 글쓰기와 임시저장을 미리 살펴볼 수 있습니다. 실제 등록은 연결 후 가능합니다.');$('posts').innerHTML='<div class="empty"><b>✎</b><h2>새로운 커뮤니티를 준비하고 있어요</h2><p>구글 로그인 없이 별명으로 이야기를 남길 수 있게 바뀝니다.</p></div>';}
}
init();
