(()=>{
 if(window.GDWorksheetStats)return;window.GDWorksheetStats=true;
 const siteNames={ko:'한국',us:'United States',gb:'England',ca:'Canada',au:'Australia',ja:'日本',fr:'France',de:'Deutschland',es:'España',it:'Italia',en:'English'};
 const copies={ko:['오늘 문제지 로딩','회'],en:["Today’s worksheet loads",'loads'],ja:['本日のプリント表示','回'],fr:["Chargements aujourd’hui",''],de:['Heutige Arbeitsblattaufrufe',''],es:['Fichas cargadas hoy',''],it:['Schede caricate oggi','']};
 function englishSite(){const path=location.pathname.toLowerCase();if(/^\/en\/(england|uk)-/.test(path))return'gb';if(/^\/en\/australia-/.test(path))return'au';if(/^\/en\/canada-/.test(path))return'ca';if(/^\/en\/us-/.test(path))return'us';const q=new URLSearchParams(location.search).get('country')?.toUpperCase();if(['US','GB','CA','AU'].includes(q))return q.toLowerCase();try{const saved=JSON.parse(localStorage.getItem('gd-learning-region')||'{}').country;if(['US','GB','CA','AU'].includes(saved))return saved.toLowerCase();}catch{}const language=(navigator.language||'').toLowerCase();if(language==='en-gb')return'gb';if(language==='en-ca')return'ca';if(language==='en-au')return'au';return'us';}
 function currentSite(){const edition=location.pathname.split('/')[1].toLowerCase();if(edition==='en')return englishSite();return['ko','ja','fr','de','es','it'].includes(edition)?edition:'ko';}
 function addStyle(){if(document.getElementById('worksheet-metrics-style'))return;const style=document.createElement('style');style.id='worksheet-metrics-style';style.textContent='.worksheet-counter-area{max-width:790px;margin:10px auto 24px;display:flex;flex-wrap:wrap;gap:8px;color:#526e68;font-size:11px;line-height:1.45}.worksheet-metric-card,.worksheet-counter-area .visit-counter{display:flex;align-items:center;justify-content:flex-start;gap:14px;flex-wrap:wrap;width:auto;margin:0;padding:8px 12px;border:1px solid #d2e3df;border-radius:8px;background:#fff;box-shadow:none}.worksheet-metric-card span,.worksheet-counter-area .visit-counter span{white-space:nowrap}.worksheet-metric-card b,.worksheet-counter-area .visit-counter b{margin-left:4px;color:#176e5c;font-size:13px}.worksheet-metric-country{font-weight:700;color:#315f55}@media(max-width:520px){.worksheet-counter-area{margin-left:0;margin-right:0}.worksheet-metric-card,.worksheet-counter-area .visit-counter{width:100%;gap:8px 14px}}@media print{.worksheet-counter-area{display:none!important}}';document.head.append(style);}
 function area(){let box=document.querySelector('.worksheet-counter-area');if(box)return box;const sheet=document.querySelector('.paper,#sheet-view,article.sheet,#sheet,.hundred-paper');if(!sheet)return null;box=document.createElement('div');box.className='worksheet-counter-area';box.setAttribute('aria-label','Site counters');sheet.insertAdjacentElement('afterend',box);return box;}
 addEventListener('DOMContentLoaded',async()=>{addStyle();const box=area();if(!box)return;document.getElementById('worksheet-load-count')?.remove();const lang=(document.documentElement.lang||'en').slice(0,2),copy=copies[lang]||copies.en,site=currentSite();const item=document.createElement('div');item.id='worksheet-load-count';item.className='worksheet-metric-card';item.innerHTML='<span class="worksheet-metric-country">'+siteNames[site]+'</span><span>'+copy[0]+' <b>…</b> '+copy[1]+'</span>';box.append(item);const number=item.querySelector('b');if(!['googoodan.com','www.googoodan.com'].includes(location.hostname)||navigator.webdriver){number.textContent=lang==='ko'?'테스트 제외':'—';return;}let excluded=false;try{excluded=localStorage.getItem('gd_operator_excluded')==='1';}catch{}const endpoint='https://googoodan-community.googoodan-community.workers.dev',payload={id:crypto.randomUUID(),site};try{const response=await fetch(endpoint+(excluded?'/stats/today':'/stats/load'),excluded?{}:{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload),keepalive:true});if(!response.ok)throw Error('HTTP '+response.status);const data=await response.json();number.textContent=Number(data[site]||0).toLocaleString(lang==='ko'?'ko-KR':'en-US');}catch(error){number.textContent=lang==='ko'?'확인 필요':'—';console.warn('Worksheet load count failed',error.message);}});
})();
