(function(){
function mascot(kind){
 const face='<circle cx="45" cy="37" r="2" fill="#294552"/><circle cx="59" cy="37" r="2" fill="#294552"/><path d="M48 44Q52 48 56 44" stroke="#294552" fill="none" stroke-width="1.5"/>';
 const forms={
 rabbit:'<path d="M36 30Q24 2 35 4Q43 5 45 27M54 26Q64 0 71 7Q74 14 65 32" fill="#fff" stroke="currentColor" stroke-width="2"/><ellipse cx="52" cy="40" rx="24" ry="19" fill="#fff" stroke="currentColor" stroke-width="2"/>'+face,
 squirrel:'<path d="M70 60Q104 51 89 21Q75 12 74 28Q94 36 68 47" fill="#e7b17c" stroke="currentColor" stroke-width="2"/><path d="M32 31L32 15L44 24L60 24L70 15V37" fill="#d39b65" stroke="currentColor" stroke-width="2"/><ellipse cx="52" cy="41" rx="23" ry="19" fill="#f9d2a2"/>'+face,
 whale:'<path d="M17 45Q14 19 44 21Q74 20 77 46L95 33L93 54Q58 81 29 60Z" fill="#8ac9df" stroke="currentColor" stroke-width="2"/><path d="M37 16Q31 0 23 7M37 16Q39 0 49 7" stroke="currentColor" fill="none" stroke-width="3"/>'+face,
 bear:'<circle cx="32" cy="23" r="11" fill="#dbb079"/><circle cx="72" cy="23" r="11" fill="#dbb079"/><ellipse cx="52" cy="40" rx="27" ry="23" fill="#efd3a4"/>'+face+'<path d="M13 63L21 45L29 63Z" fill="#75a89c"/>',
 rocket:'<path d="M36 51L28 68L45 61M62 51L75 68L57 61" fill="#9b8cc8"/><path d="M40 60L50 78L59 60" fill="#efbb56"/><path d="M35 59Q31 25 50 7Q73 28 64 59Z" fill="#d9d3f1" stroke="currentColor" stroke-width="2"/><circle cx="50" cy="33" r="10" fill="#c7e7ee" stroke="currentColor"/>',
 dinosaur:'<path d="M24 63Q11 51 12 41L30 52Q29 25 48 24L48 14Q70 7 81 29L78 39L61 39V64L53 70L42 64L35 70Z" fill="#9ace91" stroke="currentColor" stroke-width="2"/><circle cx="69" cy="24" r="2" fill="#294552"/><path d="M29 43L20 37L30 32L25 24L38 26" fill="#e9bc69"/><path d="M64 33h10" stroke="#294552"/>',
 robot:'<rect x="29" y="18" width="47" height="36" rx="8" fill="#d2e5f2" stroke="currentColor" stroke-width="2"/><path d="M52 18V8" stroke="currentColor" stroke-width="2"/><circle cx="52" cy="7" r="4" fill="#edbb63"/><rect x="34" y="55" width="38" height="16" rx="4" fill="#a6c8dc"/>'+face+'<path d="M22 35V47M82 35V47M43 72V78M63 72V78" stroke="currentColor" stroke-width="5"/>',
 submarine:'<rect x="13" y="29" width="73" height="31" rx="16" fill="#edcd7f" stroke="currentColor" stroke-width="2"/><path d="M48 29V16H63" fill="none" stroke="currentColor" stroke-width="5"/><circle cx="36" cy="44" r="9" fill="#b8e0e3" stroke="currentColor"/><circle cx="64" cy="44" r="9" fill="#b8e0e3" stroke="currentColor"/><path d="M87 44L98 30V58Z" fill="#9bc9c9"/>',
 compass:'<path d="M9 20L34 13L62 22L94 12V64L65 72L36 64L9 73Z" fill="#f4dfb5" stroke="currentColor"/><circle cx="52" cy="43" r="24" fill="#fffaf0" stroke="currentColor" stroke-width="2"/><path d="M52 20L43 46L52 42L60 46Z" fill="#d57b65"/><path d="M52 65L43 46L52 42L60 46Z" fill="#79a3ae"/>',
 city:'<path d="M12 72V37H34V72M39 72V15H66V72M72 72V28H92V72" fill="#ccd6ec" stroke="currentColor" stroke-width="2"/><path d="M46 25h6m5 0h3m-14 11h6m5 0h3m-14 11h6m5 0h3M18 47h9M18 58h9M78 39h8M78 51h8" stroke="#edb850" stroke-width="4"/>',
 telescope:'<path d="M45 47L29 76M45 47L64 76M45 47V78" stroke="currentColor" stroke-width="3"/><path d="M19 34L72 12L82 33L30 54Z" fill="#aed9cc" stroke="currentColor" stroke-width="2"/><path d="M71 10L81 6L93 32L83 37Z" fill="#79b6a6"/>',
 satellite:'<path d="M39 29L62 43L53 61L31 47Z" fill="#d7d0e8" stroke="currentColor"/><path d="M11 13L35 27L24 45L1 31ZM67 46L93 61L81 79L57 65Z" fill="#8daccd" stroke="currentColor"/><path d="M37 24Q61 11 69 37Z" fill="#ece6f5" stroke="currentColor"/><path d="M57 27L72 12" stroke="currentColor" stroke-width="2"/><circle cx="73" cy="11" r="3" fill="#efbc5a"/>'
 };
 return '<svg class="mascot" viewBox="0 0 105 82" aria-hidden="true" style="color:var(--accent)">'+forms[kind]+'</svg>';
}

const DC=DrillCatalog,params=new URLSearchParams(window.WORKSHEET_ENTRY?.query||location.search),esc=s=>String(s??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;');
const requested=(params.get('unit')||'').split('-');let selectedUnit=DC.units.find(u=>u.id===params.get('unit'))||DC.units.find(u=>u.grade===+requested[0]&&u.semester===+requested[1])||DC.units[0];let selected=selectedUnit.drills.find(p=>p.id===params.get('drill'))||selectedUnit.drills[0];
seed=Number(new URLSearchParams(location.search).get('set'))||Number(params.get('set'))||seed;let browseUnit=selectedUnit;
function navigateProfile(id){if(browseUnit.id===selectedUnit.id&&id===selected.id)return;location.href='/fr/print/drill-'+encodeURIComponent(id)+'.html';}
const groupNames=['Calcul de base','Révisions','Calculs à trous','Problèmes'];
function nav(){return '<nav class="edition-tabs"><a href="/fr/"><span class="arithmetic-menu-icons" aria-hidden="true"><span>＋</span><span>−</span><span>×</span><span>÷</span></span><span>Calcul</span></a><a href="/fr/drills.html" aria-current="page">Calcul par chapitre</a><a href="/fr/units.html">Exercices par chapitre</a></nav>';}
function setProfile(id){selected=DC.profiles.get(id);current=types.find(t=>t.id===id);menu();render();}
menu=function(){groups.innerHTML=nav()+'<div class="drill-grades">'+[...new Set(DC.units.map(u=>u.grade))].map(g=>'<button data-grade="'+g+'" aria-pressed="'+(g===browseUnit.grade)+'">'+(DC.units.find(u=>u.grade===g).gradeLabel||g)+'</button>').join('')+'</div><div class="drill-terms">'+[].map(t=>'<button data-term="'+t+'" aria-pressed="'+(t===browseUnit.semester)+'">'+t+' période</button>').join('')+'</div><label for="drill-unit">Chapitre</label><select id="drill-unit">'+DC.units.filter(u=>u.grade===browseUnit.grade&&u.semester===browseUnit.semester).map(u=>'<option value="'+u.id+'" '+(u.id===browseUnit.id?'selected':'')+'>'+u.number+'. '+u.name+'</option>').join('')+'</select><p class="drill-help">'+browseUnit.drills.length+'types · Choisissez votre exercice.</p>'+groupNames.map(g=>'<details '+(g===selected.group?'open':'')+'><summary>'+g+' <small>'+browseUnit.drills.filter(p=>p.group===g).length+'</small></summary>'+browseUnit.drills.filter(p=>p.group===g).map(p=>'<button class="drill-choice" data-drill="'+p.id+'" aria-pressed="'+(p.id===selected.id)+'"><strong class="drill-example">'+esc(sampleText(p).replace(/(\d)\.(\d)/g,'$1,$2'))+'</strong><small class="drill-description">'+esc(p.title)+'</small></button>').join('')+'</details>').join('');
groups.querySelectorAll('[data-grade]').forEach(b=>b.onclick=()=>{browseUnit=DC.units.find(u=>u.grade===+b.dataset.grade&&u.semester===browseUnit.semester)||DC.units.find(u=>u.grade===+b.dataset.grade);menu()});groups.querySelectorAll('[data-term]').forEach(b=>b.onclick=()=>{browseUnit=DC.units.find(u=>u.grade===browseUnit.grade&&u.semester===+b.dataset.term);menu()});groups.querySelector('#drill-unit').onchange=e=>{browseUnit=DC.units.find(u=>u.id===e.target.value);menu()};groups.querySelectorAll('[data-drill]').forEach(b=>b.onclick=()=>navigateProfile(b.dataset.drill));};
function sampleText(p){const q=DrillEngine.rows(p,713,1)[0];if(q.prompt)return q.prompt;if(p.mode==='blank')return [q.mask===0?'□':q.a,q.op,q.mask===1?'□':q.b,'=',q.mask===2?'□':q.answer].join(' ');if(p.mode==='digit')return 'Complétez les chiffres cachés par □';return q.a+' '+q.op+' '+q.b+' = '+String(q.answer).replace(' R ',' reste ');}
function scalar(x){return mathHTML(x);}
function fractionText(s){return esc(s).replace(/(\d+)[と과] (\d+\/\d+)/g,'($1 + $2)').replace(/(\d+) (\d+\/\d+)/g,'($1 + $2)').replace(/(\d+)\uacfc (\d+\/\d+)/g,(_,w,f)=>scalar(w+' '+f)).replace(/(?<![\d>])(\d+)\/(\d+)(?![\d<])/g,(_,n,d)=>scalar(n+'/'+d));}
function hide(s,show){return '<span class="drill-solution '+(show?'':'concealed')+'">'+s+'</span>';}
function decimalMultiply(q,show){const a=Number(String(q.a).replace('.','')),b=String(q.b).replace('.',''),parts=[...b].reverse().map((n,i)=>a*Number(n)*10**i);return '<div class="worked multiplication"><div>'+q.a+'</div><div class="work-rule">× '+q.b+'</div><div class="working '+(show?'':'concealed')+'">'+(b.length>1?parts.map(v=>'<div>'+v+'</div>').join(''):'')+'<div class="work-total">'+q.answer+'</div></div></div>';}
function qhtml(q,i,show){let html='';
if(selected.mode==='skill'||selected.mode==='story'){let art='';if(q.groups){const[a,b]=q.groups;art='<div class="dot-groups">'+Array.from({length:b},()=>'<span>'+Array(a).fill('●').join(' ')+'</span>').join('')+'</div>';}html='<div class="drill-prompt">'+fractionText(q.prompt)+'</div>'+art+'<div class="drill-response">'+hide(fractionText(q.answer),show)+'</div>'+hide('<small>'+fractionText(q.work||'')+'</small>',show);}
else if(selected.mode==='blank'){const list=[q.a,q.b,q.answer];const answer=scalar(list[q.mask]);const terms=list.map((x,j)=>j===q.mask?'<span class="drill-box">'+hide(answer,show)+'</span>':scalar(x));html='<div class="drill-equation">'+terms[0]+' '+q.op+' '+terms[1]+' = '+terms[2]+'</div>';}
else if(selected.mode==='digit'){const digit=(v,which)=>String(v).split('').map((c,j)=>q.digits.which===which&&q.digits.positions.includes(j)?'<span class="digit-box">'+hide(c,show)+'</span>':'<span class="digit-cell">'+c+'</span>').join('');if(q.op==='÷'){html='<div class="digit-division"><div class="digit-quotient">'+esc(String(q.answer).replace(' R ',' reste '))+'</div><div>'+digit(q.b,1)+' <span class="dividend-digits">'+digit(q.a,0)+'</span></div></div>';}else html='<div class="digit-vertical"><div>'+digit(q.a,0)+'</div><div class="digit-rule">'+q.op+' '+digit(q.b,1)+'</div><div>'+digit(q.answer,2)+'</div></div>';}
else{const work=selected.layout==='vertical'?(current.family==='Decimals'&&q.op==='×'?decimalMultiply(q,show):writtenWork(q,show)):null;if(work)html=work;else if(selected.layout==='vertical')html='<div class="vertical"><div>'+esc(q.a)+'</div><div class="bottom"><span>'+q.op+'</span><span>'+esc(q.b)+'</span></div><div class="result">'+hide(scalar(q.answer),show)+'</div></div>';else html='<span class="expression">'+scalar(q.a)+' '+q.op+' '+scalar(q.b)+' =</span><span class="answer '+(q.op==='÷'&&current.family==='Natural numbers'?'division-answer-line ':'')+(show?'':'concealed')+'">'+(q.fraction?fractionAnswer(q):scalar(q.answer))+'</span>';
}
html=html.replace(/(<span class="mixed-whole">[^<]+<\/span>)(<span class="fraction"><span>[^<]+<\/span><span>[^<]+<\/span><\/span>)/g,'($1 + $2)');if(current.family==='Decimals'||selected.skill==='decimal-scale')html=html.replace(/(\d)\.(\d)/g,'$1,$2');return '<div class="problem"><span class="number">'+(i+1)+'.</span>'+html+'</div>';}
function layout(){const q=generate(current.id,seed,1)[0],vert=selected.layout==='vertical',op=q.op;let cols=4,count=48;
if(selected.mode==='story'){cols=2;count=selectedUnit.grade<=2?12:16;}
else if(selected.mode==='skill'){cols=2;count=selected.skill==='groups'?6:20;}
else if(selected.mode==='digit'){cols=3;count=18;}
else if(current.family==='Fractions'){cols=2;count=20;}
else if(selected.mode==='blank'){cols=2;count=24;}
else if(vert&&op==='÷'){cols=2;count=current.family==='Decimals'?4:Math.max(String(q.a).length,String(q.b).length)>=3?4:6;}
else if(vert&&op==='×'){cols=3;const d=String(q.b).replace('.','').length;count=d>=4?6:d>=3?9:12;}
else if(vert){cols=4;count=24;}
else if(selectedUnit.grade<=2){cols=3;count=24;}
return {cols,count};}
render=function(){const theme=KoCatalog.themes[(selectedUnit.grade-1)*2+selectedUnit.semester-1],paper=document.querySelector('.paper');current=types.find(t=>t.id===selected.id);paper.classList.add('drill-sheet');paper.classList.toggle('written-sheet',selected.layout==='vertical');paper.dataset.family=current.family;paper.style.setProperty('--tone',theme[2]);paper.style.setProperty('--wash',theme[3]);
const remedial=selected.group==='Révisions';document.querySelector('#sheet-title').textContent=(remedial?'[Révisions] ':'')+selected.title;document.querySelector('.adventure-label').textContent=(selectedUnit.gradeLabel||selectedUnit.grade)+' · '+selectedUnit.number+'. '+selectedUnit.name;document.querySelector('#instructions').textContent=remedial?'Révisez les bases de ce chapitre':selected.mode==='story'?'Lisez le problème et choisissez le calcul.':selected.mode==='digit'||selected.mode==='blank'?'Écrivez le nombre qui manque dans □.':'Effectuez les calculs.';
let art=paper.querySelector('.drill-theme');if(!art){paper.querySelector('.math-buddy')?.remove();art=document.createElement('div');art.className='drill-theme';paper.querySelector('.sheet-hero').append(art)}art.innerHTML=KoThemeScene(theme[4],mascot);
const grid=paper.querySelector('.problems'),plan=layout();grid.classList.toggle('fraction-sheet',current.family==='Fractions');grid.classList.toggle('drill-word-grid',['skill','story'].includes(selected.mode));paper.style.setProperty('--cols',plan.cols);let count=plan.count;const all=generate(current.id,seed,count);let rows;
// Fit using the answer layout; hidden answers reserve identical space on worksheets.
do{rows=all.slice(0,count);paper.style.setProperty('--rows',Math.ceil(count/plan.cols));grid.innerHTML=rows.map((q,i)=>qhtml(q,i,true)).join('');const bad=[...grid.children].some(el=>el.scrollHeight>el.clientHeight+1||el.scrollWidth>el.clientWidth+1);if(!bad)break;count-=plan.cols;}while(count>=plan.cols);
if(count<plan.cols)throw Error('Espace insuffisant sur la fiche: '+selected.id);
grid.innerHTML=rows.map((q,i)=>qhtml(q,i,answers)).join('');document.querySelector('#mode').textContent=answers?'Corrigé':'Fiche';document.querySelector('#questions').setAttribute('aria-pressed',!answers);document.querySelector('#answers').setAttribute('aria-pressed',answers);document.querySelector('#set').textContent=selectedUnit.id+' · '+count+' exercices · '+seed;document.querySelector('#status').textContent=selected.title+' · '+count+' exercices';scalePage();history.replaceState(null,'',window.WORKSHEET_ENTRY?location.pathname:('?unit='+selectedUnit.id+'&drill='+selected.id+'&set='+seed));};
function scalePage(){const paper=document.querySelector('.paper'),w=document.querySelector('.layout>section').clientWidth-12;paper.style.zoom=String(Math.min(1,w/(186*96/25.4)));}window.addEventListener('resize',scalePage);
rootInit();scalePage();function rootInit(){document.querySelector('aside>p').textContent='Choisissez un calcul ou une révision';setProfile(selected.id);}
window.GDWorksheetContext=()=>({unit:selectedUnit.id,drill:selected.id,set:seed});
window.DrillPage={set(unit,id,number=713){selectedUnit=DC.units.find(u=>u.id===unit);seed=number;setProfile(id||selectedUnit.drills[0].id)},inspect(){return {unit:selectedUnit.id,profile:selected.id,count:document.querySelectorAll('.paper>.problems>.problem').length}},render};
})();
