(function(root){const base={profiles:()=>[],excludeArt:()=>{}},banks={};let excluded=[];
function add(id,name,op,kind,same=false){(banks[id]??=[]).push({name,op,kind,same,activities:[{title:'Calculer avec des fractions'},{title:'Trouver la fraction manquante'},{title:'Résoudre un problème'}]})}
for(const id of ['4-2-1','5-1-5']){const same=id==='4-2-1';for(const [kind,label] of [['proper','진분수'],['mixed','대분수']])for(const op of ['+','−'])add(id,label+' '+(op==='+'?'덧셈':'뺄셈')+' · '+(same?'같은 분모':'다른 분모'),op,kind,same)}
for(const [kind,label] of [['proper','진분수 × 진분수'],['mixed','대분수 × 진분수'],['whole-left','자연수 × 진분수'],['whole-right','진분수 × 자연수']])add('5-2-2',label,'×',kind);
for(const [kind,label] of [['proper','진분수 ÷ 자연수'],['mixed','대분수 ÷ 자연수'],['whole-left','자연수 ÷ 자연수 · 분수로 나타내기']])add('6-1-1',label,'÷',kind);
for(const [kind,label] of [['proper','진분수 ÷ 진분수'],['mixed','대분수 ÷ 진분수'],['whole-left','자연수 ÷ 진분수']])add('6-2-1',label,'÷',kind);
const gcd=(a,b)=>b?gcd(b,a%b):a,reduce=x=>{const g=gcd(x[0],x[1]);return [x[0]/g,x[1]/g]},fmt=x=>{x=reduce(x);return x[1]===1?String(x[0]):x[0]>x[1]?Math.floor(x[0]/x[1])+' + '+x[0]%x[1]+'/'+x[1]:x[0]+'/'+x[1]},html=x=>x[1]===1?String(x[0]):x[0]>x[1]?Math.floor(x[0]/x[1])+(x[0]%x[1]===0?'':' + ')+ (x[0]%x[1]===0?'':html([x[0]%x[1],x[1]])):'<span class="kf"><span>'+x[0]+'</span><span>'+x[1]+'</span></span>',op=(a,b,s)=>reduce(s==='+'?[a[0]*b[1]+b[0]*a[1],a[1]*b[1]]:s==='−'?[a[0]*b[1]-b[0]*a[1],a[1]*b[1]]:s==='×'?[a[0]*b[0],a[1]*b[1]]:[a[0]*b[1],a[1]*b[0]]);
function generate(id,p,seed,n=8){const offset=base.profiles(id).length;if(!banks[id]||p<offset)return base.generate(id,p,seed,n);const s=banks[id][p-offset],art=KoArt.session(seed,excluded);let state=seed>>>0;const r=(a,b)=>{state=(Math.imul(state,1664525)+1013904223)>>>0;return a+Math.floor(state/4294967296*(b-a+1))};return s.activities.map((act,k)=>({title:act.title,skill:s.kind,questions:Array.from({length:n},(_,index)=>{const d=r(2,9),e=s.same?d:d===9?8:d+1;let a=[r(1,d-1),d],b=[r(1,e-1),e];if(s.kind==='mixed')a[0]+=d*r(1,3);if(s.kind==='whole-left')a=[r(2,8),1];if(s.kind==='whole-right'||id==='6-1-1')b=[r(2,6),1];if(s.op==='−'&&a[0]*b[1]<b[0]*a[1])[a,b]=[b,a];const result=op(a,b,s.op),asset=art.take(x=>['음식','동물과 자연','놀이와 운동'].includes(x.category));let prompt,task,answer,reason,visual='<span class="picture-badge">'+KoArt.icon(asset)+'</span>';
if(k===0){prompt='Calcule et simplifie le résultat si nécessaire.';task='<div class="kequation">'+html(a)+' '+s.op+' '+html(b)+' = □</div><div class="calculation-space"></div>';answer=fmt(result);reason=fmt(a)+' '+s.op+' '+fmt(b)+' = '+fmt(result)}
if(k===1){prompt='Trouve la fraction manquante, puis vérifie dans l’égalité.';task='<div class="kequation">□ '+s.op+' '+html(b)+' = '+html(result)+'</div><div class="calculation-space"></div>';answer=fmt(a);reason='Vérification : '+fmt(a)+' '+s.op+' '+fmt(b)+' = '+fmt(result)}
if(k===2){const va=fmt(a),vb=fmt(b);if(s.op==='+'){prompt='On utilise '+va+' m de ruban. Il reste '+vb+' m. Quelle était la longueur initiale?';answer=fmt(result)+' m';reason='Longueur initiale = longueur utilisée + longueur restante'}if(s.op==='−'){prompt='On avait '+va+' L d’eau. Il reste '+vb+' L après utilisation. Quelle quantité a été utilisée?';answer=fmt(result)+' L';reason='Quantité utilisée = quantité initiale − quantité restante'}if(s.op==='×'){prompt='Un mètre de ficelle pèse '+va+' g. Quelle est la masse de '+vb+' m de cette ficelle?';answer=fmt(result)+' g';reason='Multiplie la masse d’un mètre par la longueur.'}if(s.op==='÷'){prompt='줄 '+va+' m를 '+(b[1]===1?vb+'명이 똑같이 나누어 가집니다. 한 명이 가지는 길이는 몇 m인가요?':vb+' m에 해당하는 양으로 나누어 나타내세요. 몇 배인가요?');answer=fmt(result)+(b[1]===1?' m':'배');reason='전체 길이를 '+(b[1]===1?'사람 수':'기준이 되는 길이')+'로 나눕니다.'}const variant=index%4;if(s.op==='−'){prompt=[prompt,'Une ficelle mesure '+va+' m. On coupe '+vb+' m. Quelle longueur reste-t-il?','On a marché '+va+' km hier et '+vb+' km aujourd’hui. Quelle est la différence?','Après avoir ajouté '+vb+' kg de farine, on obtient '+va+' kg. Quelle était la masse initiale?'][variant];answer=fmt(result)+[' L',' m',' km',' kg'][variant];reason=['Quantité utilisée = quantité initiale − quantité restante','Longueur restante = longueur initiale − longueur coupée','Différence = distance d’hier − distance d’aujourd’hui','Quantité initiale = quantité finale − quantité ajoutée'][variant]}if(s.op==='+'){prompt=[prompt,'Le contenu d’une boîte pèse '+va+' kg et la boîte vide '+vb+' kg. Quelle est la masse totale?','On marche '+va+' km le matin puis '+vb+' km l’après-midi. Quelle distance parcourt-on en tout?','Une bouteille contient '+va+' L. Une autre contient '+vb+' L de plus. Quelle quantité contient la seconde?'][variant];answer=fmt(result)+[' m',' kg',' km',' L'][variant];reason=['Longueur initiale = longueur utilisée + longueur restante','Masse totale = masse du contenu + masse de la boîte','Distance totale = distance du matin + distance de l’après-midi','Seconde bouteille = première bouteille + quantité supplémentaire'][variant]}task='Calcul : __________________<div class="calculation-space"></div>Réponse : __________________'}
return {methodId:s.kind+'-'+s.op+'-'+k,artId:asset.id,prompt,visual,task,answer,reason,check:{kind:'fraction-target',a,b,result,op:s.op}};})}));}
root.FrFractionTargets={multiplyProfiles:banks['5-2-2'].slice(2,4).map((p,i)=>({...p,name:i?'Multiplier une fraction par un entier':'Multiplier un entier par une fraction'})),generateMultiply(p,seed,n,ids=[]){if(p<0||p>1)throw Error('Unsupported profile');excluded=ids;return generate('5-2-2',p+2,seed,n)},profiles:banks['4-2-1'].slice(0,2).map((p,i)=>({...p,name:i?'Soustraire des fractions de même dénominateur':'Additionner des fractions de même dénominateur'})),generate(p,seed,n,ids=[]){if(p<0||p>1)throw Error('Unsupported profile');excluded=ids;return generate('4-2-1',p,seed,n)}};
})(globalThis);
