(function(root){const base={profiles:()=>[],generate:()=>{throw Error('Unsupported unit')}},banks={};let excluded=[];
const add=(id,name,type,data)=>{(banks[id]??=[]).push({name,type,...data,activities:[{title:'Convertir une mesure'},{title:'Décomposer une mesure'},{title:'Comparer des mesures'}]})};
for(const [id,large,small,factor] of [['2-2-3','m','cm',100],['3-1-5','cm','mm',10],['3-1-5','km','m',1000],['3-2-4','L','mL',1000],['3-2-4','kg','g',1000],['5-1-6','m²','cm²',10000],['6-1-6','m³','cm³',1000000]])add(id,large+' et '+small+' : convertir et comparer','measure',{large,small,factor});
add('1-2-3','Heures entières et demi-heures','clock',{step:30});add('2-2-4','Lire l’heure de cinq en cinq minutes','clock',{step:5});add('3-1-5','Départ, arrivée et durée','duration',{});
function clock(h,m,blank){let face='<circle cx="70" cy="70" r="57" fill="#fffaf0" stroke="#739792" stroke-width="2"/>';for(let i=1;i<=12;i++){let a=i*Math.PI/6;face+='<text x="'+(70+46*Math.sin(a))+'" y="'+(74-46*Math.cos(a))+'" text-anchor="middle" font-size="11">'+i+'</text>'}if(!blank){for(const [angle,len,width] of [[(h%12+m/60)*Math.PI/6,29,3],[m*Math.PI/30,42,2]])face+='<path d="M70 70L'+(70+len*Math.sin(angle))+' '+(70-len*Math.cos(angle))+'" stroke="#294552" stroke-width="'+width+'"/>'}return '<svg class="learning-clock" viewBox="0 0 140 140">'+face+'<circle cx="70" cy="70" r="2" fill="#294552"/></svg>'}
function generate(id,p,seed,n=8){let offset=base.profiles(id).length;if(!banks[id]||p<offset)return base.generate(id,p,seed,n);const s=banks[id][p-offset],art=KoArt.session(seed,excluded);let state=seed>>>0;const r=(a,b)=>{state=(Math.imul(state,1664525)+1013904223)>>>0;return a+Math.floor(state/4294967296*(b-a+1))},fmt=t=>Math.floor(t/60)+' h '+(t%60)+' min';return s.activities.map((activity,k)=>({title:activity.title,skill:s.type,questions:Array.from({length:n},()=>{const asset=art.take();let prompt,visual='<span class="picture-badge">'+KoArt.icon(asset)+'</span>',task='________________________',answer,reason,check;
if(s.type==='measure'){const a=r(1,8),b=r(1,9)*(s.factor/10),total=a*s.factor+b;if(k===0){prompt='Exprime la mesure dans une seule unité.';task=a+s.large+' '+b+s.small+' = □ '+s.small;answer=total+s.small;reason='1 '+s.large+' = '+s.factor+' '+s.small+'. Calcule '+a*s.factor+' + '+b+'.'}if(k===1){prompt='Complète les nombres pour convertir la mesure.';task=total+s.small+' = □ '+s.large+' □ '+s.small;answer=a+s.large+' '+b+s.small;reason='On forme '+a+' groupes de '+s.factor+' '+s.small+' ; il reste '+b+' '+s.small+'.'}if(k===2){const c=r(1,9)*s.factor/10,other=a*s.factor+c;prompt='Convertis dans la même unité, puis complète avec >, = ou <.';task=a+s.large+' '+b+s.small+' □ '+other+s.small;answer=total===other?'=':total>other?'>':'<';reason='Compare '+total+' '+s.small+' et '+other+' '+s.small+'.'}check={kind:'measurement',factor:s.factor,a,b,total}}
if(s.type==='clock'){const h=r(1,11),m=r(0,60/s.step-1)*s.step;visual+=clock(h,m,k!==1);if(k===0){prompt='Dessine les deux aiguilles pour indiquer '+h+' h '+m+' min.';task='<div class="kshort-space"></div>';answer=h+' h '+m+' min';reason='La grande aiguille indique '+(m===0?12:m/5)+' ; la petite est '+(m===0?'sur '+h:'entre '+h+' et '+(h+1))+'.'}if(k===1){prompt='Lis l’heure, puis indique l’heure trente minutes plus tard.';task='Maintenant : __________<br>30 min plus tard : __________';answer=fmt(h*60+m)+' / '+fmt(h*60+m+30);reason='60 minutes font une heure.'}if(k===2){prompt='La grande aiguille indique '+(m===0?12:m/5)+' et la petite est '+(m===0?'sur '+h:'entre '+h+' et '+(h+1))+'. Écris l’heure et dessine les aiguilles.';task='Heure : __________________';answer=fmt(h*60+m);reason='Entre deux nombres du cadran, il y a cinq minutes.'}}
if(s.type==='duration'){const start=r(8,10)*60+r(0,5)*10,duration=r(2,7)*10,end=start+duration;if(k===0){prompt='Le départ est à '+fmt(start)+' et l’arrivée à '+fmt(end)+'. Quelle est la durée du trajet ?';answer=duration+' min';reason=end+' min − '+start+' min = '+duration+' min'}if(k===1){prompt='L’arrivée est à '+fmt(end)+'. Le trajet dure '+duration+' min. À quelle heure a eu lieu le départ ?';answer=fmt(start);reason='Soustrais la durée à l’heure d’arrivée.'}if(k===2){prompt='Une activité commence à '+fmt(start)+' et dure '+duration+' min. À quelle heure se termine-t-elle ?';answer=fmt(end);reason='Ajoute la durée à l’heure de départ.'}task='Calcul ou ligne du temps : __________________<div class="calculation-space"></div>Réponse : __________________';check={kind:'duration',start,duration,end}}
return {methodId:s.type+'-'+k,artId:asset.id,prompt,visual,task,answer,reason,check};})}));}
root.FrMeasurement={profiles:banks['2-2-3'],clockProfiles:[banks['1-2-3'][0],banks['2-2-4'][0]].map(s=>({...s,activities:[{title:'Dessiner les aiguilles'},{title:'Lire et avancer de trente minutes'},{title:'Comprendre les positions des aiguilles'}]})),generateClock(p,seed,n,ids=[]){if(p!==0&&p!==1)throw Error('Unsupported profile');excluded=ids;return generate(p===0?'1-2-3':'2-2-4',0,seed,n).map((s,i)=>({...s,title:this.clockProfiles[p].activities[i].title}))},durationProfiles:[{...banks['3-1-5'][2],activities:[{title:'Calculer une durée'},{title:'Retrouver l’heure de départ'},{title:'Trouver l’heure de fin'}]}],generateDuration(p,seed,n,ids=[]){if(p!==0)throw Error('Unsupported profile');excluded=ids;return generate('3-1-5',2,seed,n).map((s,i)=>({...s,title:this.durationProfiles[0].activities[i].title}))},metricProfiles:[banks['3-1-5'][0],banks['3-1-5'][1],banks['3-2-4'][1]],generateMetric(p,seed,n,ids=[]){const mapping=[['3-1-5',0],['3-1-5',1],['3-2-4',1]];if(!Number.isInteger(p)||!mapping[p])throw Error('Unsupported profile');excluded=ids;return generate(mapping[p][0],mapping[p][1],seed,n)},generate(p,seed,n,ids=[]){if(p!==0)throw Error('Unsupported profile');excluded=ids;return generate('2-2-3',p,seed,n)}};
})(globalThis);
