const geometryActivities=[{title:'Reconnaître les figures',method:'flat-basic'},{title:'Compter les côtés',method:'flat-count'},{title:'Assembler deux triangles',method:'flat-build'}];function geometryGenerate(p,seed,n){if(p!==0)throw Error('Unknown profile');const art=KoArt.session(seed,excluded);return FrCoreGeometry.generate('1-2-3',seed,n).map((s,i)=>({...s,title:geometryActivities[i].title,questions:s.questions.map(q=>{const a=art.take();return {...q,methodId:geometryActivities[i].method,artId:a.id,visual:'<span class="picture-badge">'+KoArt.icon(a)+'</span>'+q.visual}})}))}
const numberUnits={'fr-ce1-numbers999':'2-1-1','fr-cp-numbers50':'1-1-5','fr-cp-numbers100':'1-2-1'};const numberActivities=[{title:'Repérer la valeur des chiffres',method:'place'},{title:'Comparer les nombres',method:'compare'},{title:'Compléter une suite',method:'sequence'}];function numberGenerate(id,p,seed,n){if(p!==0)throw Error('Unknown profile');const art=KoArt.session(seed,excluded);return FrCoreNumbers.generate(numberUnits[id],seed,n).map((s,i)=>({...s,title:numberActivities[i].title,questions:s.questions.map(q=>{const a=art.take();return {...q,methodId:numberActivities[i].method,artId:a.id,visual:'<span class="picture-badge">'+KoArt.icon(a)+'</span>'+q.visual}})}))}
globalThis.KoCatalog={units:[{id:'fr-cp-numbers',grade:1,semester:1,number:1,name:'Les nombres jusqu’à 9'}],themes:[["Un peu de pratique pour progresser","Réfléchis et vérifie","#278477","#edf8e9","rabbit"],["Un peu de pratique pour progresser","Réfléchis et vérifie","#ad693d","#fff3e4","squirrel"],["Un peu de pratique pour progresser","Réfléchis et vérifie","#237e9a","#eaf7fc","whale"],["Un peu de pratique pour progresser","Réfléchis et vérifie","#86622f","#fff8e8","bear"],["Un peu de pratique pour progresser","Réfléchis et vérifie","#6752a1","#f1effc","rocket"],["Un peu de pratique pour progresser","Réfléchis et vérifie","#438354","#edf7eb","dinosaur"],["Un peu de pratique pour progresser","Réfléchis et vérifie","#376b91","#edf4fb","robot"],["Un peu de pratique pour progresser","Réfléchis et vérifie","#257d88","#eaf7f6","submarine"],["Un peu de pratique pour progresser","Réfléchis et vérifie","#8c6240","#faf2e7","compass"],["Un peu de pratique pour progresser","Réfléchis et vérifie","#596b9b","#eff2fb","city"],["Un peu de pratique pour progresser","Réfléchis et vérifie","#397a71","#ecf6f1","telescope"],["Un peu de pratique pour progresser","Réfléchis et vérifie","#6e5f90","#f4f0f9","satellite"]]};let excluded=[];globalThis.KoMath={profiles:id=>id==='fr-cp-figures'?[{name:"Reconnaître et assembler",activities:geometryActivities}]:numberUnits[id]?[{name:"Valeur des chiffres et ordre",activities:numberActivities}]:id==='fr-cp-calcul100'?KoEarlyArithmetic.banks['1-2-6']:id==='fr-cp-relations'?KoEarlyArithmetic.banks['1-2-4']:id==='fr-cp-ten'?KoEarlyArithmetic.banks['1-2-2']:KoEarlyNumbers.profiles,generate:(id,p,seed,n)=>id==='fr-cp-figures'?geometryGenerate(p,seed,n):numberUnits[id]?numberGenerate(id,p,seed,n):id==='fr-cp-calcul100'?KoEarlyArithmetic.generate('1-2-6',p,seed,n,excluded):id==='fr-cp-relations'?KoEarlyArithmetic.generate('1-2-4',p,seed,n,excluded):id==='fr-cp-ten'?KoEarlyArithmetic.generate('1-2-2',p,seed,n,excluded):KoEarlyNumbers.generate(p,seed,n,excluded),excludeArt:ids=>{excluded=ids}};const icon=KoArt.icon,count=KoArt.count,absolute=a=>({...a,file:a.file.startsWith('/')?a.file:'/ko/'+a.file});KoArt.icon=(a,...args)=>icon(absolute(a),...args).replace(/alt="[^"]*"/g,'alt=""');KoArt.count=(a,...args)=>count(absolute(a),...args).replace(/alt="[^"]*"/g,'alt=""');
KoCatalog.units.push({id:"fr-cp-ten",grade:1,semester:1,number:2,name:"Trois nombres et compléments à 10"});

KoCatalog.units.push({id:"fr-cp-relations",grade:1,semester:1,number:3,name:"Relations entre additions et soustractions"});
KoCatalog.units.push({id:"fr-cp-calcul100",grade:1,semester:1,number:4,name:"Calculer avec des nombres à deux chiffres"});
KoCatalog.units.push({id:"fr-cp-numbers50",grade:1,semester:1,number:5,name:"Les nombres jusqu’à 50"});
KoCatalog.units.push({id:"fr-cp-numbers100",grade:1,semester:1,number:6,name:"Les nombres jusqu’à 100"});
KoCatalog.units.push({id:"fr-cp-figures",grade:1,semester:1,number:7,name:"Les figures planes"});
KoCatalog.units.push({id:"fr-ce1-numbers999",grade:2,semester:1,number:1,name:"Les nombres à trois chiffres"});