(function(root){const banks={};let excluded=[];for(const [id,type] of [['2-2-5','bar'],['3-2-6','picture'],['4-1-5','bar'],['4-2-5','line'],['6-1-5','percent']])banks[id]=[{name:type==='line'?'変わり方を比べる折れ線グラフ':type==='percent'?'資料の割合と帯グラフ':type==='picture'?'絵一つ分の数と資料の読み取り':'表と棒グラフの読み取り',type,activities:[{title:'資料を読む'},{title:'表し方を変える'},{title:'資料から考える'}]}];
function generate(id,p,seed,n=8){const s=banks[id][p],art=KoArt.session(seed,excluded);let state=seed>>>0;const r=(a,b)=>{state=(Math.imul(state,1664525)+1013904223)>>>0;return a+Math.floor(state/4294967296*(b-a+1))};return s.activities.map((act,k)=>({title:act.title,skill:s.type,questions:Array.from({length:n},(_,index)=>{const asset=art.take(x=>['음식','동물과 자연','놀이와 운동'].includes(x.category)),labels=s.type==='line'?['月','火','水','木']:['ア','イ','ウ','エ'];let values=Array.from({length:4},()=>r(1,8));if(s.type==='percent'){values=[r(1,3),r(1,3),r(1,2),0];values[3]=10-values.slice(0,3).reduce((a,b)=>a+b,0);values=values.map(x=>x*10)}const unit=s.type==='percent'?'%':'個',sum=values.reduce((a,b)=>a+b,0),max=Math.max(...values),winner=labels.filter((x,i)=>values[i]===max).join(', ');let prompt,task='',answer,reason='',visual='<span class="picture-badge">'+KoArt.icon(asset)+'</span>';
const table='<table class="ktable"><tr>'+labels.map(x=>'<th>'+x+'</th>').join('')+'</tr><tr>'+values.map(x=>'<td>'+x+unit+'</td>').join('')+'</tr></table>';
function chart(empty=false){const top=20,bottom=125,w=280;let out='<path d="M30 15V125H270" fill="none" stroke="#6b8791"/>';for(let t=0;t<=8;t+=2){const y=bottom-t*12;out+='<path d="M30 '+y+'H270" stroke="#dce6e8"/><text x="22" y="'+(y+4)+'" text-anchor="end" font-size="20">'+t+'</text>'}for(let i=0;i<4;i++){const x=60+i*55;out+='<text x="'+x+'" y="140" text-anchor="middle" font-size="20">'+labels[i]+'</text>';if(!empty)out+=s.type==='line'?'<circle cx="'+x+'" cy="'+(bottom-values[i]*12)+'" r="3" fill="#237d79"/>':'<rect x="'+(x-13)+'" y="'+(bottom-values[i]*12)+'" width="26" height="'+(values[i]*12)+'" fill="#85c9ba" stroke="#477e77"/>'}if(s.type==='line'&&!empty)out+='<polyline points="'+values.map((v,i)=>(60+i*55)+','+(bottom-v*12)).join(' ')+'" fill="none" stroke="#237d79" stroke-width="2"/>';if(empty){out+='<g class="geometry-answer">';if(s.type==='line'){out+='<polyline points="'+values.map((v,i)=>(60+i*55)+','+(bottom-v*12)).join(' ')+'" fill="none" stroke="#c62828" stroke-width="2"/>';out+=values.map((v,i)=>'<circle cx="'+(60+i*55)+'" cy="'+(bottom-v*12)+'" r="3" fill="#c62828"/>').join('')}else out+=values.map((v,i)=>'<rect x="'+(47+i*55)+'" y="'+(bottom-v*12)+'" width="26" height="'+(v*12)+'" fill="#f9dede" stroke="#c62828"/>').join('');out+='</g>'}return '<svg class="data-chart" viewBox="0 0 290 150">'+out+'</svg>'}
if(s.type==='percent'){visual+=table;if(k===0){prompt='全部で200個あるとき、アは何個ですか。';answer=String(values[0]*2)+'個';reason='200 × '+values[0]+'/100'}if(k===1){prompt='表の割合に合わせて帯グラフに区切りをかき、名前を書きましょう。';task='<div class="percent-strip"></div>0%　　　　　　　　50%　　　　　　　　100%';answer=values.slice(0,3).map((_,i)=>values.slice(0,i+1).reduce((a,b)=>a+b,0)+'%').join(', ')+'で区切る';reason='ア・イ・ウ・エの順に割合を足して示します。'}if(k===2){prompt='アとイを合わせた割合はウとエを合わせた割合より大きいですか。数で説明しましょう。';const first=values[0]+values[1],second=100-first;answer=first+'% '+(first>second?'>':first<second?'<':'=')+' '+second+'%';reason='それぞれ二つの割合を足して比べます。'}}
else if(s.type==='picture'){const pict=values.map((v,i)=>'<div>'+labels[i]+': '+'●'.repeat(v)+'</div>').join('');visual+='<div class="picture-data">'+pict+'</div><small>●一つは10個を表します。</small>';if(k===0){prompt='アの実際の数と、全部の数を求めましょう。';answer=values[0]*10+'個、全部で'+sum*10+'個';reason='絵の数に10をかけます。'}if(k===1){prompt='絵グラフを見て、表の□を埋めましょう。';task='<table class="ktable"><tr>'+labels.map(x=>'<th>'+x+'</th>').join('')+'</tr><tr><td>□</td><td>□</td><td>□</td><td>□</td></tr></table>';answer=values.map(x=>x*10).join(', ');reason='絵一つ分の数を先に確かめます。'}if(k===2){prompt='「アとイの実際の数は'+(values[0]+values[1])+'個です」という説明を直しましょう。';answer=(values[0]+values[1])*10+'個';reason='絵の数と実際の数はちがいます。'}}
else{visual+=k===1?table:chart();if(k===0){prompt=s.type==='line'?'最も大きい値と、その曜日をすべて書きましょう。':'最も多い項目と、全部の数を求めましょう。';answer=winner+', '+(s.type==='line'?max:sum)+'個';reason='最も大きい値がいくつかあれば、すべて探します。'}if(k===1){prompt='表を見て、'+(s.type==='line'?'点を順に結んで折れ線グラフを':'棒をかいて棒グラフを')+'完成させましょう。';task=chart(true);answer=labels.map((x,i)=>x+' '+values[i]).join(', ');reason='横の名前と縦の目もりを確かめます。'}if(k===2){if(s.type==='line'){const changes=values.slice(1).map((v,i)=>v-values[i]),largest=Math.max(...changes);prompt='前の日から最も増えた区間と増えた数を書きましょう。増えた区間がなければ「なし」と書きましょう。';answer=largest>0?changes.map((v,i)=>v===largest?labels[i]+'→'+labels[i+1]:'').filter(Boolean).join(', ')+' / '+largest+'個':'増えた区間なし';reason='隣り合う二つの値の差を比べます。'}else{prompt='アとイの合計はウとエの合計よりいくつ多いか少ないかを書きましょう。';const diff=values[0]+values[1]-values[2]-values[3];answer=diff===0?'同じです。':Math.abs(diff)+'個 '+(diff>0?'多いです。':'少ないです。');reason='二つずつの合計を比べます。'}}}
return {methodId:s.type+'-'+k,artId:asset.id,prompt,visual,task:task||'________________________',answer,reason,check:{kind:'data-target',values,sum}};})}));}
root.JaDataTargets={banks,generate};
})(globalThis);
