(function(root){const banks={};let excluded=[];
function add(id,name,op,kind,same=false){(banks[id]??=[]).push({name,op,kind,same,activities:[{title:'数の関係を使って計算する'},{title:'□に入る数を求める'},{title:'場面に合う式を書く'}]})}
for(const id of ['4-2-1','5-1-5']){const same=id==='4-2-1';for(const [kind,label] of [['proper','真分数'],['mixed','帯分数']])for(const op of ['+','−'])add(id,label+' '+(op==='+'?'たし算':'ひき算')+' · '+(same?'同じ分母':'異なる分母'),op,kind,same)}
for(const [kind,label] of [['proper','真分数 × 真分数'],['mixed','帯分数 × 真分数'],['whole-left','整数 × 真分数'],['whole-right','真分数 × 整数']])add('5-2-2',label,'×',kind);
for(const [kind,label] of [['proper','真分数 ÷ 整数'],['mixed','帯分数 ÷ 整数'],['whole-left','整数 ÷ 整数 · 分数で表す']])add('6-1-1',label,'÷',kind);
for(const [kind,label] of [['proper','真分数 ÷ 真分数'],['mixed','帯分数 ÷ 真分数'],['whole-left','整数 ÷ 真分数']])add('6-2-1',label,'÷',kind);
const gcd=(a,b)=>b?gcd(b,a%b):a,reduce=x=>{const g=gcd(x[0],x[1]);return [x[0]/g,x[1]/g]},fmt=x=>{x=reduce(x);return x[1]===1?String(x[0]):x[0]>x[1]?Math.floor(x[0]/x[1])+' '+x[0]%x[1]+'/'+x[1]:x[0]+'/'+x[1]},html=x=>x[1]===1?String(x[0]):x[0]>x[1]?Math.floor(x[0]/x[1])+' '+(x[0]%x[1]===0?'':html([x[0]%x[1],x[1]])):'<span class="kf"><span>'+x[0]+'</span><span>'+x[1]+'</span></span>',op=(a,b,s)=>reduce(s==='+'?[a[0]*b[1]+b[0]*a[1],a[1]*b[1]]:s==='−'?[a[0]*b[1]-b[0]*a[1],a[1]*b[1]]:s==='×'?[a[0]*b[0],a[1]*b[1]]:[a[0]*b[1],a[1]*b[0]]);
function generate(id,p,seed,n=8){const s=banks[id][p],art=KoArt.session(seed,excluded);let state=seed>>>0;const r=(a,b)=>{state=(Math.imul(state,1664525)+1013904223)>>>0;return a+Math.floor(state/4294967296*(b-a+1))};return s.activities.map((act,k)=>({title:act.title,skill:s.kind,questions:Array.from({length:n},(_,index)=>{const d=r(2,9),e=s.same?d:d===9?8:d+1;let a=[r(1,d-1),d],b=[r(1,e-1),e];if(s.kind==='mixed')a[0]+=d*r(1,3);if(s.kind==='whole-left')a=[r(2,8),1];if(s.kind==='whole-right'||id==='6-1-1')b=[r(2,6),1];if(s.op==='−'&&a[0]*b[1]<b[0]*a[1])[a,b]=[b,a];const result=op(a,b,s.op),asset=art.take(x=>['음식','동물과 자연','놀이와 운동'].includes(x.category));let prompt,task,answer,reason,visual='<span class="picture-badge">'+KoArt.icon(asset)+'</span>';
if(k===0){prompt='必要に応じて通分や約分をして計算しましょう。';task='<div class="kequation">'+html(a)+' '+s.op+' '+html(b)+' = □</div><div class="calculation-space"></div>';answer=fmt(result);reason=fmt(a)+' '+s.op+' '+fmt(b)+' = '+fmt(result)}
if(k===1){prompt='□に入る数を求め、式に入れて確かめましょう。';task='<div class="kequation">□ '+s.op+' '+html(b)+' = '+html(result)+'</div><div class="calculation-space"></div>';answer=fmt(a);reason='確かめ：'+fmt(a)+' '+s.op+' '+fmt(b)+' = '+fmt(result)}
if(k===2){const va=fmt(a),vb=fmt(b);if(s.op==='+'){prompt='リボンを'+va+' m使い、'+vb+' m残りました。初めの長さは何mですか。';answer=fmt(result)+' m';reason='初めの長さ = 使った長さ + 残りの長さ'}if(s.op==='−'){prompt='水'+va+' Lの一部を使うと、'+vb+' L残りました。使った量は何Lですか。';answer=fmt(result)+' L';reason='使った量 = 初めの量 − 残りの量'}if(s.op==='×'){prompt='ひも1mの重さは'+va+' gです。このひも'+vb+' mの重さは何gですか。';answer=fmt(result)+' g';reason='1mの重さに長さをかけます。'}if(s.op==='÷'){prompt='ひも'+va+' mを'+(b[1]===1?vb+'人で等しく分けます。一人分は何mですか。':vb+' mをもとにすると何倍ですか。');answer=fmt(result)+(b[1]===1?' m':'倍');reason='全体の長さを'+(b[1]===1?'人数':'もとにする長さ')+'でわります。'}const variant=index%4;if(s.op==='−'){prompt=[prompt,'ひもが'+va+' mありました。'+vb+' mを切りました。残りは何mですか。','きのう'+va+' km、今日'+vb+' km歩きました。きのうは今日より何km多く歩きましたか。','小麦粉を'+vb+' kg加えると全部で'+va+' kgになりました。初めは何kgありましたか。'][variant];answer=fmt(result)+[' L',' m',' km',' kg'][variant];reason=['使った量 = 初めの量 − 残りの量','残りの長さ = 初めの長さ − 切った長さ','ちがい = きのうの道のり − 今日の道のり','初めの量 = 加えた後の量 − 加えた量'][variant]}if(s.op==='+'){prompt=[prompt,'箱の中の材料が'+va+' kgで、空の箱は'+vb+' kgです。材料が入った箱の重さは何kgですか。','午前に'+va+' km、午後に'+vb+' km歩きました。一日に歩いた道のりは何kmですか。','一つ目のびんには'+va+' L入っています。二つ目はそれより'+vb+' L多く入っています。二つ目には何L入っていますか。'][variant];answer=fmt(result)+[' m',' kg',' km',' L'][variant];reason=['初めの長さ = 使った長さ + 残りの長さ','全体の重さ = 材料の重さ + 空の箱の重さ','全体の道のり = 午前の道のり + 午後の道のり','二つ目の量 = 一つ目の量 + 多い分'][variant]}task='式：__________________<div class="calculation-space"></div>答え：__________________'}
return {methodId:s.kind+'-'+s.op+'-'+k,artId:asset.id,prompt,visual,task,answer,reason,check:{kind:'fraction-target',a,b,result,op:s.op}};})}));}
root.JaFractionTargets={banks,generate};
})(globalThis);
