(function(root){const banks={};let excluded=[];
const add=(id,name,type,data)=>{(banks[id]??=[]).push({name,type,...data,activities:[{title:'表し方を変える'},{title:'関係を使う'},{title:'場面に合わせて考える'}]})};
for(const [id,large,small,factor] of [['2-2-3','m','cm',100],['3-1-5','cm','mm',10],['3-1-5','km','m',1000],['3-2-4','L','mL',1000],['3-2-4','kg','g',1000],['5-1-6','m²','cm²',10000],['6-1-6','m³','cm³',1000000]])add(id,large+'と'+small+'・単位を変えて比べる','measure',{large,small,factor});
add('1-2-3','時計の針をかく・何時と何時半','clock',{step:30});add('2-2-4','時計の針をかく・5分ごと','clock',{step:5});add('3-1-5','始め・終わり・かかった時間','duration',{});
function clock(h,m,blank){let face='<circle cx="70" cy="70" r="57" fill="#fffaf0" stroke="#739792" stroke-width="2"/>';for(let i=1;i<=12;i++){let a=i*Math.PI/6;face+='<text x="'+(70+46*Math.sin(a))+'" y="'+(74-46*Math.cos(a))+'" text-anchor="middle" font-size="11">'+i+'</text>'}if(!blank){for(const [angle,len,width] of [[(h%12+m/60)*Math.PI/6,29,3],[m*Math.PI/30,42,2]])face+='<path d="M70 70L'+(70+len*Math.sin(angle))+' '+(70-len*Math.cos(angle))+'" stroke="#294552" stroke-width="'+width+'"/>'}return '<svg class="learning-clock" viewBox="0 0 140 140">'+face+'<circle cx="70" cy="70" r="2" fill="#294552"/></svg>'}
function generate(id,p,seed,n=8){const s=banks[id][p],art=KoArt.session(seed,excluded);let state=seed>>>0;const r=(a,b)=>{state=(Math.imul(state,1664525)+1013904223)>>>0;return a+Math.floor(state/4294967296*(b-a+1))},fmt=t=>Math.floor(t/60)+'時'+(t%60)+'分';return s.activities.map((activity,k)=>({title:activity.title,skill:s.type,questions:Array.from({length:n},()=>{const asset=art.take();let prompt,visual='<span class="picture-badge">'+KoArt.icon(asset)+'</span>',task='________________________',answer,reason,check;
if(s.type==='measure'){const a=r(1,8),b=r(1,9)*(s.factor/10),total=a*s.factor+b;if(k===0){prompt='二つの単位を、一つの単位で表しましょう。';task=a+s.large+' '+b+s.small+' = □ '+s.small;answer=total+s.small;reason='1'+s.large+' = '+s.factor+s.small+'なので'+a*s.factor+' + '+b+'です。'}if(k===1){prompt='□に数を書いて、単位を変えましょう。';task=total+s.small+' = □ '+s.large+' □ '+s.small;answer=a+s.large+' '+b+s.small;reason=s.factor+s.small+'ずつ'+a+'まとまりを作ると、'+b+s.small+'が残ります。'}if(k===2){const c=r(1,9)*s.factor/10,other=a*s.factor+c;prompt='同じ単位に直して比べましょう。□に >、=、< のどれかを書きましょう。';task=a+s.large+' '+b+s.small+' □ '+other+s.small;answer=total===other?'=':total>other?'>':'<';reason=total+s.small+'と'+other+s.small+'を比べます。'}check={kind:'measurement',factor:s.factor,a,b,total}}
if(s.type==='clock'){const h=r(1,11),m=r(0,60/s.step-1)*s.step;visual+=clock(h,m,k!==1);if(k===0){prompt=h+'時'+(m===30?'半':m+'分')+'を長い針と短い針で表しましょう。';task='<div class="kshort-space"></div>';answer=h+'時'+m+'分';reason='長い針は'+(m===0?12:m/5)+'、短い針は'+(m===0?h:h+'と'+(h+1)+'の間')+'を指します。'}if(k===1){prompt='時こくを読んで、30分後の時こくも求めましょう。';task='今：__________<br>30分後：__________';answer=fmt(h*60+m)+' / '+fmt(h*60+m+30);reason='60分になると1時間に直します。'}if(k===2){prompt='長い針が'+(m===0?12:m/5)+'を指し、短い針は'+(m===0?h:h+'と'+(h+1)+'の間')+'にあります。時こくを書いて針をかきましょう。';task='時こく：__________________';answer=fmt(h*60+m);reason='時計の大きな目もり一つ分は5分です。'}}
if(s.type==='duration'){const start=r(8,10)*60+r(0,5)*10,duration=r(2,7)*10,end=start+duration;if(k===0){prompt=fmt(start)+'に出発して'+fmt(end)+'に着きました。何分かかりましたか。';answer=duration+'分';reason=end+'分 − '+start+'分 = '+duration+'分'}if(k===1){prompt=fmt(end)+'に着きました。移動に'+duration+'分かかったとすると、何時何分に出発しましたか。';answer=fmt(start);reason='着いた時こくから、かかった時間をひきます。'}if(k===2){prompt=fmt(start)+'から'+duration+'分間練習しました。練習が終わった時こくはいつですか。';answer=fmt(end);reason='始めの時こくに、かかった時間をたします。'}task='式や時間の図：__________________<div class="calculation-space"></div>答え：__________________';check={kind:'duration',start,duration,end}}
return {methodId:s.type+'-'+k,artId:asset.id,prompt,visual,task,answer,reason,check};})}));}
root.JaMeasurementTargets={banks,generate,excludeArt:ids=>{excluded=ids}};
})(globalThis);
