(function(root){const banks={};let excluded=[];const add=(id,name,type,titles)=>{(banks[id]??=[]).push({name,type,activities:titles.map(title=>({title}))})};
add('5-2-6','平均から分からない値を求める','average',['合計を求める','□の値を求める','資料が増えたときの平均']);add('5-2-6','人数が異なるグループの比較','compare-average',['平均で比べる','同じ平均にする','説明を確かめる']);
add('6-1-4','もとにする量と割合','rate',['比べる量ともとにする量','百分率で表す','場面から割合を考える']);add('6-2-4','比を使って分ける','share',['全体を二つに分ける','一方の量から全体を求める','条件を確かめる']);
add('5-1-6','面積から長さを求める','area-inverse',['長方形の横','三角形の高さ','平行四辺形の底辺']);add('6-2-5','円の半径と円周','circle-inverse',['円周から直径を求める','面積から半径を求める','二つの円の大きさを比べる']);
const gcd=(a,b)=>b?gcd(b,a%b):a;
function generate(id,p,seed,n=8){const s=banks[id][p],art=KoArt.session(seed,excluded);let state=seed>>>0;const r=(a,b)=>{state=(Math.imul(state,1664525)+1013904223)>>>0;return a+Math.floor(state/4294967296*(b-a+1))};return s.activities.map((act,k)=>({title:act.title,skill:s.type,questions:Array.from({length:n},(_,index)=>{const asset=art.take(x=>['음식','동물과 자연','놀이와 운동'].includes(x.category));let a=r(2,6),b=r(2,5),c=r(2,8),prompt,answer,reason,check;const task='式：__________________<div class="calculation-space"></div>答え：__________________';
if(s.type==='average'){const mean=r(5,15),count=4,total=mean*count,known=[mean-2,mean+1,mean-1],missing=mean+2;if(k===0){prompt='四人が集めた'+['カード','シール','玉','どんぐり'][index%4]+'の数の平均は'+mean+'個です。全部で何個集めましたか。';answer=total+'個';reason='平均 × 資料の数 = '+mean+' × 4'}if(k===1){prompt='四つの資料'+known.join(', ')+', □の平均が'+mean+'です。□を求めましょう。';answer=String(missing);reason='合計'+total+'から分かっている三つの数の合計'+known.reduce((x,y)=>x+y,0)+'をひきます。'}if(k===2){const added=mean+5;prompt='四人の平均は'+mean+'個でした。'+added+'個持った人が一人加わりました。五人の新しい平均は何個ですか。';answer=(mean+1)+'個';reason='('+total+' + '+added+') ÷ 5 = '+(mean+1)}check={kind:'average-target',mean,total,known,missing}}
if(s.type==='compare-average'){const ma=r(5,12),mb=ma+r(1,3),na=5,nb=3;if(k===0){prompt='アのグループ五人は全部で'+ma*na+'個、イのグループ三人は全部で'+mb*nb+'個集めました。一人当たりの平均が大きいのはどちらですか。';answer='イのグループ';reason='ア：'+ma+'個、イ：'+mb+'個となります。人数でわって比べます。'}if(k===1){prompt='アのグループの平均は'+ma+'個です。イのグループ三人の平均も同じになるには、合計何個必要ですか。';answer=ma*3+'個';reason='平均 '+ma+' × 3人'}if(k===2){prompt='アのグループ五人は全部で'+ma*5+'個、イのグループ三人は全部で'+ma*3+'個集めました。「合計が多いアの方が平均も大きい」は正しいですか。';answer='いいえ。平均はどちらも'+ma+'個です。';reason='合計と人数の両方を考えます。'}}
if(s.type==='rate'){const total=20,part=r(1,9)*2,g=gcd(part,total);if(k===0){prompt='全部で20個のうち'+part+'個が青です。全体に対する青の比を簡単に表しましょう。';answer=part+':20 = '+part/g+':'+20/g;reason='もとにする量は全部の20個です。'}if(k===1){prompt='問題20問のうち'+part+'問正解しました。正解した割合を百分率で表しましょう。';answer=part*5+'%';reason=part+' ÷ 20 × 100'}if(k===2){prompt='アのチームは20回中'+part+'回、イのチームは40回中'+part+'回成功しました。成功した割合が高いのはどちらですか。';answer='アのチーム';reason='ア '+part*5+'%、イ '+part*2.5+'%です。成功回数が同じでも、もとにする量がちがいます。'}}
if(s.type==='share'){const scale=r(2,9),x=a*scale,y=b*scale,total=x+y;if(k===0){prompt=total+'個をアとイに'+a+':'+b+'の比で分けます。それぞれ何個になりますか。';answer='ア '+x+'個、イ '+y+'個';reason='比の数の合計'+(a+b)+'でわり、それぞれの比の数をかけます。'}if(k===1){prompt='アとイがもらった数の比は'+a+':'+b+'です。アが'+x+'個もらったとき、二人の合計は何個ですか。';answer=total+'個';reason='比の1に当たる量は'+x+' ÷ '+a+' = '+scale+'個です。'}if(k===2){prompt=total+'個を'+a+':'+b+'の比で分けるとき、アに'+(x+1)+'個、イに'+(y-1)+'個渡しました。合計が合っていれば比も正しいと言えますか。';answer='いいえ。ア '+x+'個、イ '+y+'個に分けます。';reason='合計だけでなく、二つの量の比も確かめます。'}}
if(s.type==='area-inverse'){if(k===0){prompt='面積が'+a*b+' cm²、縦が'+b+' cmの長方形の横は何cmですか。';answer=a+' cm';reason='横 = 面積 ÷ 縦'}if(k===1){prompt='三角形の面積は'+a*b+' cm²、底辺は'+a+' cmです。高さは何cmですか。';answer=b*2+' cm';reason='高さ = 面積 × 2 ÷ 底辺'}if(k===2){prompt='平行四辺形の面積は'+a*b+' cm²、高さは'+b+' cmです。底辺の長さを求めましょう。';answer=a+' cm';reason='底辺 = 面積 ÷ 高さ'}}
if(s.type==='circle-inverse'){if(k===0){prompt='円周が'+(6.28*a).toFixed(2)+' cmです。直径を求めましょう。（円周率3.14）';answer=2*a+' cm';reason='直径 = 円周 ÷ 3.14'}if(k===1){prompt='円の面積は'+(3.14*a*a).toFixed(2)+' cm²です。半径は何cmですか。（円周率3.14）';answer=a+' cm';reason='半径 × 半径 = '+a*a+'なので'+a+' cmです。'}if(k===2){prompt='小さい円の半径は'+a+' cm、大きい円の半径は'+2*a+' cmです。大きい円の面積は小さい円の何倍ですか。';answer='4倍';reason='半径が2倍になると、面積は2 × 2 = 4倍です。'}}
return {methodId:s.type+'-'+k,artId:asset.id,prompt,visual:'<span class="picture-badge">'+KoArt.icon(asset)+'</span>',task,answer,reason,check};})}));}
root.JaReasoningTargets={banks,generate};
})(globalThis);
