const spec=window.SUPPLEMENTAL;let seed=Number(new URLSearchParams(location.search).get('set')||123),show=false;
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function rng(s){return n=>{s=(Math.imul(s,1664525)+1013904223)>>>0;return s%n}}
function svg(body,w=320,h=120){return `<svg viewBox="0 0 ${w} ${h}" xmlns="http://www.w3.org/2000/svg" aria-hidden="true">${body}</svg>`}
function dots(n,x=30){const pts=[[0,0],[-12,-18],[12,18],[-12,18],[12,-18],[0,-18],[0,18]];return pts.slice(0,n).map(([a,b])=>`<circle cx="${x+a}" cy="${40+b}" r="4" fill="#234f54"/>`).join('')}
const names=['circle','triangle','square'];function shape(n,x,y,size=26){return n===0?`<circle cx="${x}" cy="${y}" r="${size}"/>`:n===1?`<path d="M${x},${y-size} L${x+size},${y+size} H${x-size} Z"/>`:`<rect x="${x-size}" y="${y-size}" width="${size*2}" height="${size*2}"/>`}
function roman(n){let s='';for(const[v,t]of [[100,'C'],[90,'XC'],[50,'L'],[40,'XL'],[10,'X'],[9,'IX'],[5,'V'],[4,'IV'],[1,'I']])while(n>=v){s+=t;n-=v}return s}
function questions(){const r=rng(seed),a=[];const q=(prompt,visual,answer)=>a.push({prompt,visual,answer});switch(spec.id){
case 'multiplication-chart':case 'roman-chart':case 'numbers-1-20':case 'fraction-strips':case 'divisibility-rules':return [];
case 'addition-flashcards':for(let i=0;i<12;i++){let x=r(10),y=r(11-x);q('Say the sum.',`<div class="big">${x} + ${y}</div>`,x+y)}break;
case 'domino-addition':for(let i=0;i<12;i++){let x=r(7),y=r(7);q('Count the dots. Add.',svg(`<rect x="4" y="4" width="112" height="72" rx="8" fill="white" stroke="#23635d" stroke-width="2"/><path d="M60 4V76" stroke="#23635d"/>${dots(x)}${dots(y,88)}`,120,80)+`<p class="equation">${x} + ${y} = <span class="blank"></span></p>`,x+y)}break;
case 'venn-sorting':for(let i=0;i<4;i++){let nums=Array.from({length:6},(_,j)=>j+1+i*3),left=nums.filter(n=>n%2===0&&n<=10),both=nums.filter(n=>n%2===0&&n>10),right=nums.filter(n=>n%2!==0&&n>10),outside=nums.filter(n=>n%2!==0&&n<=10);q('Sort these numbers: '+nums.join(', '),svg('<text x="15" y="16">Even numbers</text><text x="200" y="16">Greater than 10</text><g fill="none" stroke="#538d87" stroke-width="2"><circle cx="118" cy="93" r="66"/><circle cx="210" cy="93" r="66"/></g><text x="8" y="178">Outside both: __________</text>',330,190),`Left only: ${left.join(', ')||'none'}; both: ${both.join(', ')||'none'}; right only: ${right.join(', ')||'none'}; outside: ${outside.join(', ')||'none'}`)}break;
case 'exit-ticket':for(let i=0;i<4;i++){let x=1+r(8),y=1+r(10-x);q('Name: __________  Date: ______',`<p>1. ${x} + ${y} = <span class="blank"></span></p><p>2. ${x+y} − ${y} = <span class="blank"></span></p><p>3. Show one answer with a drawing.</p><div class="work"></div>`,`1. ${x+y}; 2. ${x}; 3. A drawing showing ${x} and ${y} combining to ${x+y}, or ${y} removed to leave ${x}.`)}break;
case 'shape-tracing':for(let i=0;i<6;i++){let n=i%3;q('Trace the '+names[n]+'. Draw another beside it.',svg('<g fill="none" stroke="#557f7b" stroke-width="2" stroke-dasharray="5 5">'+shape(n,75,55,35)+'</g><path d="M170 100H310" stroke="#a6c0bc"/>',320,115),'Trace the outline and draw a '+names[n]+'. Size and position may vary.')}break;
case 'shape-matching':for(let i=0;i<4;i++){let order=[(i+1)%3,(i+2)%3,i%3];q('Draw a line from each shape to its matching shape.',svg('<g fill="#f4cd76" stroke="#416c69">'+[0,1,2].map((n,j)=>shape(n,55,40+j*65,19)).join('')+order.map((n,j)=>shape(n,255,40+j*65,19)).join('')+'</g><g font-size="15">'+order.map((_,j)=>`<text x="285" y="${45+j*65}">${'ABC'[j]}</text>`).join('')+'</g>',320,210),names.map((n,j)=>n+': '+ 'ABC'[order.indexOf(j)]).join('; '))}break;
case 'counting-to-100':{const missing=new Set();while(missing.size<20)missing.add(1+r(100));q('Fill in the missing numbers. Read the completed chart aloud.','<table class="number-chart">'+Array.from({length:10},(_,y)=>'<tr>'+Array.from({length:10},(_,x)=>{let n=y*10+x+1;return `<td>${missing.has(n)?'<span class="missing" data-answer="'+n+'"></span>':n}</td>`}).join('')+'</tr>').join('')+'</table>',[...missing].sort((a,b)=>a-b).join(', '));break;}
case 'positional-words':for(let i=0;i<8;i++){const dirs=['above','below','to the left of','to the right of'];let n=i%4;let xy=[[110,16],[110,106],[38,62],[182,62]][n];q('Where is the star? Circle a word.',svg(`<rect x="80" y="35" width="60" height="54" rx="5" fill="#dceee5" stroke="#347970"/><text x="${xy[0]}" y="${xy[1]+6}" text-anchor="middle" font-size="25" fill="#ab6810">★</text>`,220,130)+'<p>above · below · left · right</p>',dirs[n]+' the box.')}break;
case 'size-comparison':for(let i=0;i<8;i++){let left=r(2)===0,large=i%2===0;q('Circle the '+(large?'larger':'smaller')+' shape.',svg(`<g fill="#dbede5" stroke="#347970">${shape(i%3,70,55,left?38:21)}${shape(i%3,240,55,left?21:38)}</g><text x="65" y="110">A</text><text x="235" y="110">B</text>`,320,125),(left===large?'A':'B'))}break;
}return a.length?a:(typeof extraQuestions==='function'?extraQuestions(spec,seed):a)}
function reference(){switch(spec.id){case 'multiplication-chart':return '<p>Find one factor across the top and the other down the side.</p><table class="times"><tr><th>×</th>'+Array.from({length:13},(_,i)=>'<th>'+i+'</th>').join('')+'</tr>'+Array.from({length:13},(_,a)=>'<tr><th>'+a+'</th>'+Array.from({length:13},(_,b)=>'<td>'+a*b+'</td>').join('')+'</tr>').join('')+'</table>';
case 'roman-chart':return '<p>I = 1 · V = 5 · X = 10 · L = 50 · C = 100</p><div class="roman-grid">'+Array.from({length:100},(_,i)=>'<div><b>'+(i+1)+'</b> '+roman(i+1)+'</div>').join('')+'</div>';
case 'numbers-1-20':return '<p>Read the number and count its dots.</p><div class="number-cards">'+Array.from({length:20},(_,i)=>'<div><b>'+(i+1)+'</b><div class="counters">'+Array.from({length:i+1},()=>'<i></i>').join('')+'</div></div>').join('')+'</div>';
case 'fraction-strips':return '<p>Cut out the equal-length strips. Compare equal parts of the same whole.</p><div class="strips">'+[1,2,3,4,5,6,8,10,12].map(d=>'<div class="strip">'+Array.from({length:d},()=>'<span>'+(d===1?'1':'1/'+d)+'</span>').join('')+'</div>').join('')+'</div>';
case 'divisibility-rules':return '<p>A number is divisible when division leaves no remainder.</p><table class="rules"><tr><th>By</th><th>Check</th><th>Example</th></tr>'+[[2,'Last digit is 0, 2, 4, 6, or 8.','48 ÷ 2 = 24'],[3,'Digit sum is divisible by 3.','123: 1 + 2 + 3 = 6'],[4,'Last two digits form a number divisible by 4.','316: 16 ÷ 4 = 4'],[5,'Last digit is 0 or 5.','75 ÷ 5 = 15'],[6,'The number is divisible by both 2 and 3.','42 is even; 4 + 2 = 6'],[7,'Double the last digit; subtract it from the remaining number. The result is divisible by 7 (including 0). Repeat if needed.','203: 20 − 2 × 3 = 14'],[8,'Last three digits form a number divisible by 8.','1,024: 24 ÷ 8 = 3'],[9,'Digit sum is divisible by 9.','729: 7 + 2 + 9 = 18'],[10,'Last digit is 0.','120 ÷ 10 = 12']].map(row=>'<tr>'+row.map(v=>'<td>'+v+'</td>').join('')+'</tr>').join('')+'</table>';default:return ''}}
function sheet(answer){let qs=questions(),ref=reference();return `<article class="sheet ${esc(spec.id)} ${answer?'answer-sheet':''}"><div class="brand"><img src="/en/assets/brand-logo.svg" alt=""><b>googoodan<span>.com</span></b><small>${ref?'Reference sheet':answer?'Answer key':'Worksheet'}</small></div><header><h1>${esc(spec.title)}</h1><span aria-hidden="true">★</span></header><div class="meta">Name: ____________________ <span>Date: __________</span></div>${ref||'<div class="questions">'+qs.map((q,i)=>'<section class="question"><b class="num">'+(i+1)+'.</b><p>'+esc(q.prompt)+'</p>'+q.visual+(answer?'<p class="answer">'+esc(q.answer)+'</p>':'')+'</section>').join('')+'</div>'}${spec.id==='cut-paste-counting'?'<div class="cutout-numbers">'+[5,2,1,6,3,4].map(n=>'<span>'+n+'</span>').join('')+'</div>':''}<footer>googoodan.com <span>Set ${seed}</span></footer></article>`}
function render(){document.querySelector('#screen').innerHTML=sheet(show);let q=document.querySelector('#print-q').checked,a=document.querySelector('#print-a').checked;document.querySelector('#print-root').innerHTML=(q?sheet(false):'')+(a&&!spec.reference?sheet(true):'');document.querySelector('#print').disabled=!q&&(!a||spec.reference);if(show||a)document.querySelectorAll('.answer-sheet .missing').forEach(e=>{if(e.closest('#screen')&&!show)return;e.textContent=e.dataset.answer;e.style.color='#ba2525'});}
document.querySelector('#questions').onclick=()=>{show=false;render()};document.querySelector('#answers').onclick=()=>{show=true;render()};document.querySelector('#new').onclick=()=>{seed=crypto.getRandomValues(new Uint32Array(1))[0];render()};document.querySelector('#print-q').onchange=document.querySelector('#print-a').onchange=render;document.querySelector('#print').onclick=()=>{render();window.print()};if(spec.reference){document.querySelector('#answers').hidden=true;document.querySelector('#print-a').parentElement.hidden=true;document.querySelector('#new').hidden=true;}render();

window.GDPreparePDF=()=>{const originalSeed=seed,q=document.getElementById('print-q'),a=document.getElementById('print-a'),count=Math.min(20,Math.max(1,Math.floor(Number(document.getElementById('worksheet-copies')?.value)||1)));if(!q.checked&&!a.checked)return false;let pages='';try{for(let i=0;i<count;i++){seed=(originalSeed+i)>>>0;pages+=(q.checked?sheet(false):'')+(a.checked?sheet(true):'')}}finally{seed=originalSeed}document.getElementById('print-root').innerHTML=pages;return true;};