(function(root){const base=root.KoMath,banks={};let excluded=[];const add=(id,name,type,titles)=>{(banks[id]??=[]).push({name,type,activities:titles.map(title=>({title}))})};
add('5-2-6','평균에서 빠진 자료 찾기','average',['전체 양으로 바꾸어요','빠진 값을 구해요','추가된 자료를 생각해요']);add('5-2-6','자료 수가 다른 두 모둠 비교','compare-average',['평균으로 비교해요','같은 평균을 만들어요','주장을 확인해요']);
add('6-1-4','기준량이 달라지면 비율은?','rate',['비교하는 양과 기준량','백분율로 표현하기','실생활 비율 판단']);add('6-2-4','전체와 부분을 오가는 비례배분','share',['전체를 두 부분으로','한 부분으로 전체 찾기','조건을 만족하는지 검산']);
add('5-1-6','넓이로 도형의 길이 찾기','area-inverse',['직사각형의 가로','삼각형의 높이','평행사변형의 밑변']);add('6-1-6','부피·겉넓이에서 길이 구하기','volume-inverse',['부피로 높이 찾기','겉넓이로 높이 찾기','정육면체의 모서리']);add('6-2-5','원에서 반지름과 둘레 연결','circle-inverse',['둘레로 지름 찾기','넓이로 반지름 찾기','두 원의 크기 비교']);
const gcd=(a,b)=>b?gcd(b,a%b):a;
function generate(id,p,seed,n=8){const offset=base.profiles(id).length;if(!banks[id]||p<offset)return base.generate(id,p,seed,n);const s=banks[id][p-offset],art=KoArt.session(seed,excluded);let state=seed>>>0;const r=(a,b)=>{state=(Math.imul(state,1664525)+1013904223)>>>0;return a+Math.floor(state/4294967296*(b-a+1))};return s.activities.map((act,k)=>({title:act.title,skill:s.type,questions:Array.from({length:n},(_,index)=>{const asset=art.take(x=>['음식','동물과 자연','놀이와 운동'].includes(x.category));let a=r(2,6),b=r(2,5),c=r(2,8),prompt,answer,reason,check;const task='식: __________________<div class="calculation-space"></div>답: __________________';
if(s.type==='average'){const mean=r(5,15),count=4,total=mean*count,known=[mean-2,mean+1,mean-1],missing=mean+2;if(k===0){prompt='네 사람이 모은 '+['카드','스티커','구슬','도토리'][index%4]+' 수의 평균은 '+mean+'개입니다. 모두 몇 개를 모았나요?';answer=total+'개';reason='평균 × 자료 수 = '+mean+' × 4'}if(k===1){prompt='네 자료 '+known.join(', ')+', □의 평균이 '+mean+'입니다. □를 구하세요.';answer=String(missing);reason='전체 합 '+total+'에서 알려진 세 수의 합 '+known.reduce((x,y)=>x+y,0)+'을 뺍니다.'}if(k===2){const added=mean+5;prompt='네 사람의 평균은 '+mean+'개였습니다. '+added+'개를 가진 한 사람이 더 왔습니다. 다섯 사람의 새 평균은 몇 개인가요?';answer=(mean+1)+'개';reason='('+total+' + '+added+') ÷ 5 = '+(mean+1)}check={kind:'average-target',mean,total,known,missing}}
if(s.type==='compare-average'){const ma=r(5,12),mb=ma+r(1,3),na=5,nb=3;if(k===0){prompt='가 모둠 5명은 모두 '+ma*na+'개, 나 모둠 3명은 모두 '+mb*nb+'개를 모았습니다. 한 사람당 평균이 더 큰 모둠은 어디인가요?';answer='나 모둠';reason='가: '+ma+'개, 나: '+mb+'개로 자료 수를 나누어 비교합니다.'}if(k===1){prompt='가 모둠의 평균은 '+ma+'개입니다. 나 모둠 3명의 평균도 같아지려면 나 모둠의 전체 개수는 몇 개여야 하나요?';answer=ma*3+'개';reason='평균 '+ma+' × 3명'}if(k===2){prompt='가 모둠 5명은 모두 '+ma*5+'개, 나 모둠 3명은 모두 '+ma*3+'개를 모았습니다. “전체 개수가 많은 가 모둠의 평균이 더 크다.”는 말이 맞나요?';answer='아니요. 평균은 둘 다 '+ma+'개입니다.';reason='전체 개수와 자료 수를 함께 비교해야 합니다.'}}
if(s.type==='rate'){const total=20,part=r(1,9)*2,g=gcd(part,total);if(k===0){prompt='전체 20개 중 '+part+'개가 파란색입니다. 전체에 대한 파란색의 비를 쓰고 가장 간단하게 나타내세요.';answer=part+':20 = '+part/g+':'+20/g;reason='기준량은 전체 20개입니다.'}if(k===1){prompt='문제 20개 중 '+part+'개를 맞혔습니다. 맞힌 비율을 백분율로 나타내세요.';answer=part*5+'%';reason=part+' ÷ 20 × 100'}if(k===2){prompt='가 팀은 20번 중 '+part+'번 성공했습니다. 나 팀은 40번 중 '+part+'번 성공했습니다. 성공률이 더 높은 팀은 어디인가요?';answer='가 팀';reason='가 '+part*5+'%, 나 '+part*2.5+'%입니다. 성공 횟수가 같아도 기준량이 다릅니다.'}}
if(s.type==='share'){const scale=r(2,9),x=a*scale,y=b*scale,total=x+y;if(k===0){prompt=total+'개를 가와 나에게 '+a+':'+b+'로 나누어 줍니다. 각각 몇 개를 받나요?';answer='가 '+x+'개, 나 '+y+'개';reason='전체 비의 합 '+(a+b)+'으로 나누고 각 비를 곱합니다.'}if(k===1){prompt='가와 나가 받은 개수의 비는 '+a+':'+b+'입니다. 가가 '+x+'개를 받았다면 두 사람이 받은 전체는 몇 개인가요?';answer=total+'개';reason='비의 1에 해당하는 양은 '+x+' ÷ '+a+' = '+scale+'개입니다.'}if(k===2){prompt=total+'개를 '+a+':'+b+'로 나누는데 가에게 '+(x+1)+'개, 나에게 '+(y-1)+'개를 주었습니다. 전체가 맞으니 비도 맞다는 말이 옳나요?';answer='아니요. 가 '+x+'개, 나 '+y+'개로 나눕니다.';reason='합뿐 아니라 두 양의 비도 함께 만족해야 합니다.'}}
if(s.type==='area-inverse'){if(k===0){prompt='넓이가 '+a*b+' cm², 세로가 '+b+' cm인 직사각형의 가로는 몇 cm인가요?';answer=a+' cm';reason='가로 = 넓이 ÷ 세로'}if(k===1){prompt='삼각형의 넓이는 '+a*b+' cm²이고 밑변은 '+a+' cm입니다. 높이는 몇 cm인가요?';answer=b*2+' cm';reason='높이 = 넓이 × 2 ÷ 밑변'}if(k===2){prompt='평행사변형의 넓이는 '+a*b+' cm², 높이는 '+b+' cm입니다. 밑변의 길이를 구하세요.';answer=a+' cm';reason='밑변 = 넓이 ÷ 높이'}}
if(s.type==='volume-inverse'){if(k===0){prompt='직육면체의 가로는 '+a+' cm, 세로는 '+b+' cm, 부피는 '+a*b*c+' cm³입니다. 높이는 몇 cm인가요?';answer=c+' cm';reason='높이 = 부피 ÷ (가로 × 세로)'}if(k===1){const surface=2*(a*b+a*c+b*c);prompt='가로 '+a+' cm, 세로 '+b+' cm인 직육면체의 겉넓이가 '+surface+' cm²입니다. 높이는 몇 cm인가요?';answer=c+' cm';reason='위아래 넓이 '+2*a*b+'를 빼고 밑면 둘레 '+2*(a+b)+'로 나눕니다.'}if(k===2){prompt='정육면체의 겉넓이는 '+6*a*a+' cm²입니다. 모서리의 길이는 몇 cm인가요?';answer=a+' cm';reason='한 면의 넓이 '+a*a+' cm² = '+a+' × '+a+'입니다.'}}
if(s.type==='circle-inverse'){if(k===0){prompt='원의 둘레가 '+(6.28*a).toFixed(2)+' cm입니다. 지름을 구하세요. (원주율 3.14)';answer=2*a+' cm';reason='지름 = 둘레 ÷ 3.14'}if(k===1){prompt='원의 넓이는 '+(3.14*a*a).toFixed(2)+' cm²입니다. 반지름은 몇 cm인가요? (원주율 3.14)';answer=a+' cm';reason='반지름 × 반지름 = '+a*a+'이므로 '+a+' cm입니다.'}if(k===2){prompt='작은 원의 반지름은 '+a+' cm, 큰 원의 반지름은 '+2*a+' cm입니다. 큰 원의 넓이는 작은 원의 몇 배인가요?';answer='4배';reason='반지름을 2배 하면 넓이는 2 × 2 = 4배입니다.'}}
return {methodId:s.type+'-'+k,artId:asset.id,prompt,visual:'<span class="picture-badge">'+KoArt.icon(asset)+'</span>',task,answer,reason,check};})}));}
root.KoMath={...base,profiles:id=>base.profiles(id).concat(banks[id]||[]),generate,excludeArt:ids=>{excluded=ids;base.excludeArt(ids)}};
})(globalThis);
