(()=>{const original=KoMath;const titles=['Find the unknown','Same numbers, different questions','Choose an equation','Identify useful information','Use a bar model','Explain and check'];const singular=(value,one,many=one+'s')=>Number(value)===1?one:many;
KoMath={...original,profiles:id=>original.profiles(id).map((p,i)=>({...p,name:titles[i],goal:'Identify known and unknown quantities',activities:p.activities.map((a,j)=>({...a,title:['Read the story','Use the information','Explain your thinking'][j]}))})),generate(id,p,seed,n){return original.generate(id,p,seed,n).map((section,k)=>({...section,title:['Read the story','Use the information','Explain your thinking'][k],questions:section.questions.map((q,i)=>{const {a,b,sum,difference,method:m}=q.check;const nouns=[['library book','library books'],['baseball card','baseball cards'],['cookie for a bake sale','cookies for a bake sale']][k],noun=value=>singular(value,nouns[0],nouns[1]),total=`Alex has ${a} ${noun(a)}. Maya brings ${b} more. How many are there altogether?`,initial=`After Maya brings ${b} ${noun(b)}, the class has ${a}. How many were there before?`,change=`The class has ${a} ${noun(a)}. After using some, ${b} ${Number(b)===1?'remains':'remain'}. How many were used?`;let prompt=total,answer=`${a} + ${b} = ${sum}`,reason='Add the starting amount and the amount received.',task='Equation: ____________________<br>Answer: ____________________';if(['initial','choose-initial','bar-part','claim'].includes(m)){prompt=initial;answer=`${a} − ${b} = ${difference}`;reason='Subtract the amount received from the final total.';}if(['change','choose-change','bar-difference','justify'].includes(m)){prompt=change;answer=`${a} − ${b} = ${difference}`;reason='Subtract the amount left from the starting amount.';}if(m==='change'){prompt=`Alex has ${a} ${singular(a,'cent')} for school supplies. After a purchase, ${b} ${singular(b,'cent')} ${Number(b)===1?'remains':'remain'}. How many cents were spent?`;answer=`${a} − ${b} = ${difference} ${singular(difference,'cent')}`;}if(m==='paired'){prompt='1. '+total+'<br>2. '+initial;answer=`1. ${a} + ${b} = ${sum}; 2. ${a} − ${b} = ${difference}`;reason='The unknown is different in the two stories.';}
if(m==='compare-more')prompt=`Alex has ${a} ${singular(a,'baseball card')}. Maya has ${b} more than Alex. How many does Maya have?`;
if(m==='compare-less'){prompt=`Maya has ${a} ${singular(a,'pencil')}. Alex has ${b} fewer. How many pencils does Alex have?`;answer=`${a} − ${b} = ${difference}`;reason='Subtract the difference from Maya’s amount.';}
if(m.startsWith('choose-'))task=`Choose an equation: ${a} + ${b} or ${a} − ${b}. Then solve.`;
if(m.startsWith('extra-')){const variant=i%3;prompt=(m==='extra-label'?'The classroom is room 8. ':m==='extra-other'?'There are also 6 notebooks. ':'Alex’s sister is 7 years old. ')+(variant===0?total:variant===1?initial:change);answer=`Use ${a} and ${b}: ${a} ${variant===0?'+':'−'} ${b} = ${variant===0?sum:difference}`;task='Useful numbers: ______ and ______<br>Equation: __________________';reason='The extra detail does not help answer the question.';}
if(m==='question'){prompt=`The class has $${a} in bake sale money and earns $${b} more. Write a question about the total and answer it.`;answer=`Example: How much money is there now? $${a} + $${b} = $${sum}`;reason='The question, equation and answer should agree.';task='My question: __________________<br>Equation and answer: __________________';}
if(m==='claim'){prompt+=' A friend says to add because the story says “brings more.” Explain the mistake.';}if(m==='justify')task+='<br>Why? __________________';
return {...q,prompt,answer,reason,task,visual:q.visual.replaceAll('전체','Total')};})}));}};
})();
