(()=>{'use strict';const API='https://googoodan-community.googoodan-community.workers.dev',$=id=>document.getElementById(id);let token=sessionStorage.getItem('gd-admin-session')||'',botToken='',data=[],generation=0;
const today=()=>new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Seoul',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());const shift=(day,n)=>new Date(Date.parse(day)+n*86400000).toISOString().slice(0,10);$('end').value=today();$('start').value=shift(today(),-29);
async function post(path,body){const r=await fetch(API+path,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body),credentials:'omit'});let d;try{d=await r.json()}catch{throw Error('통계 서버 연결을 확인하세요.')}if(!r.ok)throw Error(d.error||'요청을 처리하지 못했습니다.');return d}
function showLogin(){token='';sessionStorage.removeItem('gd-admin-session');$('login').hidden=false;$('dashboard').hidden=true;data=[];$('csv').disabled=true;generation++}
function card(label,value){let el=document.createElement('div');el.className='card';el.textContent=label;let strong=document.createElement('strong');strong.textContent=Number(value||0).toLocaleString('ko-KR');el.append(strong);$('cards').append(el)}
async function load(){const g=++generation;data=[];$('csv').disabled=true;for(const id of ['cards','rows','chart'])$(id).replaceChildren();$('status').textContent='조회 중…';try{const d=await post('/admin/metrics',{adminToken:token,start:$('start').value,end:$('end').value,site:$('site').value});if(g!==generation)return;const totals=Object.fromEntries(d.totals.map(x=>[x.kind,x.count])),now=Object.fromEntries(d.todayCounts.map(x=>[x.kind,x.count]));card('오늘 방문자',now.visit);card('누적 방문자 (일별 합계)',totals.visit);card('오늘 버튼 클릭',(now.print||0)+(now.pdf||0)+(now.print_pdf||0));card('누적 인쇄 클릭',totals.print);card('누적 PDF 클릭',totals.pdf);card('누적 인쇄 / PDF 공용 클릭',totals.print_pdf);const map=new Map;for(let day=$('start').value;day<=$('end').value;day=shift(day,1))map.set(day,{day,visit:0,print:0,pdf:0,print_pdf:0});for(const row of d.rows)if(map.has(row.day))map.get(row.day)[row.kind]=Number(row.count);data=[...map.values()];let max=Math.max(1,...data.map(x=>x.visit));for(const row of data){const bar=document.createElement('div');bar.className='bar';bar.style.height=Math.max(1,row.visit/max*170)+'px';bar.title=row.day+' · '+row.visit+'명';bar.setAttribute('aria-label',bar.title);bar.tabIndex=0;$('chart').append(bar)}for(const row of [...data].reverse()){const tr=document.createElement('tr');for(const key of ['day','visit','print','pdf','print_pdf']){const td=document.createElement('td');td.textContent=row[key];tr.append(td)}$('rows').append(tr)}$('summary').textContent='선택 기간 방문자 '+data.reduce((s,x)=>s+x.visit,0).toLocaleString()+'명';$('firstDay').textContent=d.firstDay?'집계 시작일: '+d.firstDay:'아직 수집된 기록이 없습니다.';$('status').textContent='조회 완료 · 한국 시간 기준';$('csv').disabled=false}catch(e){if(g===generation)$('status').textContent=e.message}}
$('filters').onsubmit=e=>{e.preventDefault();load()};$('logout').onclick=()=>{showLogin();$('status').textContent='로그아웃했습니다.'};$('loginForm').onsubmit=async e=>{e.preventDefault();if(!botToken){$('status').textContent='자동입력 방지 확인을 완료하세요.';return}try{const d=await post('/admin/login',{password:$('password').value,token:botToken});token=d.adminToken;sessionStorage.setItem('gd-admin-session',token);$('password').value='';$('login').hidden=true;$('dashboard').hidden=false;await load()}catch(e){$('status').textContent=e.message}finally{botToken='';if(window.turnstile)window.turnstile.reset()}};
$('csv').onclick=()=>{if(!data.length)return;const text='\ufeff날짜,방문자,인쇄 클릭,PDF 클릭,공용 클릭\r\n'+data.map(x=>[x.day,x.visit,x.print,x.pdf,x.print_pdf].join(',')).join('\r\n');const u=URL.createObjectURL(new Blob([text],{type:'text/csv;charset=utf-8'})),a=document.createElement('a');a.href=u;a.download='googoodan-'+$('start').value+'-'+$('end').value+'.csv';a.click();setTimeout(()=>URL.revokeObjectURL(u),1000)};
if(['127.0.0.1','localhost'].includes(location.hostname)){
 $('login').hidden=true;$('dashboard').hidden=false;
 $('status').textContent='로컬 관리자 미리보기 · 실제 통계 수집 및 운영 서버 연결 전입니다.';
 for(const label of ['오늘 방문자','누적 방문자 (일별 합계)','오늘 버튼 클릭','누적 인쇄 클릭','누적 PDF 클릭','누적 인쇄 / PDF 공용 클릭']){card(label,0);$('cards').lastElementChild.querySelector('strong').textContent='—'}
 $('summary').textContent='날짜별 방문자';$('firstDay').textContent='연결 후 날짜별 방문자와 클릭 횟수가 표시됩니다. 현재 실제 데이터는 없습니다.';
 $('chart').textContent='방문 기록 수집 대기 중';$('chart').style.alignItems='center';
 for(const element of $('filters').elements)element.disabled=true;
 $('logout').hidden=true;return;
}
const script=document.createElement('script');script.src='https://challenges.cloudflare.com/turnstile/v0/api.js?render=explicit';script.onload=()=>window.turnstile.render('#bot',{sitekey:'0x4AAAAAAErjOzd5LPDgqlmm',action:'board-write',callback:t=>botToken=t,'expired-callback':()=>botToken=''});script.onerror=()=>{$('status').textContent='로그인 보안 확인을 불러올 수 없습니다.'};document.head.append(script);
fetch(API+'/metrics/status').then(r=>{if(!r.ok)throw Error();$('status').textContent='관리자 계정으로 로그인하세요.';if(token){$('login').hidden=true;$('dashboard').hidden=false;load()}}).catch(()=>{$('status').textContent='관리자 화면은 준비됐습니다. 새 통계 서버 연결 전이므로 실제 집계는 아직 표시되지 않습니다.'});})();