(() => {
 'use strict';
 const local=['localhost','127.0.0.1'].includes(location.hostname),api=local?'http://127.0.0.1:4208':'https://googoodan-community.googoodan-community.workers.dev';
 const el=(tag,text)=>{const n=document.createElement(tag);if(text!==undefined)n.textContent=text;return n;};
 const host=document.querySelector('#dashboard')||document.querySelector('main')||document.body;
 const section=el('section');section.id='private-feedback-inbox';section.append(el('h2','비공개 접수함 · 한국 / 미국'));
 const status=el('p','오류 신고, 문제지 요청, 질문을 관리자만 확인합니다.');status.setAttribute('role','status');section.append(status);
 if(local){const label=el('label','로컬 관리자 암호 '),input=el('input');input.type='password';input.autocomplete='current-password';label.append(input);const login=el('button','접수함 로그인');login.onclick=async()=>{try{const r=await fetch(api+'/local-admin/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({password:input.value})});const d=await r.json();if(!r.ok)throw Error(d.error);sessionStorage.setItem('feedback-local-session',d.token);input.value='';await load(false);}catch(e){status.textContent=e.message;}};section.append(label,login);}
 const filter=el('select');for(const [v,t]of [['all','전체 사이트'],['ko','한국 사이트'],['us','미국 사이트']]){const o=el('option',t);o.value=v;filter.append(o);}const refresh=el('button','새로고침');refresh.onclick=()=>load(false);section.append(filter,refresh);
 const list=el('div');section.append(list);const more=el('button','더 보기');more.hidden=true;section.append(more);host.prepend(section);
 let cursor=null,items=[];
 const token=()=>sessionStorage.getItem(local?'feedback-local-session':'gd-admin-session')||'';
 async function request(path,body){const r=await fetch(api+path,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...body,adminToken:token()})});const d=await r.json();if(!r.ok)throw Error(d.error||'접수함을 불러오지 못했습니다.');return d;}
 function render(){list.replaceChildren();for(const row of items.filter(x=>filter.value==='all'||x.site===filter.value)){const card=el('article');card.style.cssText='border-top:1px solid #c9ded4;padding:15px 0';card.append(el('h3',(row.site==='ko'?'한국':'미국')+' · '+({error:'오류 신고',request:'문제지 요청',other:'질문·기타'}[row.category])+' · '+row.subject));card.append(el('small',new Date(row.created_at).toLocaleString('ko-KR')+' · 메일: '+({sent:'발송 완료',failed:'발송 실패',pending:'대기', 'not-configured':'발송 설정 전'}[row.mail_status]||row.mail_status)));const msg=el('p',row.message);msg.style.whiteSpace='pre-wrap';card.append(msg);if(row.email){const a=el('a',row.email);a.href='mailto:'+encodeURIComponent(row.email);card.append(a);}if(row.worksheet_url){const p=el('p'),a=el('a','해당 문제지 열기');a.href=row.worksheet_url;a.target='_blank';a.rel='noopener noreferrer';p.append(a);card.append(p);}const select=el('select');for(const [value,label]of [['new','신규'],['in-progress','확인 중'],['closed','처리 완료']]){const o=el('option',label);o.value=value;select.append(o);}select.value=row.status;select.onchange=async()=>{try{await request('/admin/feedback/status',{id:row.id,status:select.value});row.status=select.value;}catch(e){status.textContent=e.message;select.value=row.status;}};card.append(select);list.append(card);}if(!list.children.length)list.append(el('p','접수된 내용이 없습니다.'));}
 async function load(append){try{const d=await request('/admin/feedback',append&&cursor?cursor:{});items=append?items.concat(d.items):d.items;cursor=d.next;more.hidden=!cursor;status.textContent=d.mailConfigured?'관리자 전용 접수함 · 이메일 알림 연결됨':'관리자 전용 접수함 · 이메일 알림은 발송 서비스 설정 후 작동합니다.';render();}catch(e){items=[];list.replaceChildren();more.hidden=true;status.textContent=e.message;}}
 document.getElementById('logout')?.addEventListener('click',()=>{items=[];list.replaceChildren();status.textContent='관리자 로그인이 필요합니다.';}); new MutationObserver(()=>{if(!host.hidden&&token())load(false);}).observe(host,{attributes:true,attributeFilter:['hidden']}); filter.onchange=render;more.onclick=()=>load(true);if(token())load(false);
})();
