(()=>{
const unit=document.documentElement.dataset.sourceUnit,grade=document.documentElement.dataset.koGrade,title=document.documentElement.dataset.koTitle;
const u=new URL(location.href);u.searchParams.set('grade','4');u.searchParams.set('unit',unit);history.replaceState(null,'',u);document.documentElement.lang='ko';
const dict={'Calculate.':'계산하세요.','Complete the equivalent fraction.':'크기가 같은 분수가 되도록 빈칸을 채우세요.','Write the number in expanded form.':'각 자리의 수로 나누어 나타내세요.','Name:':'이름:','Date: ______________':'날짜: ______________','ANSWER KEY':'정답','MATH JOURNAL':'수학 문제지','Answer: ':'정답: ','Example / check: ':'예시 / 확인: ','My reflection: What strategy helped me today?':'어떤 방법으로 풀었나요?','Observe. Connect. Explain.':'생각하며 문제를 풀어 보세요.','My check: __________________':'확인: __________________','degrees':'도',' degrees':' 도','Worksheet':'문제지','Answer key':'정답지','Print ↗':'인쇄 ↗','↻ New problems':'새 문제','NATURE RESEARCH LAB':'수학 학습','Nature Research Lab':'수학 학습'};
const place={'ones':'일','tens':'십','hundreds':'백','thousands':'천','ten-thousands':'만','hundred-thousands':'십만'};
function tr(t){if(dict[t])return dict[t];return t.replace(/Two adjacent angles measure (\d+)° and (\d+)°\. Find their combined angle\./g,'$1°와 $2°의 합을 구하세요.').replace(/A (\d+)° angle is split into (\d+)° and an unknown angle\. Find the unknown\./g,'$1°에서 $2°를 뺀 각도를 구하세요.').replace(/What digit is in the ([a-z-]+) place\?/g,(_,p)=>`${place[p]||p}의 자리 숫자는 무엇인가요?`).replace(/What is the value of the digit in the ([a-z-]+) place\?/g,(_,p)=>`${place[p]||p}의 자리 숫자가 나타내는 수는 얼마인가요?`).replace(/Start at (\d+)\. Add (\d+) each time\./g,'$1부터 $2씩 커지는 규칙을 완성하세요.').replace(/A rectangle is (\d+) units long and (\d+) units wide\. Find (area|perimeter)\./g,(_,a,b,c)=>`가로 ${a}, 세로 ${b}인 직사각형의 ${c==='area'?'넓이':'둘레'}를 구하세요. (단위 길이)`).replace(/GRADE 4 \/ NATURE RESEARCH LAB/g,`${grade}학년 / 수학 학습`).replace(/Grade 4 Math/g,`${grade}학년 수학`).replace(/Set (\d+)/g,'문제 $1').replace(/\b(angle|place|equivalent|patterns|area-perimeter)\b/g,'학습').replace(/googoodan\.com\/en/g,'googoodan.com');}
function localize(el){const walk=document.createTreeWalker(el,NodeFilter.SHOW_TEXT);let n;while(n=walk.nextNode())n.nodeValue=tr(n.nodeValue);const h=el.querySelector('.hero h2');if(h)h.textContent=title;}
const desc=Object.getOwnPropertyDescriptor(Element.prototype,'innerHTML');Object.defineProperty(Element.prototype,'innerHTML',{...desc,set(value){desc.set.call(this,value);if(this.id==='sheet')localize(this);}});
window.addEventListener('DOMContentLoaded',()=>{for(const id of ['worksheet','answer','new','print']){const e=document.getElementById(id);if(e)localize(e);}document.title=title;});
})();