/* Standalone curriculum drill catalogue. Existing worksheet types remain unchanged. */
(function(root){
const W=Worksheets,units=[],profiles=new Map(),labels={add:'덧셈',sub:'뺄셈',mul:'곱셈',div:'나눗셈'};
function unit(id){const original=KoCatalog.units.find(u=>u.id===id);const u={...original,drills:[]};units.push(u);return u;}
function put(u,source,title,group='기본 연산',mode='basic',layout='horizontal',extra={}){const id=u.id+'--'+u.drills.length;const base=W.types.find(t=>t.id===source)||W.types[0];const p={id,source,title,group,mode,layout,...extra};u.drills.push(p);profiles.set(id,p);W.types.push({...base,id,title,config:base.config?{...base.config}:undefined});return p;}
function natural(u,code,pairs,group='기본 연산',vertical=true){for(const [a,b]of pairs)for(const layout of vertical?['horizontal','vertical']:['horizontal'])put(u,`natural-${code}-${a}-${b}`,`${a}자리 ${code==='add'?'+':code==='sub'?'−':code==='mul'?'×':'÷'} ${b}자리 · ${layout==='vertical'?'세로셈':'가로셈'}`,group,'basic',layout);}
function source(u,id,title,group='기본 연산',vertical=false,extra={}){for(const layout of vertical?['horizontal','vertical']:['horizontal'])put(u,id,title+(vertical?' · '+(layout==='vertical'?'세로셈':'가로셈'):''),group,'basic',layout,extra);}
function skill(u,key,title,group='기초 보충'){put(u,'add-small',title,group,'skill','horizontal',{skill:key});}
function extensions(u){const bases=u.drills.filter(p=>p.group==='기본 연산'&&p.mode==='basic');const byOp=new Map();for(const p of bases){const t=W.types.find(t=>t.id===p.source);const op=t.config?.code||p.source.split('-')[0];if(!byOp.has(op))byOp.set(op,p);}
for(const [op,p] of byOp){put(u,p.source,(labels[op]||'계산')+' · 가로식 빈칸','빈칸 응용','blank','horizontal',{sourceExtra:p});if(u.grade>=2&&bases.some(b=>b.source===p.source&&b.layout==='vertical')&&W.types.find(t=>t.id===p.source)?.family==='Natural numbers')put(u,p.source,(labels[op]||'계산')+' · 세로 숫자 빈칸','빈칸 응용','digit','vertical',{sourceExtra:p});}
const candidates=bases.filter(p=>p.layout==='horizontal');if(candidates.length)put(u,candidates[0].source,'상황을 읽고 알맞은 계산 찾기','문장 연습','story','horizontal',{pool:candidates.map(p=>({source:p.source,extra:p}))});}
function prereq(u,full=false){for(const [k,n]of [['improper','가분수를 대분수로'],['mixed','대분수를 가분수로'],['factor','약수 찾기'],['common-factor','공약수 찾기'],['gcd','최대공약수'],['reduce','약분하기']])skill(u,k,n);if(full)for(const [k,n]of [['multiple','배수 찾기'],['common-multiple','공배수 찾기'],['lcm','최소공배수'],['common','통분하기']])skill(u,k,n);}
for(const [id,max,carry] of [['1-1-3',9,false],['1-2-2',99,false],['1-2-4',10,false],['1-2-6',20,true]]){const u=unit(id);for(const code of ['add','sub'])source(u,code==='add'?'add-small':'subtract-small',labels[code]+' · '+(max===99?'두 자리와 한 자리':max+'까지'), '기본 연산',false,{custom:'early',code,max,carry});skill(u,id==='1-1-3'?'bond9':'bond',id==='1-1-3'?'9까지 가르기·모으기':'10 만들기');source(u,'subtract-small','9까지 뺄셈','기초 보충',false,{custom:'early',code:'sub',max:9});source(u,'add-small','5까지 덧셈','기초 보충',false,{custom:'early',code:'add',max:5});extensions(u);}
{const u=unit('2-1-3');for(const op of ['add','sub']){natural(u,op,[[2,2]]);natural(u,op,[[2,1],[1,1]],'기초 보충');for(const condition of ['no-carry','carry'])for(const layout of ['horizontal','vertical'])put(u,'natural-'+op+'-2-2',labels[op]+' · '+(condition==='carry'?'받아올림·내림 집중':'받아올림·내림 없음')+' · '+(layout==='vertical'?'세로':'가로'),'기본 연산','basic',layout,{condition});}extensions(u);}
{const u=unit('2-1-6');source(u,'multiply-one','몇씩 몇 묶음의 곱셈');skill(u,'repeat','같은 수를 여러 번 더하기','기본 연산');skill(u,'groups','묶음 그림을 곱셈식으로','기본 연산');source(u,'add-small','덧셈 복습','기초 보충');extensions(u);}
function tables(u,group='기초 보충'){for(const ds of [[2],[3],[4],[5],[6],[7],[8],[9],[2,3,4],[4,5,6],[6,7,8,9],[2,3,4,5,6,7,8,9],[0,1]])source(u,'multiply-one',ds.length>4?'구구단 전체':ds.join('·')+'단 익히기',group,false,{tables:ds});}
{const u=unit('2-2-2');tables(u,'기본 연산');skill(u,'repeat','같은 수 덧셈');skill(u,'groups','그림을 곱셈식으로');extensions(u);}
{const u=unit('3-1-1');for(const op of ['add','sub']){natural(u,op,[[3,3]]);for(const layout of ['horizontal','vertical'])put(u,'natural-'+op+'-3-3',labels[op]+' · 받아올림·내림 집중 · '+(layout==='vertical'?'세로':'가로'),'기본 연산','basic',layout,{condition:'carry'});natural(u,op,[[2,2],[3,2]],'기초 보충');}extensions(u);}
{const u=unit('3-1-3');source(u,'divide','구구단 범위의 나눗셈');tables(u);extensions(u);}
for(const [id,mul,div,pm,pd] of [
['3-1-4',[[2,1]],[],[[1,1]],[]],['3-2-1',[[3,1],[2,2]],[],[[2,1],[1,1]],[]],
['3-2-3',[],[[2,1],[3,1]],[[1,1]],[]],['4-1-3',[[3,2]],[[2,2],[3,2]],[[2,2],[3,1]],[[2,1],[3,1]]]]){const u=unit(id);natural(u,'mul',mul);natural(u,'div',div);natural(u,'mul',pm,'기초 보충');natural(u,'div',pd,'기초 보충');tables(u);for(const [a,b]of div)for(const remainder of [false,true])for(const layout of ['horizontal','vertical'])put(u,`natural-div-${a}-${b}`,`${a}자리 ÷ ${b}자리 · ${remainder?'나머지 있음':'나누어떨어짐'} · ${layout==='vertical'?'세로':'가로'}`,'기본 연산','basic',layout,{remainder});extensions(u);}
{const u=unit('4-2-1');for(const op of ['add','sub']){source(u,`fraction-${op}-same`,'같은 분모 · '+labels[op]);for(const pair of [['mixed','mixed'],['whole','proper'],['improper','proper']])source(u,`fraction-${op}-${pair[0]}-${pair[1]}`,'같은 분모 · '+({mixed:'대분수',whole:'자연수',improper:'가분수'}[pair[0]])+' '+labels[op],'기본 연산',false,{same:true});}skill(u,'improper','가분수를 대분수로');skill(u,'mixed','대분수를 가분수로');skill(u,'one-fraction','자연수 1을 분수로');extensions(u);}
function decimals(u,ops,max,division=false){for(const op of ops)for(let a=0;a<=max;a++)for(let b=0;b<=max;b++){if(!a&&!b||division&&b!==0)continue;const id=a===b?`decimal-${op}-${a}`:`decimal-${op}-${a}dp-${b}dp`;if(W.types.some(t=>t.id===id))source(u,id,`${a?'소수 '+a+'자리':'자연수'} ${labels[op]} ${b?'소수 '+b+'자리':'자연수'}`,'기본 연산',true);else if(a===3||b===3)for(const layout of ['horizontal','vertical'])put(u,'decimal-'+op+'-2',`소수 ${a}자리 ${labels[op]} 소수 ${b}자리 · `+(layout==='vertical'?'세로':'가로'),'기본 연산','basic',layout,{decimalPlaces:[a,b],code:op});}skill(u,'decimal-scale','소수점과 10·100배');}
{const u=unit('4-2-3');decimals(u,['add','sub'],3);natural(u,'add',[[2,2]],'기초 보충');natural(u,'sub',[[2,2]],'기초 보충');extensions(u);}
{const u=unit('5-1-1');for(const [k,n]of [['mixed-add','덧셈·뺄셈 혼합'],['mixed-mul','곱셈·나눗셈 혼합'],['mixed-four','사칙 혼합'],['mixed-bracket','괄호가 있는 혼합 계산']])skill(u,k,n,'기본 연산');for(const op of ['add','sub','mul','div'])natural(u,op,[[2,1]],'기초 보충');put(u,'add-small','상황을 읽고 알맞은 계산 찾기','문장 연습','story','horizontal',{pool:[{source:'natural-add-2-2'},{source:'natural-sub-2-2'},{source:'multiply-one'},{source:'divide'}]});}
for(const id of ['5-1-2','5-1-4']){const u=unit(id);for(const [k,n]of [['factor','약수 찾기'],['multiple','배수 찾기'],['common-factor','공약수'],['common-multiple','공배수'],['gcd','최대공약수'],['lcm','최소공배수'],...(id==='5-1-4'?[['reduce','약분'],['common','통분'],['compare-fraction','통분해서 크기 비교']]:[])])skill(u,k,n,(id==='5-1-2'||['reduce','common','compare-fraction'].includes(k))?'기본 연산':'기초 보충');natural(u,'mul',[[1,1]],'기초 보충');source(u,'divide','나누어떨어지는 나눗셈','기초 보충');}
for(const [id,op]of [['5-1-5','add'],['5-2-2','mul'],['6-1-1','div'],['6-2-1','div']]){const u=unit(id),ops=op==='add'?['add','sub']:[op];for(const code of ops){source(u,`fraction-${code}-different`,'진분수 '+labels[code]+' 진분수',id==='6-1-1'?'기초 보충':'기본 연산');for(const a of ['whole','proper','improper','mixed'])for(const b of ['whole','proper','improper','mixed']){if(a==='whole'&&b==='whole'||a==='proper'&&b==='proper'||id==='6-1-1'&&b!=='whole')continue;const src=`fraction-${code}-${a}-${b}`;if(W.types.some(t=>t.id===src)){const names={whole:'자연수',proper:'진분수',improper:'가분수',mixed:'대분수'};source(u,src,names[a]+' '+labels[code]+' '+names[b]);}}}if(id==='6-1-1')u.drills=u.drills.filter(p=>p.source!=='fraction-div-different');prereq(u,['5-1-5','6-2-1'].includes(id));if(id==='5-1-5')for(const c of ['add','sub'])source(u,`fraction-${c}-same`,'같은 분모 '+labels[c],'기초 보충');if(op==='div')source(u,'fraction-mul-different','분수 곱셈 복습','기초 보충');extensions(u);}
{const u=unit('5-2-4');decimals(u,['mul'],2);natural(u,'mul',[[2,1],[2,2]],'기초 보충');extensions(u);}
for(const id of ['6-1-3','6-2-3']){const u=unit(id);decimals(u,['div'],2,id==='6-1-3');natural(u,'div',[[2,1],[3,1]],'기초 보충');source(u,'decimal-mul-1','소수 곱셈 검산','기초 보충');extensions(u);}

// Remedial lists stop at the immediately preceding grade; same-grade earlier concepts remain useful.
function review(u,src,label,learned,layout='horizontal',extra={}){const id=u.id+'--review-'+src+'-'+layout,base=W.types.find(t=>t.id===src);if(!base)throw Error('Unknown review source '+src);const p={id,source:src,title:label,group:'기초 보충',mode:'basic',layout,reviewGrade:learned,...extra};u.drills.push(p);profiles.set(id,p);W.types.push({...base,id,config:base.config?{...base.config}:undefined});}
for(const u of units){if(u.grade<4)continue;
const keep=p=>{if(p.group!=='기초 보충')return true;
if(u.grade===4){if(p.tables||p.source==='natural-mul-1-1')return false;if(u.id==='4-2-3')return false;return true;}
if(u.grade===5){if(p.tables||['improper','mixed'].includes(p.skill))return false;if(p.source.startsWith('natural-')||p.source==='divide')return false;return true;}
if(u.grade===6){if(['improper','mixed'].includes(p.skill)||p.source.startsWith('natural-div-'))return false;return true;}return true;};
u.drills=u.drills.filter(keep);
if(u.id==='4-2-3'){for(const op of ['add','sub'])for(const layout of ['horizontal','vertical'])review(u,'natural-'+op+'-3-3','3학년 복습 · 세 자리 '+labels[op]+' · '+(layout==='vertical'?'세로셈':'가로셈'),3,layout);}
if(['5-1-1','5-1-2','5-1-4','5-2-4'].includes(u.id)){for(const op of ['mul','div']){if(u.id==='5-2-4'&&op==='div')continue;for(const layout of ['horizontal','vertical'])review(u,'natural-'+op+'-3-2','4학년 복습 · 세 자리와 두 자리 '+labels[op]+' · '+(layout==='vertical'?'세로셈':'가로셈'),4,layout);}}
if(u.id==='5-2-2')for(const op of ['add','sub'])review(u,'fraction-'+op+'-same','4학년 복습 · 같은 분모 '+labels[op],4);
if(u.id==='6-1-3'||u.id==='6-2-3'){for(const layout of ['horizontal','vertical'])review(u,'decimal-mul-2','5학년 복습 · 소수 곱셈 · '+(layout==='vertical'?'세로셈':'가로셈'),5,layout);}
for(const p of u.drills.filter(p=>p.group==='기초 보충')){if(!p.reviewGrade)p.reviewGrade=(p.skill&&['factor','multiple','common-factor','common-multiple','gcd','lcm','reduce','common'].includes(p.skill))?5:u.grade-1;}
}

// Read operand-to-operand titles naturally; retain nouns in names such as '분수의 곱셈'.
for(const u of units)for(const p of u.drills){p.title=p.title.replace(/(덧셈|뺄셈|곱셈|나눗셈)(?= (?:자연수|진분수|가분수|대분수|소수))/g,m=>({덧셈:'더하기',뺄셈:'빼기',곱셈:'곱하기',나눗셈:'나누기'}[m]));const t=W.types.find(t=>t.id===p.id);if(t)t.title=p.title;}
const order=['기본 연산','기초 보충','빈칸 응용','문장 연습'];for(const u of units)u.drills.sort((a,b)=>order.indexOf(a.group)-order.indexOf(b.group));
root.DrillCatalog={units:units.sort((a,b)=>a.id.localeCompare(b.id)),profiles};
})(globalThis);
