(function(root){const base=root.KoMath,banks={};let excluded=[];
function add(id,name,op,kind,same=false){(banks[id]??=[]).push({name,op,kind,same,activities:[{title:'수를 연결해 계산해요'},{title:'가려진 수를 찾아요'},{title:'조건에 맞는 식을 써요'}]})}
for(const id of ['4-2-1','5-1-5']){const same=id==='4-2-1';for(const [kind,label] of [['proper','진분수'],['mixed','대분수']])for(const op of ['+','−'])add(id,label+' '+(op==='+'?'덧셈':'뺄셈')+' · '+(same?'같은 분모':'다른 분모'),op,kind,same)}
for(const [kind,label] of [['proper','진분수 × 진분수'],['mixed','대분수 × 진분수'],['whole-left','자연수 × 진분수'],['whole-right','진분수 × 자연수']])add('5-2-2',label,'×',kind);
for(const [kind,label] of [['proper','진분수 ÷ 자연수'],['mixed','대분수 ÷ 자연수'],['whole-left','자연수 ÷ 자연수 · 분수로 나타내기']])add('6-1-1',label,'÷',kind);
for(const [kind,label] of [['proper','진분수 ÷ 진분수'],['mixed','대분수 ÷ 진분수'],['whole-left','자연수 ÷ 진분수']])add('6-2-1',label,'÷',kind);
const gcd=(a,b)=>b?gcd(b,a%b):a,reduce=x=>{const g=gcd(x[0],x[1]);return [x[0]/g,x[1]/g]},fmt=x=>{x=reduce(x);return x[1]===1?String(x[0]):x[0]>x[1]?Math.floor(x[0]/x[1])+' '+x[0]%x[1]+'/'+x[1]:x[0]+'/'+x[1]},html=x=>x[1]===1?String(x[0]):x[0]>x[1]?Math.floor(x[0]/x[1])+' '+(x[0]%x[1]===0?'':html([x[0]%x[1],x[1]])):'<span class="kf"><span>'+x[0]+'</span><span>'+x[1]+'</span></span>',op=(a,b,s)=>reduce(s==='+'?[a[0]*b[1]+b[0]*a[1],a[1]*b[1]]:s==='−'?[a[0]*b[1]-b[0]*a[1],a[1]*b[1]]:s==='×'?[a[0]*b[0],a[1]*b[1]]:[a[0]*b[1],a[1]*b[0]]);
function generate(id,p,seed,n=8){const offset=base.profiles(id).length;if(!banks[id]||p<offset)return base.generate(id,p,seed,n);const s=banks[id][p-offset],art=KoArt.session(seed,excluded);let state=seed>>>0;const r=(a,b)=>{state=(Math.imul(state,1664525)+1013904223)>>>0;return a+Math.floor(state/4294967296*(b-a+1))};return s.activities.map((act,k)=>({title:act.title,skill:s.kind,questions:Array.from({length:n},(_,index)=>{const d=r(2,9),e=s.same?d:d===9?8:d+1;let a=[r(1,d-1),d],b=[r(1,e-1),e];if(s.kind==='mixed')a[0]+=d*r(1,3);if(s.kind==='whole-left')a=[r(2,8),1];if(s.kind==='whole-right'||id==='6-1-1')b=[r(2,6),1];if(s.op==='−'&&a[0]*b[1]<b[0]*a[1])[a,b]=[b,a];const result=op(a,b,s.op),asset=art.take(x=>['음식','동물과 자연','놀이와 운동'].includes(x.category));let prompt,task,answer,reason,visual='<span class="picture-badge">'+KoArt.icon(asset)+'</span>';
if(k===0){prompt='필요하면 통분하거나 약분하여 계산하세요.';task='<div class="kequation">'+html(a)+' '+s.op+' '+html(b)+' = □</div><div class="calculation-space"></div>';answer=fmt(result);reason=fmt(a)+' '+s.op+' '+fmt(b)+' = '+fmt(result)}
if(k===1){prompt='□에 들어갈 수를 구하고 식에 다시 넣어 확인하세요.';task='<div class="kequation">□ '+s.op+' '+html(b)+' = '+html(result)+'</div><div class="calculation-space"></div>';answer=fmt(a);reason='확인: '+fmt(a)+' '+s.op+' '+fmt(b)+' = '+fmt(result)}
if(k===2){const va=fmt(a),vb=fmt(b);if(s.op==='+'){prompt='리본을 '+va+' m 사용하고 '+vb+' m가 남았습니다. 처음 리본의 길이는 몇 m였나요?';answer=fmt(result)+' m';reason='처음 길이 = 사용한 길이 + 남은 길이'}if(s.op==='−'){prompt='물 '+va+' L 중 일부를 사용하니 '+vb+' L가 남았습니다. 사용한 물의 양은 몇 L인가요?';answer=fmt(result)+' L';reason='사용한 양 = 처음 양 − 남은 양'}if(s.op==='×'){prompt='끈 1 m의 무게는 '+va+' g입니다. 이 끈 '+vb+' m의 무게는 몇 g인가요?';answer=fmt(result)+' g';reason='1 m의 무게에 길이를 곱합니다.'}if(s.op==='÷'){prompt='줄 '+va+' m를 '+(b[1]===1?vb+'명이 똑같이 나누어 가집니다. 한 명이 가지는 길이는 몇 m인가요?':vb+' m에 해당하는 양으로 나누어 나타내세요. 몇 배인가요?');answer=fmt(result)+(b[1]===1?' m':'배');reason='전체 길이를 '+(b[1]===1?'사람 수':'기준이 되는 길이')+'로 나눕니다.'}const variant=index%4;if(s.op==='−'){prompt=[prompt,'끈이 '+va+' m 있었습니다. '+vb+' m를 잘라 주었습니다. 남은 길이는 몇 m인가요?','어제 '+va+' km, 오늘 '+vb+' km를 걸었습니다. 어제는 오늘보다 몇 km 더 걸었나요?','밀가루를 '+vb+' kg 더 부으니 모두 '+va+' kg이 되었습니다. 처음 밀가루는 몇 kg이었나요?'][variant];answer=fmt(result)+[' L',' m',' km',' kg'][variant];reason=['사용한 양 = 처음 양 − 남은 양','남은 길이 = 처음 길이 − 잘라 준 길이','차이 = 어제 걸은 거리 − 오늘 걸은 거리','처음 양 = 늘어난 뒤의 양 − 더 부은 양'][variant]}if(s.op==='+'){prompt=[prompt,'상자에 든 재료가 '+va+' kg이고 빈 상자는 '+vb+' kg입니다. 재료가 든 상자의 무게는 모두 몇 kg인가요?','오전에 '+va+' km를 걷고 오후에 '+vb+' km를 걸었습니다. 하루 동안 걸은 거리는 몇 km인가요?','첫째 병에는 '+va+' L가 들어 있습니다. 둘째 병은 그보다 '+vb+' L 더 많습니다. 둘째 병에는 몇 L가 들어 있나요?'][variant];answer=fmt(result)+[' m',' kg',' km',' L'][variant];reason=['처음 길이 = 사용한 길이 + 남은 길이','전체 무게 = 재료 무게 + 빈 상자 무게','전체 거리 = 오전 거리 + 오후 거리','둘째 병의 양 = 첫째 병의 양 + 더 많은 양'][variant]}task='식: __________________<div class="calculation-space"></div>답: __________________'}
return {methodId:s.kind+'-'+s.op+'-'+k,artId:asset.id,prompt,visual,task,answer,reason,check:{kind:'fraction-target',a,b,result,op:s.op}};})}));}
root.KoMath={...base,profiles:id=>base.profiles(id).concat(banks[id]||[]),generate,excludeArt:ids=>{excluded=ids;base.excludeArt(ids)}};
})(globalThis);
