const fs=require('fs'),path=require('path'),vm=require('vm');const root=path.resolve(__dirname,'..'),fr=path.join(root,'fr');const c={Worksheets:{types:[]}};vm.createContext(c);vm.runInContext(fs.readFileSync(path.join(fr,'reuse/drill-catalog.js'),'utf8'),c);
const slug=s=>s.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/&[^;]+;/g,'-').replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'');
const mapping={},idUrls={};for(const u of c.DrillCatalog.units)for(const [index,p]of u.drills.entries()){const old='drill-'+p.id+'.html';if(!/^drill-\d/.test(old)){idUrls[p.id]='/fr/print/'+old;continue;}let s=fs.readFileSync(path.join(fr,'print',old),'utf8'),title=s.match(/<title>(.*?)<\/title>/s)[1].replace(/\s*\| googoodan\.?$/i,'').replace(/\s*—\s*(CP|CE1|CE2|CM1|CM2)\b/,'');const name='drill-fr-'+u.gradeLabel.toLowerCase()+'-'+slug(title)+'-'+index+'.html';if(Object.values(mapping).includes(name)||fs.existsSync(path.join(fr,'print',name)))throw Error('Collision '+name);mapping[old]=name;idUrls[p.id]='/fr/print/'+name;}
let links=0;for(const f of fs.readdirSync(fr,{recursive:true}).filter(f=>/\.(html|xml|js)$/.test(f))){const p=path.join(fr,f);let s=fs.readFileSync(p,'utf8');for(const [old,name]of Object.entries(mapping)){const parts=s.split(old);links+=parts.length-1;s=parts.join(name);}fs.writeFileSync(p,s);}const sitemap=path.join(root,'sitemap.xml');let s=fs.readFileSync(sitemap,'utf8');for(const [old,name]of Object.entries(mapping)){const parts=s.split('/fr/print/'+old);links+=parts.length-1;s=parts.join('/fr/print/'+name);}fs.writeFileSync(sitemap,s);
// All resolved paths remain inside fr/print. Rename only the enumerated drill HTML files.
for(const [old,name]of Object.entries(mapping)){const a=path.resolve(fr,'print',old),b=path.resolve(fr,'print',name);if(path.dirname(a)!==path.join(fr,'print')||path.dirname(b)!==path.join(fr,'print'))throw Error('Unsafe path');fs.renameSync(a,b);}
const cat=path.join(fr,'reuse/drill-catalog.js');fs.appendFileSync(cat,'\nDrillCatalog.urls='+JSON.stringify(idUrls)+';\n');const dp=path.join(fr,'reuse/drill-page.js');s=fs.readFileSync(dp,'utf8').replace("'/fr/print/drill-'+encodeURIComponent(id)+'.html'","DC.urls[id]");fs.writeFileSync(dp,s);
for(const f of fs.readdirSync(fr,{recursive:true}).filter(f=>f.endsWith('.html'))){const p=path.join(fr,f);s=fs.readFileSync(p,'utf8').replace(/(\/fr\/reuse\/drill-(?:catalog|page)\.js)\?[^"\s]+/g,'$1?v=20260911-fr-urls');fs.writeFileSync(p,s);}
fs.writeFileSync(path.join(root,'.work-english/fr-url-report.json'),JSON.stringify({renamed:Object.keys(mapping).length,updatedReferences:links,mapping,idUrls},null,2));console.log({renamed:Object.keys(mapping).length,updatedReferences:links});
