const fs=require('fs'),path=require('path'),vm=require('vm');
const root=path.resolve(__dirname,'..'),fr=path.join(root,'fr'),work=path.join(root,'.work-english');fs.mkdirSync(work,{recursive:true});
const backup=path.join(work,'fr-before-seo-'+Date.now());fs.cpSync(fr,backup,{recursive:true});
const files=fs.readdirSync(fr,{recursive:true}).filter(f=>f.endsWith('.html')).map(f=>f.replaceAll('\\','/'));
const counts=s=>Object.fromEntries(['ko','ja','en','fr'].map(l=>[l,[...s.matchAll(new RegExp('<loc>https://googoodan.com/'+l+'/','g'))].length]));
let sitemap=fs.readFileSync(path.join(root,'sitemap.xml'),'utf8'),before=counts(sitemap);const originalOther=[...sitemap.matchAll(/<url>.*?<\/url>/gs)].map(m=>m[0]).filter(s=>!s.includes('https://googoodan.com/fr/'));
const c={Worksheets:{types:[]}};vm.createContext(c);vm.runInContext(fs.readFileSync(path.join(fr,'reuse/drill-catalog.js'),'utf8'),c);
const grammar=new Map(),changedJS=[];function fix(s){return s.replace(/\b(la|le)\s+(addition\w*|aire\w*|angle\w*|heure\w*|unité\w*|opération\w*|écriture\w*|ordre\w*)/gi,m=>{const n=m.replace(/^(la|le)\s+/i,m[0]===m[0].toUpperCase()?"L'":"l'");grammar.set(m,n);return n;}).replace(/\b(de|à)\s+(le|les)\b/gi,(m,a,b)=>{const n=(a.toLowerCase()==='de'?(b==='le'?'du':'des'):(b==='le'?'au':'aux'));grammar.set(m,n);return n;});}
for(const f of fs.readdirSync(fr,{recursive:true}).filter(f=>/\.(html|js)$/.test(f))){const p=path.join(fr,f),old=fs.readFileSync(p,'utf8'),s=fix(old);if(s!==old){fs.writeFileSync(p,s);if(f.endsWith('.js'))changedJS.push('/fr/'+f.replaceAll('\\','/'));}}
let pageSource=new Map(files.map(f=>[f,fs.readFileSync(path.join(fr,f),'utf8')]));const titleGroups=new Map();for(const [f,s]of pageSource){const t=s.match(/<title>(.*?)<\/title>/s)[1];if(!titleGroups.has(t))titleGroups.set(t,[]);titleGroups.get(t).push(f);}
let h1Changed=0,alternatesChanged=0,titlesClarified=0;const used=new Set();
for(const [f,original]of pageSource){let s=original,title=s.match(/<title>(.*?)<\/title>/s)[1];if(titleGroups.get(title).length>1){const id=f.replace('print/drill-','').replace('.html',''),u=c.DrillCatalog.units.find(u=>u.drills.some(p=>p.id===id)),p=c.DrillCatalog.profiles.get(id);let detail=u?u.name:'Concepts et applications';if(p?.source?.startsWith('natural-sub-'))detail+=' · '+p.source.split('-').slice(-2).join(' − ')+' chiffres';title=title.replace(/\s*\| googoodan\.?$/i,'')+' — '+detail+' | googoodan';if(used.has(title))throw Error('Still duplicate '+f);s=s.replace(/<title>.*?<\/title>/s,'<title>'+title+'</title>');titlesClarified++;}used.add(title);
const h1=title.replace(/\s*\|\s*googoodan\.?\s*$/i,'');let first=true;s=s.replace(/<h1([^>]*)>.*?<\/h1>/gs,(m,attrs)=>{if(first){first=false;if(m!==`<h1${attrs}>${h1}</h1>`)h1Changed++;return `<h1${attrs}>${h1}</h1>`;}return m.replace('<h1','<h2').replace('</h1>','</h2>');});if(first)throw Error('No h1 '+f);
const canonical=s.match(/<link rel="canonical" href="([^"]+)"/)[1];const old=s; s=s.replace(/<link\b[^>]*\bhreflang=["'][^"']+["'][^>]*>/gi,'');const langs={fr:canonical,ko:'https://googoodan.com/',en:'https://googoodan.com/en/',ja:'https://googoodan.com/ja/','x-default':'https://googoodan.com/'};s=s.replace('</head>',Object.entries(langs).map(([l,u])=>`<link rel="alternate" hreflang="${l}" href="${u}">`).join('')+'</head>');if(s!==old)alternatesChanged++;fs.writeFileSync(path.join(fr,f),s);}
// Preserve the static h1 after JS renders the drill menu.
const dp=path.join(fr,'reuse/drill-page.js');let ds=fs.readFileSync(dp,'utf8');ds=ds.replace("document.querySelector('aside h1').textContent='Calcul par classe et chapitre';",'');fs.writeFileSync(dp,ds);changedJS.push('/fr/reuse/drill-page.js');
for(const f of files){const p=path.join(fr,f);let s=fs.readFileSync(p,'utf8');for(const js of changedJS)s=s.replace(new RegExp(js.replace(/[.*+?^${}()|[\]\\]/g,'\\$&')+'(?:\\?[^"\\s>]*)?','g'),js+'?v=20260911-fr-seo');fs.writeFileSync(p,s);}
const urls=files.filter(f=>f!=='aide.html').map(f=>'https://googoodan.com/fr/'+(f==='index.html'?'':f));sitemap=sitemap.replace(/<url>.*?<\/url>/gs,m=>m.includes('https://googoodan.com/fr/aide.html')?'':m);for(const u of urls)if(!sitemap.includes('<loc>'+u+'</loc>'))sitemap=sitemap.replace('</urlset>','<url><loc>'+u+'</loc></url>\n</urlset>');fs.writeFileSync(path.join(root,'sitemap.xml'),sitemap);fs.writeFileSync(path.join(fr,'sitemap.xml'),'<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n'+urls.map(u=>'<url><loc>'+u+'</loc></url>').join('\n')+'\n</urlset>\n');
const afterOther=[...sitemap.matchAll(/<url>.*?<\/url>/gs)].map(m=>m[0]).filter(s=>!s.includes('https://googoodan.com/fr/'));if(JSON.stringify(originalOther)!==JSON.stringify(afterOther))throw Error('Other sitemap modified');
const report={backup,pages:files.length,before,after:counts(sitemap),h1Changed,titlesClarified,duplicateH1:0,grammar:[...grammar],alternatesChanged,changedJS};fs.writeFileSync(path.join(work,'fr-seo-report.json'),JSON.stringify(report,null,2));console.log(report);
