const fs=require('fs'),path=require('path');const walk=d=>fs.readdirSync(d,{withFileTypes:true}).flatMap(x=>x.isDirectory()?walk(d+'/'+x.name):[d+'/'+x.name]);
const work='.work-english/de-seo';fs.mkdirSync(work,{recursive:true});if(!fs.existsSync(work+'/backup'))fs.cpSync('de',work+'/backup',{recursive:true});
if(fs.existsSync('scripts/german-url-map.json'))throw Error('One-time migration already applied; use check-german-seo.cjs for validation');
const mapping={},routes={},used=new Set();let links=0,h1=0,titles=0;const counts={};const slug=s=>s.toLowerCase().replaceAll('ä','ae').replaceAll('ö','oe').replaceAll('ü','ue').replaceAll('ß','ss').replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'');
for(const p of walk('de').filter(p=>/\/drill-\d.*html$/.test(p))){const s=fs.readFileSync(p,'utf8'),topic=s.match(/<title>(.*?) – /)[1],id=path.basename(p,'.html').slice(6);let i=0,n;do{n='de/print/drill-de-by-klasse1-2-'+slug(topic)+'-'+i+++'.html';}while(used.has(n));used.add(n);mapping[p]=n;routes[id]='/'+n;}
fs.writeFileSync('scripts/german-url-map.json',JSON.stringify(mapping,null,2)+'\n');
for(const p of [...walk('de').filter(p=>/\.(html|js)$/.test(p)),'sitemap.xml']){let s=fs.readFileSync(p,'utf8');for(const[a,b]of Object.entries(mapping)){links+=s.split(a).length-1;s=s.replaceAll(a,b);}fs.writeFileSync(mapping[p]||p,s);if(mapping[p])fs.unlinkSync(p);}
let js=fs.readFileSync('de/reuse/drill-page.js','utf8');js=js.replace("location.href='/de/print/drill-'+encodeURIComponent(id)+'.html';",'location.href=('+JSON.stringify(routes)+')[id];');fs.writeFileSync('de/reuse/drill-page.js',js);
const seen=new Map();for(const p of walk('de').filter(p=>p.endsWith('.html'))){let s=fs.readFileSync(p,'utf8'),old=s.match(/<title>(.*?)<\/title>/s)[1],t=old;
if(p.includes('/drill-')){let topic=old.split(' – ')[0].replace(' mit Zehnerübergang bis 20',' bis 20: Zehnerübergang').replace('Die passende Rechnung finden','Passende Rechnung finden');const k=(seen.get(topic)||0)+1;seen.set(topic,k);if(k>1)topic+=' · Übung '+k;t=topic+' – Klasse 1/2 | googoodan';if(t.length>60)t=t.replace('Zehnerübergang','Zehnerwechsel');}
if(p==='de/units.html')t='Mathe-Aufgabentypen – Bayern Klasse 1–4 | googoodan';
if(t.length>60)throw Error('long '+t);if(t!==old)titles++;s=s.replace(/<title>.*?<\/title>/s,'<title>'+t+'</title>');const heading=t.replace(/ \| googoodan$/,'');s=s.replace(/<h1\b[^>]*>(.*?)<\/h1>/s,(m,x)=>{if(x!==heading)h1++;return '<h1>'+heading+'</h1>';});
const desc=heading+': kostenlos üben, mit Lösungen kontrollieren und zum Ausdrucken vorbereiten. Neue Zahlen für weitere Übungen auswählen.';
s=s.replace(/(<meta (?:name="description"|property="og:description") content=")[^"]*/g,'$1'+desc).replace(/(<meta property="og:title" content=")[^"]*/,'$1'+heading);
s=s.replace(/<script([^>]*type="application\/ld\+json"[^>]*)>([\s\S]*?)<\/script>/g,(m,a,b)=>{const j=JSON.parse(b);if(j['@type']==='LearningResource'){j.name=heading;j.description=desc;return '<script'+a+'>'+JSON.stringify(j)+'</script>';}return m;});
s=s.replace(/<h1 id="theme-name">(.*?)<\/h1>/g,'<h2 id="theme-name">$1</h2>');
const canonical=s.match(/<link rel="canonical" href="([^"]+)"/)[1];s=s.replace(/<link\b[^>]*\bhreflang=["'][^"']+["'][^>]*>/gi,'');const langs={de:canonical,ko:'https://googoodan.com/',en:'https://googoodan.com/en/',ja:'https://googoodan.com/ja/',fr:'https://googoodan.com/fr/','x-default':'https://googoodan.com/'};s=s.replace('</head>',Object.entries(langs).map(([l,u])=>'<link rel="alternate" hreflang="'+l+'" href="'+u+'">').join('')+'</head>');s=s.replace(/\/de\/reuse\/drill-page.js\?v=[^"\s>]+/g,'/de/reuse/drill-page.js?v=20260911-de-seo-url');fs.writeFileSync(p,s);counts.de=(counts.de||0)+1;}
const addDe=s=>s.replace('</head>','<link rel="alternate" hreflang="de" href="https://googoodan.com/de/"></head>');
for(const lang of ['fr','ja','en']){counts[lang]=0;for(const p of walk(lang).filter(p=>p.endsWith('.html'))){const s=fs.readFileSync(p,'utf8');if(!/hreflang=["']de["']/.test(s)){fs.writeFileSync(p,addDe(s));counts[lang]++;}}}
const report={renamed:Object.keys(mapping).length,urlReferencesUpdated:links,hreflang:counts,h1Changed:h1,titlesShortened:titles};fs.writeFileSync(work+'/report.json',JSON.stringify(report,null,2));console.log(report);
