(function(root){const base=root.KoMath,banks={};let excluded=[];
const add=(id,name,type,data)=>{(banks[id]??=[]).push({name,type,...data,activities:[{title:'표현을 바꾸어요'},{title:'관계를 이용해요'},{title:'상황을 해결해요'}]})};
for(const [id,large,small,factor] of [['2-2-3','m','cm',100],['3-1-5','cm','mm',10],['3-1-5','km','m',1000],['3-2-4','L','mL',1000],['3-2-4','kg','g',1000],['5-1-6','m²','cm²',10000],['6-1-6','m³','cm³',1000000]])add(id,large+'와 '+small+' · 단위 바꾸고 비교하기','measure',{large,small,factor});
add('1-2-3','시곗바늘 그리기 · 몇 시와 몇 시 반','clock',{step:30});add('2-2-4','시계로 나타내기 · 5분 단위','clock',{step:5});add('3-1-5','시작·끝·걸린 시간의 관계','duration',{});
function clock(h,m,blank){let face='<circle cx="70" cy="70" r="57" fill="#fffaf0" stroke="#739792" stroke-width="2"/>';for(let i=1;i<=12;i++){let a=i*Math.PI/6;face+='<text x="'+(70+46*Math.sin(a))+'" y="'+(74-46*Math.cos(a))+'" text-anchor="middle" font-size="11">'+i+'</text>'}if(!blank){for(const [angle,len,width] of [[(h%12+m/60)*Math.PI/6,29,3],[m*Math.PI/30,42,2]])face+='<path d="M70 70L'+(70+len*Math.sin(angle))+' '+(70-len*Math.cos(angle))+'" stroke="#294552" stroke-width="'+width+'"/>'}return '<svg class="learning-clock" viewBox="0 0 140 140">'+face+'<circle cx="70" cy="70" r="2" fill="#294552"/></svg>'}
function generate(id,p,seed,n=8){let offset=base.profiles(id).length;if(!banks[id]||p<offset)return base.generate(id,p,seed,n);const s=banks[id][p-offset],art=KoArt.session(seed,excluded);let state=seed>>>0;const r=(a,b)=>{state=(Math.imul(state,1664525)+1013904223)>>>0;return a+Math.floor(state/4294967296*(b-a+1))},fmt=t=>Math.floor(t/60)+'시 '+(t%60)+'분';return s.activities.map((activity,k)=>({title:activity.title,skill:s.type,questions:Array.from({length:n},()=>{const asset=art.take();let prompt,visual='<span class="picture-badge">'+KoArt.icon(asset)+'</span>',task='________________________',answer,reason,check;
if(s.type==='measure'){const a=r(1,8),b=r(1,9)*(s.factor/10),total=a*s.factor+b;if(k===0){prompt='두 가지 단위를 한 가지 단위로 나타내세요.';task=a+s.large+' '+b+s.small+' = □ '+s.small;answer=total+s.small;reason='1'+s.large+' = '+s.factor+s.small+'이므로 '+a*s.factor+' + '+b+'입니다.'}if(k===1){prompt='알맞은 수를 써서 단위를 바꾸세요.';task=total+s.small+' = □ '+s.large+' □ '+s.small;answer=a+s.large+' '+b+s.small;reason=s.factor+s.small+'씩 '+a+'묶음을 만들고 '+b+s.small+'가 남습니다.'}if(k===2){const c=r(1,9)*s.factor/10,other=a*s.factor+c;prompt='단위를 같게 바꾸어 두 양을 비교하세요. □에 >, =, < 중 하나를 쓰세요.';task=a+s.large+' '+b+s.small+' □ '+other+s.small;answer=total===other?'=':total>other?'>':'<';reason=total+s.small+'와 '+other+s.small+'를 비교합니다.'}check={kind:'measurement',factor:s.factor,a,b,total}}
if(s.type==='clock'){const h=r(1,11),m=r(0,60/s.step-1)*s.step;visual+=clock(h,m,k!==1);if(k===0){prompt=h+'시 '+(m===30?'반':m+'분')+'을 긴바늘과 짧은바늘로 그리세요.';task='<div class="kshort-space"></div>';answer=h+'시 '+m+'분';reason='긴바늘은 '+(m===0?12:m/5)+', 짧은바늘은 '+(m===0?h:h+'와 '+(h+1)+' 사이')+'를 가리킵니다.'}if(k===1){prompt='시각을 읽고 30분 뒤의 시각도 구하세요.';task='지금: __________<br>30분 뒤: __________';answer=fmt(h*60+m)+' / '+fmt(h*60+m+30);reason='60분이 되면 1시간으로 바꿉니다.'}if(k===2){prompt='긴바늘이 '+(m===0?12:m/5)+'를 가리키고 짧은바늘은 '+(m===0?h:h+'와 '+(h+1)+' 사이')+'에 있습니다. 시각을 쓰고 그리세요.';task='시각: __________________';answer=fmt(h*60+m);reason='시계의 큰 눈금 한 칸은 5분입니다.'}}
if(s.type==='duration'){const start=r(8,10)*60+r(0,5)*10,duration=r(2,7)*10,end=start+duration;if(k===0){prompt=fmt(start)+'에 출발해서 '+fmt(end)+'에 도착했습니다. 걸린 시간은 얼마인가요?';answer=duration+'분';reason=end+'분 − '+start+'분 = '+duration+'분'}if(k===1){prompt=fmt(end)+'에 도착했습니다. 이동하는 데 '+duration+'분 걸렸다면 몇 시에 출발했나요?';answer=fmt(start);reason='도착 시각에서 걸린 시간을 뺍니다.'}if(k===2){prompt=fmt(start)+'부터 '+duration+'분 동안 연습했습니다. 연습을 마친 시각은 언제인가요?';answer=fmt(end);reason='시작 시각에 걸린 시간을 더합니다.'}task='식 또는 시간선: __________________<div class="calculation-space"></div>답: __________________';check={kind:'duration',start,duration,end}}
return {methodId:s.type+'-'+k,artId:asset.id,prompt,visual,task,answer,reason,check};})}));}
root.KoMath={...base,profiles:id=>base.profiles(id).concat(banks[id]||[]),generate,excludeArt:ids=>{excluded=ids;base.excludeArt(ids)}};
})(globalThis);
