'use strict';
const el=id=>document.getElementById(id),base=window.GD_COMMUNITY.apiBase;
let token='',next=null,widget=null;try{token=sessionStorage.getItem('gd-admin-session')||'';}catch{}
function message(s){el('status').textContent=s;}
async function api(path,body){const r=await fetch(base+path,{method:body?'POST':'GET',headers:{'Content-Type':'application/json'},body:body?JSON.stringify(body):undefined});const data=await r.json();if(!r.ok)throw Error(data.error||'요청 실패');return data;}
function logout(){token='';try{sessionStorage.removeItem('gd-admin-session');}catch{}el('manage').hidden=true;el('detail').hidden=true;el('login').hidden=false;el('logout').hidden=true;message('로그아웃했습니다.');}
function show(){el('manage').hidden=false;el('login').hidden=true;el('logout').hidden=false;load();}
async function remove(kind,id,label){if(!confirm(label+' 삭제할까요? 삭제 후 되돌릴 수 없습니다.'))return false;const r=await fetch(base+'/'+kind+'/'+id,{method:'DELETE',headers:{'Content-Type':'application/json'},body:JSON.stringify({adminToken:token})});const d=await r.json();if(!r.ok){if(r.status===400||r.status===403)logout();throw Error(d.error||'삭제 실패');}message('삭제했습니다.');return true;}
async function details(p){const data=await api('/posts/'+p.id);el('detail').hidden=false;el('detailTitle').textContent=p.title+' · 댓글 관리';el('comments').replaceChildren();for(const c of data.comments){const row=document.createElement('div');row.className='comment';const name=document.createElement('strong'),text=document.createElement('p'),button=document.createElement('button');name.textContent=c.nickname;text.textContent=c.content;button.textContent='댓글 삭제';button.onclick=async()=>{try{if(await remove('comments',c.id,'이 댓글을')){row.remove();}}catch(e){message(e.message);}};row.append(name,text,button);el('comments').append(row);}if(!data.comments.length)el('comments').textContent='댓글이 없습니다.';}
async function load(more=false){try{const data=await api('/posts?q='+encodeURIComponent(el('query').value)+(more&&next?'&before='+next:''));if(!more)el('list').replaceChildren();for(const p of data.posts){const row=document.createElement('section');row.className='post-card';const title=document.createElement('strong'),info=document.createElement('small'),comments=document.createElement('button'),del=document.createElement('button');title.textContent=p.title;info.textContent=p.nickname+' · '+new Date(p.created_at).toLocaleDateString()+' · '+p.category;comments.textContent='댓글 관리 ('+p.comment_count+')';comments.onclick=()=>details(p).catch(e=>message(e.message));del.textContent='글 삭제';del.onclick=async()=>{try{if(await remove('posts',p.id,'「'+p.title+'」와 모든 댓글을')){el('detail').hidden=true;load();}}catch(e){message(e.message);}};row.append(title,info,comments,del);el('list').append(row);}next=data.next;el('more').hidden=!next;if(!el('list').children.length)el('list').textContent='게시글이 없습니다.';}catch(e){message(e.message);}}
el('login').onsubmit=e=>{e.preventDefault();if(!window.turnstile){message('스팸 방지 기능을 불러오는 중입니다. 잠시 후 다시 눌러주세요.');return;}if(widget!==null)turnstile.remove(widget);widget=turnstile.render('#bot',{sitekey:window.GD_COMMUNITY.turnstileSiteKey,action:'board-write',callback:async proof=>{try{const data=await api('/admin/login',{password:el('password').value,token:proof});el('password').value='';token=data.adminToken;try{sessionStorage.setItem('gd-admin-session',token);}catch{}message('로그인했습니다. 2시간 동안 관리할 수 있습니다.');show();}catch(err){message(err.message);}finally{if(widget!==null){turnstile.remove(widget);widget=null;}}},'error-callback':()=>message('인증을 다시 시도해 주세요.')});};
el('logout').onclick=logout;el('searchForm').onsubmit=e=>{e.preventDefault();load();};el('more').onclick=()=>load(true);
if(token&&Number(token.split('.')[0])>Date.now())show();else if(token)logout();
