(function(){
const palettes=[['#e9f5e9','#287b50','うさぎ'],['#eaf2ff','#366fa5','くま'],['#fff0df','#b57522','ねこ'],['#f1ebff','#8056ab','ロボット']];
let selected=[...new Set((new URLSearchParams(location.search).get('tables')||'2').split(',').map(Number).filter(n=>Number.isInteger(n)&&n>=0&&n<=19))];
const type={id:'times-tables',family:'Times tables',group:'Multiplication',title:'九九の練習',instruction:'選んだ段の九九を練習しましょう。',example:'2 × 3',config:{kind:'times'}};
function random(seed){let n=seed>>>0;return ()=>{n=(Math.imul(n,1664525)+1013904223)>>>0;return n/4294967296;};}
function rows(seed,count=28){if(!selected.length)return [];const r=random(seed),out=[];while(out.length<count){const factors=[...selected];for(let i=factors.length-1;i>0;i--){const j=Math.floor(r()*(i+1));[factors[i],factors[j]]=[factors[j],factors[i]];}for(const a of factors){if(out.length>=count)break;const b=1+Math.floor(r()*19);out.push({a,b,op:'×',answer:a*b,vertical:false});}}return out;}
function art(seed){const index=(seed>>>0)%4,[bg,ink,animal]=palettes[index];const ears=index===0?'<ellipse cx="37" cy="19" rx="8" ry="19"/><ellipse cx="65" cy="19" rx="8" ry="19"/>':index===1?'<circle cx="29" cy="30" r="13"/><circle cx="73" cy="30" r="13"/>':index===2?'<path d="M26 38L25 9L45 27M61 27L78 9L76 40Z"/>':'<path d="M51 24V8" stroke="'+ink+'" stroke-width="4"/><circle cx="51" cy="7" r="5"/>';
return {bg,ink,animal,svg:'<svg class="math-buddy" viewBox="0 0 110 90" role="img" aria-label="'+animal+' 友だち"><g fill="'+bg+'" stroke="'+ink+'" stroke-width="3">'+ears+'<rect x="23" y="25" width="58" height="52" rx="'+(index===3?9:26)+'"/></g><g fill="'+ink+'"><circle cx="41" cy="46" r="3"/><circle cx="64" cy="46" r="3"/></g><path d="M43 59Q52 68 63 59" stroke="'+ink+'" stroke-width="3" fill="none"/><text x="91" y="32" font-size="23" fill="'+ink+'">×</text></svg>'};}
let originalArt=null;
function reset(){if(!originalArt)return;const paper=document.querySelector(".paper"),hero=paper?.querySelector(".sheet-hero");if(!hero)return;hero.style.background=originalArt.background;hero.style.borderColor=originalArt.border;const buddy=hero.querySelector(".math-buddy");if(buddy)buddy.outerHTML=originalArt.svg;const label=hero.querySelector(".adventure-label");if(label)label.textContent=originalArt.label;paper.classList.remove("times-paper");}
function decorate(seed){const paper=document.querySelector('.paper'),hero=paper?.querySelector('.sheet-hero');if(!hero)return;if(!originalArt)originalArt={background:hero.style.background,border:hero.style.borderColor,svg:hero.querySelector(".math-buddy")?.outerHTML||"",label:hero.querySelector(".adventure-label")?.textContent||""};const a=art(seed);hero.style.background=a.bg;hero.style.borderColor=a.ink;paper.style.setProperty('--times-ink',a.ink);paper.classList.add('times-paper');const old=hero.querySelector('.math-buddy');if(old)old.outerHTML=a.svg;const title=hero.querySelector('.adventure-label');if(title)title.textContent=a.animal+' 友だちと九九の練習';}
function menu(root,change){const section=document.createElement('section');section.className='times-menu';root.append(section);function draw(){section.innerHTML='<h2>練習する段を選びましょう</h2><p>複数の段を選べます。</p><div class="times-actions"><button type="button" data-all>すべて選択</button><button type="button" data-clear>選択解除</button></div><div class="times-dans">'+Array.from({length:20},(_,n)=>'<button type="button" data-dan="'+n+'" aria-pressed="'+selected.includes(n)+'">'+n+'の段</button>').join('')+'</div><p class="times-selected">'+(selected.length?selected.join('·')+'の段の練習':'練習する段を選んでください.')+'</p><button type="button" data-chart>九九表を印刷</button><small>選んだ段を印刷します（×1〜19）。</small>';section.querySelectorAll('[data-dan]').forEach(b=>b.onclick=()=>{const n=Number(b.dataset.dan);selected=selected.includes(n)?selected.filter(x=>x!==n):[...selected,n].sort((a,b)=>a-b);draw();change();});section.querySelector('[data-all]').onclick=()=>{selected=Array.from({length:20},(_,n)=>n);draw();change();};section.querySelector('[data-clear]').onclick=()=>{selected=[];draw();change();};section.querySelector('[data-chart]').onclick=chart;}draw();}
function chart(){document.querySelector('#print-bundle')?.remove();if(!selected.length)return;const bundle=document.createElement('div');bundle.id='print-bundle';for(let offset=0;offset<selected.length;offset+=4){const group=selected.slice(offset,offset+4);const page=document.createElement('article');page.className='times-chart';page.innerHTML='<h1>九九表</h1><p>'+group.join(' · ')+'の段 · × 1~19</p><div class="times-chart-grid" style="grid-template-columns:repeat(2,1fr)">'+group.map(a=>'<section><h2>'+a+'の段</h2>'+Array.from({length:19},(_,i)=>'<p style="font-size:12px;margin:2px">'+a+' × '+(i+1)+' = <b>'+a*(i+1)+'</b></p>').join('')+'</section>').join('')+'</div>';bundle.append(page);}document.body.append(bundle);document.body.classList.add('printing-bundle');api.chartActive=true;window.print();}
const api=window.GDTimes={type,rows,menu,decorate,reset,art,get selected(){return [...selected]},chartActive:false};window.addEventListener('afterprint',()=>{api.chartActive=false;});
})();
