(() => {
 'use strict';
 const script=document.currentScript,ko=script.dataset.locale==='ko',local=['127.0.0.1','localhost'].includes(location.hostname);
 const api=local?'http://127.0.0.1:4208':'https://googoodan-community.googoodan-community.workers.dev';
 const t=(en,kr)=>ko?kr:en;
 const n=(tag,text)=>{const el=document.createElement(tag);if(text!==undefined)el.textContent=text;return el;};
 const style=n('style');style.textContent='.feedback-search-actions{display:flex;align-items:center;gap:10px;margin-left:auto;min-width:0}.feedback-search-actions .worksheet-search{margin:0!important;min-width:0;flex:1}.feedback-search-actions .feedback-open{margin:0;flex-shrink:0;padding:10px 12px;font-size:14px}@media(max-width:600px){.feedback-search-actions{width:100%;gap:6px}.feedback-search-actions .worksheet-search{width:0}.feedback-search-actions .feedback-open{font-size:12px;padding:10px 8px}}.feedback-open{display:inline-flex;align-items:center;justify-content:center;padding:12px 18px;border:1px solid #176e5c;border-radius:8px;background:#176e5c;color:white;font:700 15px/1.3 Arial,sans-serif;text-decoration:none;cursor:pointer;white-space:nowrap;margin-left:16px}.feedback-dialog{box-sizing:border-box;width:min(590px,calc(100vw - 28px));max-height:90vh;overflow:auto;padding:24px;border:1px solid #aacdc0;border-radius:12px;color:#214c50;background:#fff;font:16px/1.5 Arial,sans-serif}.feedback-dialog::backdrop{background:#123c4266}.feedback-dialog h2{font-size:23px;margin:0 0 8px}.feedback-dialog label{display:block;margin:12px 0 5px;font-weight:600}.feedback-dialog input,.feedback-dialog select,.feedback-dialog textarea{box-sizing:border-box;width:100%;font:inherit;padding:9px;border:1px solid #abc9c0;border-radius:5px;color:#214c50;background:#fff}.feedback-dialog textarea{min-height:140px;resize:vertical}.feedback-dialog .feedback-actions{display:flex;gap:10px;margin-top:16px}.feedback-dialog button{font:inherit;padding:9px 15px;cursor:pointer}.feedback-dialog .feedback-submit{background:#176e5c;color:white;border:1px solid #176e5c;border-radius:5px}.feedback-dialog small{font-size:13px}.feedback-dialog .feedback-trap{position:absolute;left:-10000px;width:1px;height:1px;overflow:hidden}.feedback-dialog [role=status]{white-space:pre-wrap}.feedback-dialog button:disabled{opacity:.55;cursor:wait}@media(max-width:600px){.feedback-open{margin:10px 0 0;padding:10px 14px;font-size:14px}}@media print{.feedback-open,.feedback-dialog{display:none!important}}';document.head.append(style);
 const button=n('button',t('Feedback & Requests','오류 신고 · 문제 요청'));button.type='button';button.className='feedback-open';
 const header=document.querySelector('body>header')||document.querySelector('header');if(!header)return;
 const old=script.dataset.replaceBadge==='true'?header.querySelector('a.badge[href="worksheets.html"]'):null;if(old)old.replaceWith(button);else {const search=header.querySelector('.worksheet-search');if(search){const group=n('div');group.className='feedback-search-actions';search.before(group);group.append(search,button);}else header.append(button);}
 const dialog=n('dialog');dialog.className='feedback-dialog';dialog.setAttribute('aria-labelledby','feedback-heading');
 const heading=n('h2',t('Feedback & Requests','오류 신고 · 문제 요청'));heading.id='feedback-heading';
 dialog.append(heading,n('p',t('Report a problem, request a worksheet, or ask a question. Only the site administrator can read your message. No account is needed.','잘못된 문제, 필요한 문제지, 궁금한 내용을 보내 주세요. 접수 내용은 관리자만 볼 수 있으며 회원가입이 필요 없습니다.')));
 const form=n('form');const fields={};
 function input(key,label,type='text',required=false,max=150){const lab=n('label',label);lab.htmlFor='feedback-'+key;const el=n(type==='textarea'?'textarea':'input');if(type!=='textarea')el.type=type;el.id=lab.htmlFor;el.name=key;el.required=required;el.maxLength=max;form.append(lab,el);fields[key]=el;return el;}
 const lab=n('label',t('Request type','접수 유형'));lab.htmlFor='feedback-category';const category=n('select');category.id=lab.htmlFor;for(const [value,en,kr]of [['error','Report an error','오류 신고'],['request','Request a worksheet','문제지 요청'],['other','Question or suggestion','질문 · 기타 의견']]){const option=n('option',t(en,kr));option.value=value;category.append(option);}form.append(lab,category);
 input('subject',t('Subject','제목'),'text',true).minLength=3;
 input('message',t('Message','내용'),'textarea',true,6000).minLength=10;
 input('email',t('Your email (optional, for a reply)','이메일 (답변을 원할 때만 입력)'),'email',false,254);
 input('worksheetUrl',t('Worksheet or page URL','문제지 또는 페이지 주소'),'url',false,1500);
 form.append(n('small',t('Please do not include children’s names or other personal details.','아이의 이름 등 개인 정보는 적지 말아 주세요.')));
 const trap=n('div');trap.className='feedback-trap';trap.setAttribute('aria-hidden','true');const trapInput=n('input');trapInput.name='website';trapInput.tabIndex=-1;trapInput.autocomplete='off';trap.append(trapInput);form.append(trap);
 const bot=n('div'),status=n('p');status.setAttribute('role','status');form.append(bot,status);
 const actions=n('div');actions.className='feedback-actions';const submit=n('button',t('Send message','접수하기'));submit.type='submit';submit.className='feedback-submit';const close=n('button',t('Close','닫기'));close.type='button';close.onclick=()=>dialog.close();actions.append(submit,close);form.append(actions);dialog.append(form);document.body.append(dialog);
 let widget=null,token='',requestId=crypto.randomUUID(),ready=false,opened=false;
 async function setup(){submit.disabled=true;status.textContent=t('Connecting…','연결 중…');try{const r=await fetch(api+'/feedback/status');if(!r.ok)throw Error();const config=await r.json();if(config.localPreview){ready=true;status.textContent=t('Local preview: messages are stored locally. Live bot checks and email delivery are not enabled yet.','로컬 미리보기: 접수는 로컬에 저장됩니다. 운영용 봇 검사와 이메일 발송은 아직 연결 전입니다.');submit.disabled=false;return;}if(!window.turnstile){await new Promise((resolve,reject)=>{const s=n('script');s.src='https://challenges.cloudflare.com/turnstile/v0/api.js?render=explicit';s.onload=resolve;s.onerror=reject;document.head.append(s);});}widget=turnstile.render(bot,{sitekey:config.siteKey,action:'feedback-submit',callback:value=>{token=value;ready=true;submit.disabled=false;status.textContent='';},'expired-callback':()=>{token='';submit.disabled=true;},'error-callback':()=>{token='';submit.disabled=true;status.textContent=t('Security check failed. Close and reopen this form to retry.','보안 확인에 실패했습니다. 창을 닫고 다시 열어 주세요.');}});opened=true;}catch{status.textContent=t('The feedback service is not available yet. Please try again later.','접수 서비스 연결 전입니다. 잠시 후 다시 시도해 주세요.');}}
 button.onclick=()=>{let url=location.href;try{const frame=document.querySelector('#active-sheet');if(frame)url=frame.contentWindow.location.href!=='about:blank'?frame.contentWindow.location.href:frame.src;}catch{}fields.worksheetUrl.value=url;dialog.showModal();if(!opened||local)setup();else if(widget!==null)turnstile.reset(widget);};
 form.onsubmit=async e=>{e.preventDefault();if(!ready)return;submit.disabled=true;status.textContent=t('Sending…','접수 중…');try{const body={requestId,site:ko?'ko':'us',category:category.value,website:trapInput.value,token,...Object.fromEntries(Object.entries(fields).map(([key,input])=>[key,input.value]))};const r=await fetch(api+'/feedback',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const result=await r.json();if(!r.ok)throw Error(result.error||'Unable to send.');form.reset();requestId=crypto.randomUUID();status.textContent=t('Thank you. Your private message has been received. Reference: ','접수되었습니다. 관리자만 내용을 확인할 수 있습니다. 접수 번호: ')+result.receipt;}catch(error){status.textContent=ko?'접수하지 못했습니다. 입력 내용을 확인한 뒤 다시 시도해 주세요. ('+error.message+')':error.message;}finally{if(local)submit.disabled=false;else if(widget!==null){token='';turnstile.reset(widget);}}};
})();
