(()=>{const original=globalThis.KoMath;
(function(root){const base=root.KoMath,banks={};let excluded=[];for(const [id,type] of [['2-2-5','bar'],['3-2-6','picture'],['4-1-5','bar'],['4-2-5','line'],['6-1-5','percent']])banks[id]=[{name:type==='line'?'변화량을 비교하는 꺾은선그래프':type==='percent'?'자료의 비율과 띠그래프':type==='picture'?'그림 한 개의 값과 자료 읽기':'표에서 그래프로, 그래프에서 질문으로',type,activities:[{title:'자료를 읽어요'},{title:'다른 모습으로 나타내요'},{title:'자료로 판단해요'}]}];
function generate(id,p,seed,n=8){const offset=base.profiles(id).length;if(!banks[id]||p<offset)return base.generate(id,p,seed,n);const s=banks[id][p-offset],art=KoArt.session(seed,excluded);let state=seed>>>0;const r=(a,b)=>{state=(Math.imul(state,1664525)+1013904223)>>>0;return a+Math.floor(state/4294967296*(b-a+1))};return s.activities.map((act,k)=>({title:act.title,skill:s.type,questions:Array.from({length:n},(_,index)=>{const asset=art.take(x=>['음식','동물과 자연','놀이와 운동'].includes(x.category)),labels=s.type==='line'?['월','화','수','목']:['가','나','다','라'];let values=Array.from({length:4},()=>r(1,8));if(s.type==='percent'){values=[r(1,3),r(1,3),r(1,2),0];values[3]=10-values.slice(0,3).reduce((a,b)=>a+b,0);values=values.map(x=>x*10)}const unit=s.type==='percent'?'%':'개',sum=values.reduce((a,b)=>a+b,0),max=Math.max(...values),winner=labels.filter((x,i)=>values[i]===max).join(', ');let prompt,task='',answer,reason='',visual='<span class="picture-badge">'+KoArt.icon(asset)+'</span>';
const table='<table class="ktable"><tr>'+labels.map(x=>'<th>'+x+'</th>').join('')+'</tr><tr>'+values.map(x=>'<td>'+x+unit+'</td>').join('')+'</tr></table>';
function chart(empty=false){const top=20,bottom=125,w=280;let out='<path d="M30 15V125H270" fill="none" stroke="#6b8791"/>';for(let t=0;t<=8;t+=2){const y=bottom-t*12;out+='<path d="M30 '+y+'H270" stroke="#dce6e8"/><text x="22" y="'+(y+4)+'" text-anchor="end" font-size="20">'+t+'</text>'}for(let i=0;i<4;i++){const x=60+i*55;out+='<text x="'+x+'" y="140" text-anchor="middle" font-size="20">'+labels[i]+'</text>';if(!empty)out+=s.type==='line'?'<circle cx="'+x+'" cy="'+(bottom-values[i]*12)+'" r="3" fill="#237d79"/>':'<rect x="'+(x-13)+'" y="'+(bottom-values[i]*12)+'" width="26" height="'+(values[i]*12)+'" fill="#85c9ba" stroke="#477e77"/>'}if(s.type==='line'&&!empty)out+='<polyline points="'+values.map((v,i)=>(60+i*55)+','+(bottom-v*12)).join(' ')+'" fill="none" stroke="#237d79" stroke-width="2"/>';if(empty){out+='<g class="geometry-answer">';if(s.type==='line'){out+='<polyline points="'+values.map((v,i)=>(60+i*55)+','+(bottom-v*12)).join(' ')+'" fill="none" stroke="#c62828" stroke-width="2"/>';out+=values.map((v,i)=>'<circle cx="'+(60+i*55)+'" cy="'+(bottom-v*12)+'" r="3" fill="#c62828"/>').join('')}else out+=values.map((v,i)=>'<rect x="'+(47+i*55)+'" y="'+(bottom-v*12)+'" width="26" height="'+(v*12)+'" fill="#f9dede" stroke="#c62828"/>').join('');out+='</g>'}return '<svg class="data-chart" viewBox="0 0 290 150">'+out+'</svg>'}
if(s.type==='percent'){visual+=table;if(k===0){prompt='전체가 200개라면 가에 해당하는 것은 몇 개인가요?';answer=String(values[0]*2)+'개';reason='200 × '+values[0]+'/100'}if(k===1){prompt='표의 비율에 맞추어 띠그래프의 경계를 긋고 이름을 쓰세요.';task='<div class="percent-strip"></div>0%　　　　　　　　50%　　　　　　　　100%';answer=values.slice(0,3).map((_,i)=>values.slice(0,i+1).reduce((a,b)=>a+b,0)+'%').join(', ')+'에 경계';reason='가·나·다·라 순서로 누적한 비율을 표시합니다.'}if(k===2){prompt='가와 나를 합한 비율은 다와 라를 합한 비율보다 큰가요? 수로 설명하세요.';const first=values[0]+values[1],second=100-first;answer=first+'% '+(first>second?'>':first<second?'<':'=')+' '+second+'%';reason='두 범주의 비율을 각각 더해 비교합니다.'}}
else if(s.type==='picture'){const pict=values.map((v,i)=>'<div>'+labels[i]+': '+'●'.repeat(v)+'</div>').join('');visual+='<div class="picture-data">'+pict+'</div><small>● 한 개는 10개를 나타냅니다.</small>';if(k===0){prompt='가의 실제 개수와 전체 개수를 구하세요.';answer=values[0]*10+'개, 전체 '+sum*10+'개';reason='그림 수에 10을 곱합니다.'}if(k===1){prompt='그림그래프를 보고 표의 빈칸을 채우세요.';task='<table class="ktable"><tr>'+labels.map(x=>'<th>'+x+'</th>').join('')+'</tr><tr><td>□</td><td>□</td><td>□</td><td>□</td></tr></table>';answer=values.map(x=>x*10).join(', ');reason='그림 한 개의 값을 먼저 확인합니다.'}if(k===2){prompt='“가와 나의 실제 개수는 '+(values[0]+values[1])+'개다.”라는 말을 고치세요.';answer=(values[0]+values[1])*10+'개';reason='그림 개수와 실제 개수는 다릅니다.'}}
else{visual+=k===1?table:chart();if(k===0){prompt=s.type==='line'?'요일별 값 중 가장 큰 값과 그 요일을 모두 쓰세요.':'가장 많은 범주와 전체 개수를 구하세요.';answer=winner+', '+(s.type==='line'?max:sum)+'개';reason='같은 최댓값이 여러 번 나오면 모두 찾습니다.'}if(k===1){prompt='표를 보고 '+(s.type==='line'?'점을 찍고 차례로 이어 꺾은선그래프를':'막대를 그려 막대그래프를')+' 완성하세요.';task=chart(true);answer=labels.map((x,i)=>x+' '+values[i]).join(', ');reason='가로축의 이름과 세로축의 눈금을 확인합니다.'}if(k===2){if(s.type==='line'){const changes=values.slice(1).map((v,i)=>v-values[i]),largest=Math.max(...changes);prompt='앞날보다 가장 많이 늘어난 구간과 늘어난 양을 구하세요. 늘어난 구간이 없으면 없다고 쓰세요.';answer=largest>0?changes.map((v,i)=>v===largest?labels[i]+'→'+labels[i+1]:'').filter(Boolean).join(', ')+' / '+largest+'개':'늘어난 구간 없음';reason='값 자체의 크기가 아니라 이웃한 두 값의 차이를 비교합니다.'}else{prompt='가와 나를 합한 수가 다와 라를 합한 수보다 얼마나 많거나 적은지 쓰세요.';const diff=values[0]+values[1]-values[2]-values[3];answer=diff===0?'같습니다.':Math.abs(diff)+'개 '+(diff>0?'많습니다.':'적습니다.');reason='두 범주의 합끼리 비교합니다.'}}}
return {methodId:s.type+'-'+k,artId:asset.id,prompt,visual,task:task||'________________________',answer,reason,check:{kind:'data-target',values,sum}};})}));}
root.KoMath={...base,profiles:id=>base.profiles(id).concat(banks[id]||[]),generate,excludeArt:ids=>{excluded=ids;base.excludeArt(ids)}};
})(globalThis);

globalThis.EsDataSource=globalThis.KoMath;globalThis.KoMath=original;})();
