/* The original ko/engine.js is loaded first. Keep its generator and catalog intact. */
(()=>{
const source=KoMath;
const definitions=[["es-1-contar",1,1,"Contar hasta 9","1-1-1","count:9"],["es-1-comparar",1,2,"Comparar números hasta 9","1-1-1","compare:9"],["es-2-decenas-unidades",2,1,"Decenas y unidades","1-2-1","place:2"],["es-2-sumas",2,2,"Sumas hasta 100","2-1-3","add:99"],["es-3-restas",3,1,"Repaso: restas hasta 1 000","3-1-1","sub:999"],["es-3-multiplicaciones",3,2,"Multiplicar por una cifra","3-1-4","mul:99"],["es-4-angulos-rectos",4,1,"Reconocer ángulos rectos","4-1-2","angle-right"],["es-4-simetria",4,2,"Ejes de simetría del cuadrado","4-1-2","symmetry-line"],["es-4-fracciones-figuras",4,3,"Fracciones y figuras","3-1-6","fraction-model"],["es-5-comparar-fracciones",5,1,"Repaso: fracciones con igual denominador","3-2-5","fraction-compare"]];
definitions.push(['es-4-tipos-angulos',4,4,'Ángulos agudos, rectos y obtusos','4-1-2','angle-type'],['es-4-transportador',4,5,'Leer el transportador de ángulos','4-1-2','angle-measure'],['es-5-perimetro-rectangulo',5,2,'Perímetro del rectángulo','5-1-6','perimeter'],['es-5-area-rectangulo',5,3,'Área del rectángulo','5-1-6','area-rectangle']);
definitions.push(['es-2-regla',2,3,'Leer la regla','2-1-4','ruler:cm'],['es-3-centimetros-milimetros',3,3,'Centímetros y milímetros','3-1-5','convert:mm'],['es-3-metros-centimetros',3,4,'Metros y centímetros','2-2-3','convert:m'],['es-4-kilogramos-gramos',4,6,'Kilogramos y gramos','3-2-4','convert:kg'],['es-4-litros-mililitros',4,7,'Litros y mililitros','3-2-4','convert:L']);
definitions.push(...[["es-5-decimales-figuras",5,4,"Décimas y números decimales","3-1-6","decimal-model"],["es-5-centesimas-decimales",5,5,"De centésimas a números decimales","6-1-3","decimal-fraction"],["es-5-simplificar-fracciones",5,6,"Simplificar fracciones","5-1-4","reduce"],["es-5-comparar-denominadores",5,7,"Comparar fracciones diferentes","5-1-4","fraction-compare-unlike"]]);
definitions.push(...[["es-2-leer-tablas",2,4,"Leer tablas de datos","2-2-5","table"],["es-3-pictogramas",3,5,"Leer pictogramas","3-2-6","graph:picture"],["es-4-graficos-barras",4,8,"Leer gráficos de barras","4-1-5","graph:bar"],["es-5-media-aritmetica",5,8,"Calcular la media aritmética","5-2-6","average"]]);
definitions.push(...[["es-2-horas-medias",2,5,"Reloj: horas y medias horas","1-2-3","clock:30"],["es-2-semanas-dias",2,6,"Semanas y días","2-2-4","calendar"],["es-3-reloj-minutos",3,6,"Reloj: intervalos de 5 minutos","2-2-4","clock:5"],["es-3-hora-final",3,7,"Calcular la hora final","2-2-4","elapsed"],["es-4-minutos-segundos",4,9,"Convertir minutos y segundos","3-1-5","time-seconds"]]);
definitions.push(...[["es-1-figuras-planas",1,3,"Reconocer figuras planas","1-2-3","flat-basic"],["es-2-contar-lados",2,7,"Contar los lados de las figuras","2-1-2","flat-count"],["es-3-lineas-segmentos",3,8,"Rectas, semirrectas y segmentos","3-1-2","lines"],["es-3-lados-poligonos",3,9,"Contar los lados de los polígonos","4-2-6","polygon"]]);
definitions.push(...[["es-5-sumas-igual-denominador",5,9,"Sumas de fracciones: igual denominador","4-2-1","fraction-add-same"],["es-5-restas-igual-denominador",5,10,"Restas de fracciones: igual denominador","4-2-1","fraction-sub-same"],["es-5-sumas-fracciones",5,11,"Sumas de fracciones","5-1-5","fraction-add"],["es-5-restas-fracciones",5,12,"Restas de fracciones","5-1-5","fraction-sub"]]);
definitions.push(...[["es-5-sumas-decimales",5,13,"Sumas con números decimales","4-2-3","decimal-add"],["es-5-restas-decimales",5,14,"Restas con números decimales","4-2-3","decimal-sub"],["es-5-decimales-por-naturales",5,15,"Multiplicar decimales por naturales","5-2-4","decimal-mul-whole"],["es-5-decimales-entre-naturales",5,16,"Dividir decimales entre naturales","6-1-3","decimal-div-whole"]]);
definitions.push(...[["es-2-centenas-decenas-unidades",2,8,"Centenas, decenas y unidades","2-1-1","place:3"],["es-3-cifras-millares",3,10,"Reconocer cifras hasta los millares","2-2-1","place:4"],["es-5-divisores",5,17,"Encontrar todos los divisores","5-1-2","factor"],["es-5-multiplos",5,18,"Los tres primeros múltiplos positivos","5-1-2","multiple"]]);
definitions.push(...[["es-5-redondear",5,19,"Redondear a decenas y centenas","5-2-1","round-nearest"],["es-5-orden-operaciones",5,20,"El orden de las operaciones","5-1-1","mixed"],["es-5-operaciones-parentesis",5,21,"Operaciones con paréntesis","5-1-1","mixed-bracket"],["es-5-denominador-comun",5,22,"El mínimo denominador común","5-1-4","common-denominator"]]);
definitions.push(...[["es-6-area-triangulo",6,1,"Área del triángulo","5-1-6","area-triangle"],["es-6-area-paralelogramo",6,2,"Área del paralelogramo","5-1-6","area-parallelogram"],["es-6-area-trapecio",6,3,"Área del trapecio","5-1-6","area-trapezoid"],["es-6-area-rombo",6,4,"Área del rombo","5-1-6","area-rhombus"]]);
definitions.push(...[["es-6-porcentajes",6,5,"Calcular un porcentaje","6-1-4","percent"],["es-6-probabilidad-basica",6,6,"Sucesos seguros, imposibles y al 50%","5-2-6","chance"],["es-6-media-dato-desconocido",6,7,"La media y el dato desconocido","5-2-6","average-missing"]]);
definitions.push(...[["es-2-contar-cubos",2,9,"Contar cubos","2-1-2","cube-count"],["es-6-columnas-cubos",6,8,"Contar cubos desde un plano","6-2-3","cube-count"],["es-6-vistas-cubos",6,9,"Cubos: vistas frontal y lateral","6-2-3","cube-view"],["es-6-quitar-columna",6,10,"Quitar una columna de cubos","6-2-3","cube-missing"]]);
definitions.push(["es-2-cuerpos-geometricos",2,10,"Reconocer cuerpos geométricos","2-2-6","solid-basic"]);
definitions.push(...[["es-1-contar-formas",1,4,"Contar formas iguales","1-1-2","sort"],["es-1-comparar-longitudes",1,5,"Comparar longitudes","1-1-5","length-compare"]]);
const compareText=s=>String(s).replaceAll('막대가 길수록 길이가 큽니다.',"Compara las longitudes.").replace(/(?<![가-힣])(가|나)(?![가-힣])/g,(_,x)=>x==='가'?'A':'B');
definitions.push(...[["es-1-series-formas",1,6,"Completar series de formas","1-2-5","pattern"],["es-2-series-numeros",2,11,"Números que faltan hasta 100","1-2-1","sequence:100"]]);
definitions.push(...[["es-1-descomponer-numeros",1,7,"Descomponer números hasta 10","1-2-2","bond:10"],["es-2-multiplicacion-filas-columnas",2,12,"Multiplicar con filas y columnas","2-1-6","array"]]);
definitions.push(...[["es-6-multiplicar-decimales",6,11,"Multiplicar números decimales","5-2-4","decimal-mul"],["es-6-divisor-decimal",6,12,"Dividir entre un número decimal","6-2-2","decimal-div"]]);
definitions.push(...[["es-4-traslaciones-cuadricula",4,10,"Traslaciones en cuadrícula","4-1-4","geometry-move"],["es-4-simetrias-cuadricula",4,11,"Simetrías en cuadrícula","4-1-4","geometry-flip"],["es-6-giros-cuadricula",6,13,"Giros de 90 grados en cuadrícula","4-1-4","geometry-turn"]]);
const geometryText=s=>String(s).replaceAll('빨간 모양을 확인하세요.',"Comprueba la figura roja.").replaceAll('빨간 모양이 처음 모양입니다.',"La figura roja es la inicial.").replaceAll('×, 빨간 모양으로 고칩니다.',"×, corrige siguiendo la figura roja.").replaceAll('중심',"Centro").replace(/src="art\//g,'src="/ko/art/').replace(/alt="[^"]*"/g,'alt=""');
definitions.push(...[["es-6-graficos-lineas",6,14,"Gráficos de líneas: leer y dibujar","4-2-5","data-line"],["es-6-diagramas-bandas",6,15,"Porcentajes y diagramas de bandas","6-1-5","data-percent"]]);
const bankText=s=>String(s).replaceAll('전체',"total").replaceAll('같습니다.',"Son iguales.").replace(/(\d+)개 많습니다\./g,"$1 más").replace(/(\d+)개 적습니다\./g,"$1 menos").replaceAll('● 한 개는 10개를 나타냅니다.',"● = 10 elementos").replaceAll('늘어난 구간 없음',"Ningún aumento").replaceAll('에 경계',": límites").replaceAll('개','').replace(/(?<![가-힣])(월|화|수|목|가|나|다|라)(?![가-힣])/g,(_,x)=>({월:"Lun",화:"Mar",수:"Mié",목:"Jue",가:'A',나:'B',다:'C',라:'D'})[x]);
definitions.push(...[["es-4-construir-graficos-barras",4,12,"Dibujar y comparar gráficos de barras","4-1-5","data-bar"],["es-3-pictogramas-tablas",3,11,"Pictogramas: completar tablas","3-2-6","data-picture"]]);
definitions.push(...[["es-4-radio-circulo",4,13,"Reconocer el radio del círculo","3-2-2","circle-parts"],["es-4-diametro-circulo",4,14,"Calcular el diámetro del círculo","3-2-2","circle-size"]]);
definitions.push(...[["es-4-clasificar-triangulos",4,15,"Clasificar triángulos por sus ángulos","4-2-2","triangle-type"],["es-4-clasificar-cuadrilateros",4,16,"Clasificar cuadriláteros","4-2-4","quad-type"]]);
definitions.push(...[["es-3-metros-centimetros-comparar",3,12,"Metros y centímetros: convertir y comparar","2-2-3","metric-m-cm",0],["es-4-masa-conversiones-comparar",4,17,"Kilogramos y gramos: equivalencias","3-2-4","metric-kg-g",1],["es-4-capacidad-conversiones-comparar",4,18,"Litros y mililitros: equivalencias","3-2-4","metric-L-mL",0]]);
definitions.push(...[["es-3-centimetros-milimetros-equivalencias",3,13,"Centímetros y milímetros: equivalencias","3-1-5","metric-cm-mm",0],["es-3-kilometros-metros-equivalencias",3,14,"Kilómetros y metros: equivalencias","3-1-5","metric-km-m",1]]);
definitions.push(...[["es-2-dibujar-reloj",2,13,"Dibujar el reloj: horas y medias","1-2-3","time-clock-30",0],["es-3-dibujar-minutos",3,15,"Dibujar el reloj cada 5 minutos","2-2-4","time-clock-5",0],["es-3-inicio-final-duracion",3,16,"Inicio, final y tiempo transcurrido","3-1-5","time-duration",2]]);
const documentLang='es';
const clockCopy={"draw":"Dibuja las agujas para indicar las ","read":"Lee la hora y escribe también qué hora será 30 minutos después.","long":"La aguja de los minutos señala ","short":" y la de las horas señala ","between":" y está entre ","end":". Escribe la hora y dibuja las agujas.","reason":"La aguja corta indica las horas y la larga los minutos. Cada intervalo grande vale 5 minutos.","now":"Hora actual","later":"30 minutos después","time":"Hora","work":"Operación o línea del tiempo","answer":"Respuesta","duration":["Tiempo transcurrido","Hora de inicio","Hora final"],"clock":["Dibuja las agujas","Lee y añade tiempo","Reconstruye la hora"],"start":"Inicio: ","arrival":"Final: ","elapsed":"Tiempo transcurrido: ","askDuration":"¿Cuánto tiempo ha transcurrido?","askStart":"¿A qué hora empezó?","askEnd":"¿A qué hora terminó?","reasons":["Resta la hora inicial de la final.","Resta la duración de la hora final.","Suma la duración a la hora inicial."]};
const timeText=s=>String(s).replaceAll('class="learning-clock"','class="learning-clock" style="width:85px;height:85px"').replaceAll('식 또는 시간선',clockCopy.work).replaceAll('30분 뒤',clockCopy.later).replaceAll('지금',clockCopy.now).replaceAll('시각',clockCopy.time).replaceAll('답:',clockCopy.answer+':').replace(/(\d+)분/g,'$1 min');
const dataText=s=>String(s).replaceAll('사과','Manzanas').replaceAll('배','Peras').replaceAll('귤','Mandarinas').replace(/● 한 개는 (\d+)명/g,'● = $1 personas').replaceAll('선택한 사람 수 (명)','Número de personas').replace(/>(가|나|다)</g,(_,x)=>'>'+({가:'A',나:'B',다:'C'}[x])+'<');
const decimalText=s=>String(s).split(/(<[^>]*>)/g).map((t,i)=>i%2?t:t.replace(/(\d)\.(\d)/g,'$1,$2')).join('');
const tr=s=>String(s).replaceAll("예각삼각형","triángulo acutángulo").replaceAll("직각삼각형","triángulo rectángulo").replaceAll("둔각삼각형","triángulo obtusángulo").replaceAll("직사각형","rectángulo").replaceAll("정사각형","cuadrado").replaceAll("마름모","rombo").replaceAll("평행사변형","paralelogramo").replaceAll('반지름',"radio").replaceAll('지름',"diámetro").replaceAll('꼭짓점',"vértice").replaceAll('직육면체','prisma rectangular').replaceAll('원기둥','cilindro').replace(/(?<![가-힣])구(?![가-힣])/g,'esfera').replaceAll('위에서 본 모양 · 숫자는 그 자리의 개수 · 아래쪽이 앞','Vista superior: cada número indica los cubos de la columna. El borde inferior es el frente.').replaceAll('불가능하다','imposible').replaceAll('확실하다','seguro').replaceAll('반반이다','probabilidad del 50%').replaceAll('길이는 문제의 조건을 보세요','Medidas indicadas en el texto').replaceAll('삼각형','triángulo').replaceAll('사각형','cuadrilátero').replaceAll('원','círculo').replaceAll('선분','segmento').replaceAll('반직선','semirrecta').replaceAll('직선','recta').replace(/(\d+)시\s*(\d+)분/g,(_,h,m)=>h+':'+m.padStart(2,'0')).replaceAll('친구의 답:','Respuesta propuesta:').replaceAll('맞으면 ○, 틀리면 ×. 틀린 답은 고치세요.','Verdadero: ○. Falso: ×. Corrige la respuesta incorrecta.').replaceAll('바른 답:','Respuesta correcta:').replaceAll('예각','agudo').replaceAll('직각','recto').replaceAll('둔각','obtuso').replaceAll('아니요','No').replaceAll('예','Sí').replaceAll('문제 그림','Figura del ejercicio');
globalThis.EsSourceMath=source;globalThis.EsDefinitions=definitions;
globalThis.KoCatalog={units:definitions.map(([id,grade,number,name])=>({id,grade,number,name,semester:1,gradeLabel:'Curso '+grade})),themes:Array.from({length:12},()=>['Paso a paso','Observa, calcula y explica','#278477','#edf8e9','rabbit'])};
globalThis.KoMath={...source,profiles(id){const d=definitions.find(x=>x[0]===id);return d?[{name:d[3]}]:[];},generate(id,p,seed,n){
 const d=definitions.find(x=>x[0]===id);if(!d||p!==0)throw Error('Unsupported Spanish topic');
 return ((d[5].startsWith('metric-')||(d[5].startsWith('time-clock')||d[5]==='time-duration'))?EsMeasurementSource.generate(d[4],source.profiles(d[4]).length+d[6],seed,n):d[5].startsWith('data-')?EsDataSource.generate(d[4],source.profiles(d[4]).length,seed,n):d[5].startsWith('geometry-')?EsGeometrySource.generate(d[4],source.profiles(d[4]).length+['geometry-move','geometry-flip','geometry-turn'].indexOf(d[5]),seed,n):source.generate(d[4],0,seed,n,[0,1,2].map(mode=>({skill:d[5],mode})))).map((s,i)=>({...s,title:(d[5].startsWith('time-clock')||d[5]==='time-duration')?["Dibuja o calcula","Lee y completa","Encuentra el dato que falta"][i]:d[5].startsWith('metric-')?["Convierte la medida","Completa la equivalencia","Compara las medidas"][i]:d[5].startsWith('data-')?["Lee los datos","Representa los datos","Interpreta los datos"][i]:d[5].startsWith('geometry-')?["Dibuja la figura transformada","Reconstruye la figura inicial","Comprueba el dibujo"][i]:['Observa y resuelve','Completa o elige','Comprueba la respuesta'][i],questions:s.questions.map(q=>{
  const skill=d[5].split(':')[0];let prompt,reason;
  if(d[5].startsWith('time-clock')){if(i===0){const m=q.answer.match(/(\d+)시 (\d+)분/);prompt=clockCopy.draw+m[1]+':'+m[2].padStart(2,'0')+'.';}else if(i===1)prompt=clockCopy.read;else{const m=q.prompt.match(/긴바늘이 (\d+)를 가리키고 짧은바늘은 (\d+)(?:와 (\d+) 사이)?/);prompt=clockCopy.long+m[1]+(m[3]?(documentLang==='it'?' e quella delle ore è tra ':' y la de las horas está entre ')+m[2]+(documentLang==='it'?' e ':' y ')+m[3]:clockCopy.short+m[2])+clockCopy.end;}reason="Horas: aguja corta. Minutos: aguja larga.";}
  else if(q.check?.kind==='duration'){const c=q.check,fmt=t=>Math.floor(t/60)+':'+String(t%60).padStart(2,'0');prompt=i===0?clockCopy.start+fmt(c.start)+'. '+clockCopy.arrival+fmt(c.end)+'. '+clockCopy.askDuration:i===1?clockCopy.arrival+fmt(c.end)+'. '+clockCopy.elapsed+c.duration+' min. '+clockCopy.askStart:clockCopy.start+fmt(c.start)+'. '+clockCopy.elapsed+c.duration+' min. '+clockCopy.askEnd;reason=clockCopy.reasons[i];}
  else if(q.check?.kind==='measurement'){const m=q.check,[_,large,small]=d[5].split('-');prompt=["Expresa la medida usando solo la unidad más pequeña.","Completa los números que faltan para usar las dos unidades.","Expresa las medidas en la misma unidad y compáralas con >, = o <."][i];reason=i===0?'1 '+large+' = '+m.factor+' '+small+'; '+m.a+' × '+m.factor+' + '+m.b+' = '+m.total+' '+small:i===1?m.total+' '+small+' = '+m.a+' × '+m.factor+' '+small+' + '+m.b+' '+small:"Compara "+m.total+' '+small+' / '+q.task.match(/(\d+)[a-zA-Z]+$/)[1]+' '+small+'.';}
  else if(d[5]==='data-bar'){prompt=["Indica todas las categorías más numerosas y el total de elementos.","Completa el gráfico dibujando las barras correspondientes a la tabla.","Compara A+B con C+D: indica cuánto mayor o menor es el primer total, o si son iguales."][i];reason=["Busca el valor máximo y suma todos los valores.","Comprueba etiquetas y escala antes de dibujar las barras.","Suma cada pareja y compara los resultados."][i];}
  else if(d[5]==='data-picture'){prompt=i===0?"¿Cuántos elementos representa A? ¿Cuántos elementos hay en total?":i===1?"Completa la tabla con los valores reales del pictograma.":"Corrige esta frase: “A y B representan "+(q.check.values[0]+q.check.values[1])+" elementos en total”.";reason=["Cada símbolo representa 10 elementos: multiplica el número de símbolos por 10.","Lee la leyenda antes de completar cada columna.","No confundas el número de símbolos con el número de elementos."][i];}
  else if(q.check?.kind==='data-target'){prompt=(d[5]==='data-line'?["Indica el valor máximo y todos los días en los que aparece.","Dibuja los puntos de la tabla y únelos en orden para completar el gráfico.","Encuentra todos los intervalos con el mayor aumento e indica cuánto aumenta. Si nunca aumenta, escribe “ningún aumento”."]:["Si el total es de 200 elementos, ¿cuántos pertenecen a la categoría A?","Marca los límites en la banda y escribe las categorías según los porcentajes de la tabla.","¿La suma de los porcentajes de A y B es mayor que la suma de C y D? Compara con números."])[i];reason=d[5]==='data-line'?["Busca todos los días que tienen el mismo valor máximo.","Comprueba las etiquetas y la escala de los ejes.","Compara las diferencias entre días consecutivos, no solo los valores."][i]:i===0?q.reason:i===1?"Marca los porcentajes acumulados en el orden A, B, C, D.":"Suma los porcentajes de cada pareja y compáralos.";}
  else if(q.check?.kind==='transform'){const inst=q.check.type==='move'?"Desplaza la figura "+q.check.dx+" casillas a la derecha y una casilla hacia abajo.":q.check.type==='flip'?"Refleja la figura respecto a la línea discontinua.":"Gira la figura 90° en sentido horario alrededor del punto indicado.";prompt=inst+[" Dibuja la figura transformada."," La figura muestra el resultado: dibuja la figura inicial.","¿La figura morada es la transformación correcta de la figura verde? Corrígela si es necesario."][i];reason=["Aplica la misma transformación a cada vértice.","Recorre la transformación en sentido inverso.","Comprueba cada vértice: la forma y el tamaño se conservan."][i];}
  else if(q.check?.kind==='calc'){const c=q.check;prompt=['Calcula el resultado.','Escribe el número que falta.','Comprueba el resultado de '+q.reason.split(' = ')[0]+'.'][i];reason=q.reason.replaceAll('이므로',', por tanto');}
  else if(q.check?.kind==='fraction'){prompt=i===1?'Completa el numerador que falta.':i===2?'Calcula y comprueba el resultado propuesto.':d[4]==='4-2-1'?'Calcula el resultado.':'Calcula y escribe una fracción irreducible o un número entero.';reason=q.reason;}
  else if(skill==='perimeter'){const c=q.check;prompt='¿Cuál es el perímetro del rectángulo en cm?';reason='('+c.a+' + '+c.b+') × 2 = '+c.result+' cm';}
  else if(skill==='area-rectangle'){const c=q.check;prompt='¿Cuál es el área del rectángulo en cm²?';reason=c.a+' × '+c.b+' = '+c.result+' cm²';}
  else if(skill==='angle-type'){prompt='¿El ángulo es agudo, recto u obtuso?';reason='Agudo: menos de 90°. Recto: 90°. Obtuso: más de 90° y menos de 180°.';}
  else if(skill==='angle-measure'){prompt='Lee el transportador. ¿Cuánto mide el ángulo?';const degrees=q.reason.match(/(\d+)°를/)[1];reason='Empieza en el cero de la derecha: el otro lado marca '+degrees+'°.';}
  else if(skill==='ruler'){prompt='¿Cuánto mide la barra en cm?';reason='Resta la posición inicial de la final: '+q.reason+'.';}
  else if(skill==='convert'){const m=q.prompt.match(/^(\d+)(\w+) (\d+)(\w+)는 몇 (\w+)인가요/);prompt='Expresa '+m[1]+' '+m[2]+' y '+m[3]+' '+m[4]+' en '+m[5]+'.';reason=q.reason.replaceAll('입니다.','.');}
  else if(skill==='decimal-model'){prompt='Escribe la parte coloreada como número decimal.';reason=q.reason;}
  else if(skill==='decimal-fraction'){const n=q.prompt.match(/^(\d+)\/100/)[1];prompt='Escribe '+n+'/100 como número decimal.';reason=n+' centésimas: utiliza dos cifras después de la coma.';}
  else if(skill==='reduce'){prompt='Reduce la fracción a su forma irreducible.';const n=q.reason.match(/(\d+)로/)[1];reason='Divide el numerador y el denominador por su máximo común divisor, '+n+'.';}
  else if(skill==='fraction-compare-unlike'){prompt='Compara las fracciones con distinto denominador.';reason='Expresa las fracciones con un denominador común y compara los numeradores.';}
  else if(skill==='table'){const fruit=q.prompt.match(/^(사과|배|귤)/)[1];prompt='¿Cuántas frutas hay en la columna '+dataText(fruit)+'?';reason='Lee el número que aparece debajo del nombre de la fruta en la tabla.';}
  else if(skill==='graph'){if(i===2){prompt='Suma los valores de las categorías A y B.';reason=q.reason;}else{const label=({가:'A',나:'B',다:'C'})[q.prompt[0]];prompt='¿Cuántas personas han elegido la categoría '+label+'?';reason='Lee la escala o la leyenda y encuentra el valor de la categoría.';}}
  else if(skill==='average'){const sum=q.reason.match(/합 (\d+)/)[1];prompt='Calcula la media de los tres números.';reason='Divide la suma '+sum+' entre el número de datos, 3.';}
  else if(skill==='clock'){prompt='Escribe la hora que indica el reloj.';reason='La aguja corta indica las horas y la larga indica los minutos.';}
  else if(skill==='calendar'){const weeks=q.prompt.match(/^(\d+)/)[1];prompt='¿Cuántos días hay en '+weeks+' '+(weeks==='1'?'semana':'semanas')+'?';reason='Una semana tiene 7 días: multiplica el número de semanas por 7.';}
  else if(skill==='elapsed'){const m=q.prompt.match(/^(\d+)시 (\d+)분부터 (\d+)분/);prompt='Hora inicial: '+m[1]+':'+m[2].padStart(2,'0')+'. ¿Qué hora será después de '+m[3]+' minutos?';reason='Suma los minutos transcurridos. Cada 60 minutos pasa una hora.';}
  else if(skill==='time-seconds'){const m=q.prompt.match(/^(\d+)분 (\d+)초/);prompt='Expresa '+m[1]+' min y '+m[2]+' s en segundos.';reason=q.reason.replaceAll('입니다.','')+' s; 1 min = 60 s.';}
  else if(skill==='flat-basic'){prompt='Escribe el nombre de la figura.';reason='Observa los lados rectos y las líneas curvas.';}
  else if(skill==='flat-count'){prompt='¿Cuántos lados rectos tiene la figura?';reason='El triángulo tiene 3 lados y el cuadrilátero 4; el círculo no tiene lados rectos.';}
  else if(skill==='lines'){prompt='¿La figura es una recta, una semirrecta o un segmento?';reason='El segmento tiene dos extremos; la semirrecta tiene un origen; la recta continúa en ambas direcciones.';}
  else if(skill==='polygon'){prompt='¿Cuántos lados tiene el polígono?';reason='Sigue el contorno y cuenta cada lado una sola vez.';}
  else if(skill==='factor'){const n=q.prompt.match(/^(\d+)/)[0];prompt='Escribe todos los divisores positivos de '+n+'.';reason='Busca los números naturales que dividen '+n+' sin dejar resto.';}
  else if(skill==='multiple'){const n=q.prompt.match(/^(\d+)/)[0];prompt='Escribe los tres primeros múltiplos positivos de '+n+' en orden creciente.';reason='Multiplica '+n+' por 1, 2 y 3.';}
  else if(skill==='round-nearest'){const n=q.prompt.match(/^(\d+)/)[0],place=q.prompt.includes('십')?'decena':'centena';prompt='Redondea '+n+' a la '+place+' más cercana.';reason='Observa la cifra inmediatamente a la derecha: si es 5 o mayor, sube al siguiente múltiplo; si es menor, conserva el inferior.';}
  else if(skill==='mixed'||skill==='mixed-bracket'){prompt='Calcula respetando el orden de las operaciones.';reason=skill==='mixed-bracket'?'Calcula primero la suma entre paréntesis y después multiplica.':'Realiza primero la multiplicación y después la suma.';}
  else if(skill==='common-denominator'){const n=q.reason.match(/는 (\d+)/)[1];prompt='Escribe las fracciones con el mínimo denominador común.';reason='El mínimo común múltiplo de los denominadores es '+n+'.';}
  else if(['area-triangle','area-parallelogram','area-trapezoid','area-rhombus'].includes(skill)){const c=q.check;const details=skill==='area-trapezoid'?'trapecio de bases '+c.a+' cm y '+c.c+' cm y altura '+c.b+' cm':skill==='area-rhombus'?'rombo de diagonales '+c.a+' cm y '+c.b+' cm':(skill==='area-triangle'?'triángulo':'paralelogramo')+' de base '+c.a+' cm y altura '+c.b+' cm';prompt='Calcula el área en cm² del '+details+'.';if(i===1)prompt+=' Elige el resultado.';if(i===2)prompt+=' Comprueba la respuesta propuesta.';reason=(skill==='area-trapezoid'?'('+c.a+' + '+c.c+') × '+c.b+' ÷ 2':c.a+' × '+c.b+(skill==='area-parallelogram'?'':' ÷ 2'))+' = '+c.result+' cm²';}
  else if(skill==='percent'){const m=q.prompt.match(/전체 (\d+)개 중 (\d+)개/);prompt='¿Qué porcentaje representan '+m[2]+' elementos de un total de '+m[1]+'?';reason='Divide la parte entre el total y multiplica por 100.';}
  else if(skill==='chance'){prompt=q.prompt.includes('빨간 공만')?'Una caja contiene solo bolas rojas. ¿Qué probabilidad hay de sacar una bola azul?':q.prompt.includes('파란 공만')?'Una caja contiene solo bolas azules. ¿Qué probabilidad hay de sacar una bola azul?':'Una caja contiene una bola roja y una azul. Sacas una al azar sin mirar: ¿qué probabilidad hay de que sea roja?';reason='Compara el color y el número de bolas que hay en la caja.';}
  else if(skill==='average-missing'){const n=q.prompt.match(/평균이 (\d+)/)[1],sum=q.reason.match(/합 (\d+)/)[1];prompt='La media de los tres números es '+n+'. Encuentra el número que falta.';reason='La suma de los tres números es '+sum+'. Resta los dos números conocidos.';}
  else if(['cube-count','cube-view','cube-missing'].includes(skill)){prompt=skill==='cube-view'?'¿Cuántos cuadrados se ven en la vista '+(q.prompt.startsWith('앞')?'frontal':'desde la derecha')+'?':skill==='cube-missing'?'Quita todos los cubos de la columna situada arriba a la izquierda en el plano. ¿Cuántos cubos quedan?':'¿Cuántos cubos hay en total?';reason=d[4]==='2-1-2'?'Cuenta una vez cada cubo dibujado.':skill==='cube-view'?'En cada fila de la dirección de observación toma la altura de la columna más alta; después suma las alturas.':q.reason;}
  else if(skill==='solid-basic'){prompt="¿Cómo se llama el cuerpo geométrico representado?";reason="Observa las superficies planas y curvas. Compara el dibujo con un objeto real.";}
  else if(skill==='sort'){prompt="¿Cuántos símbolos iguales a "+q.prompt[0]+" hay?";reason="Agrupa los símbolos de la misma forma y cuéntalos.";}
  else if(skill==='length-compare'){prompt="¿Qué barra es más larga, A o B?";reason="Las barras empiezan en el mismo punto. Compara hasta dónde llegan.";}
  else if(skill==='pattern'){prompt="¿Qué símbolo continúa la serie?";reason="Se repite este grupo: "+q.reason.replace('가 반복됩니다.','')+'.';}
  else if(skill==='sequence'){prompt="Escribe el número que falta.";reason="Cada número aumenta en "+q.reason.match(/^\d+/)[0]+'.';}
  else if(skill==='bond'){const m=q.prompt.match(/^(\d+)을 (\d+)과/);prompt="Descompón "+m[1]+" en "+m[2]+" y otra parte. ¿Cuál es la parte que falta?";reason=q.reason;}
  else if(skill==='circle-parts'){prompt="¿Cómo se llama el segmento que une el centro con un punto de la circunferencia?";reason="El radio une el centro con un punto de la circunferencia.";}
  else if(skill==='circle-size'){prompt="¿Cuánto mide el diámetro en cm?";reason="El diámetro es el doble del radio.";}
  else if(skill==='triangle-type'){prompt="Clasifica por sus ángulos un triángulo cuyos ángulos miden "+q.prompt.match(/세 각이 (.*?)인/)[1]+'.';reason="Comprueba si hay un ángulo recto u obtuso; si todos son agudos, es un triángulo acutángulo.";}
  else if(skill==='quad-type'){const idx=q.prompt.startsWith('네 각이 직각이고 가로')?0:q.prompt.startsWith('네 각이 직각이고 네 변')?1:q.prompt.startsWith('네 변이 같고')?2:3;prompt=["Tiene cuatro ángulos rectos y lados de 6 cm y 3 cm.","Tiene cuatro ángulos rectos y cuatro lados de 4 cm.","Tiene cuatro lados iguales y un ángulo de 60°.","Tiene dos parejas de lados opuestos paralelos, lados consecutivos de 4 cm y 6 cm y un ángulo de 60°."][idx]+" ¿Cuál es el nombre más específico del cuadrilátero?";reason="Usa las longitudes y los ángulos juntos. Elige el nombre más específico, aunque la figura pertenezca también a una familia más amplia.";}
  else if(skill==='count'){prompt='¿Cuántos puntos hay?';reason='Cuenta cada punto una sola vez.';}
  else if(skill==='compare'){prompt='Compara los números. ¿Qué signo es correcto?';reason='Compara las cantidades y usa >, < o =.';}
  else if(skill==='place'){const m=q.prompt.match(/^(\d+)에서 (일|십|백|천)의/),place=({일:'las unidades',십:'las decenas',백:'las centenas',천:'los millares'})[m[2]];prompt='¿Cuál es la cifra de '+place+' en el número '+m[1]+'?';reason='Desde la derecha se encuentran las unidades, decenas, centenas y unidades de millar.';}
  else if(skill==='angle-right'){prompt='¿La figura muestra un ángulo recto?';reason='Compara el ángulo con la esquina de una hoja rectangular.';}
  else if(skill==='symmetry-line'){prompt='¿Cuántos ejes de simetría tiene un cuadrado?';reason='Dos ejes pasan por los puntos medios de los lados y otros dos son las diagonales.';}
  else if(skill==='fraction-model'){prompt='¿Qué fracción representa la parte coloreada?';reason='El denominador indica todas las partes iguales; el numerador, las partes coloreadas.';}
  else{prompt='Compara las dos fracciones.';reason='Si los denominadores son iguales, compara los numeradores.';}
  if(!q.check&&!skill.startsWith('time-clock')&&i===1)prompt+=' Elige la respuesta.';
  if(!q.check&&!skill.startsWith('time-clock')&&i===2)prompt+=' Comprueba la respuesta propuesta.';
  const display=(skill.startsWith('time-clock')||skill==='time-duration')?s=>timeText(tr(geometryText(s))):skill.startsWith('metric-')?s=>tr(geometryText(s)):skill.startsWith('data-')?s=>tr(bankText(geometryText(s))):skill.startsWith('geometry-')?s=>tr(geometryText(s)):skill==='length-compare'?s=>tr(compareText(s)):skill.startsWith('decimal-')?s=>decimalText(tr(s)):['table','graph'].includes(skill)?s=>dataText(tr(s)):tr;
  return {...q,prompt:skill.startsWith('decimal-')?decimalText(prompt):prompt,reason:skill.startsWith('decimal-')?decimalText(reason):reason,visual:display(q.visual),task:display(q.task),answer:display(q.answer)};
 })}));
}};
})();
